/*
 * University of Arizona — undergraduate college/major catalog.
 * Engineering + College of Science lead (CS, Astronomy, Neuroscience, Optical, Physiology);
 * Eller business, land-grant ALES, and the other major colleges included.
 */

export const COLLEGE_MAJORS: Record<string, string[]> = {
  'College of Engineering': [
    'Aerospace Engineering',
    'Architectural Engineering',
    'Biomedical Engineering',
    'Biosystems Engineering',
    'Chemical Engineering',
    'Civil Engineering',
    'Electrical and Computer Engineering',
    'Engineering Management',
    'Environmental Engineering',
    'Industrial Engineering',
    'Materials Science and Engineering',
    'Mechanical Engineering',
    'Mining Engineering',
    'Optical Sciences and Engineering',
    'Systems Engineering',
  ],
  'College of Science': [
    'Astronomy',
    'Biochemistry',
    'Biology',
    'Chemistry',
    'Computer Science',
    'Ecology and Evolutionary Biology',
    'Geosciences',
    'Atmospheric Sciences',
    'Mathematics',
    'Molecular and Cellular Biology',
    'Neuroscience',
    'Physics',
    'Physiology',
    'Psychology',
    'Statistics and Data Science',
    'Speech, Language, and Hearing Sciences',
  ],
  'Eller College of Management': [
    'Accounting',
    'Business Economics',
    'Business Management',
    'Economics',
    'Entrepreneurship',
    'Finance',
    'Management Information Systems',
    'Marketing',
    'Operations Management',
  ],
  'College of Agriculture, Life and Environmental Sciences': [
    'Agricultural Economics',
    'Animal Sciences',
    'Environmental Science',
    'Microbiology',
    'Nutritional Sciences',
    'Plant Sciences',
    'Wildlife Conservation',
  ],
  'College of Social and Behavioral Sciences': [
    'Anthropology',
    'Communication',
    'Geography',
    'History',
    'Journalism',
    'Linguistics',
    'Philosophy',
    'Political Science',
    'Sociology',
    'Africana Studies',
    'American Indian Studies',
  ],
  'College of Humanities': [
    'English',
    'Classics',
    'East Asian Studies',
    'French',
    'German Studies',
    'Italian',
    'Religious Studies',
    'Russian',
    'Spanish',
    'Middle Eastern and North African Studies',
  ],
  'College of Fine Arts': [
    'Art History',
    'Studio Art',
    'Dance',
    'Music',
    'Music Education',
    'Theatre',
    'Film & Television',
  ],
  'College of Architecture, Planning and Landscape Architecture': [
    'Architecture',
    'Landscape Architecture',
    'Sustainable Built Environments',
  ],
  'College of Education': [
    'Early Childhood Education',
    'Elementary Education',
    'Secondary Education',
    'Special Education',
  ],
  'College of Nursing': [
    'Nursing',
  ],
  'Mel and Enid Zuckerman College of Public Health': [
    'Public Health',
  ],
  'College of Information Science': [
    'Information Science',
    'Data Science',
  ],
};
