/*
 * Arizona State University — undergraduate college/major catalog.
 * Ira A. Fulton Schools of Engineering + The College (natural sciences) lead;
 * business, design/arts, and the professional colleges follow.
 */

export const COLLEGE_MAJORS: Record<string, string[]> = {
  'Ira A. Fulton Schools of Engineering': [
    'Computer Science',
    'Computer Engineering',
    'Software Engineering',
    'Informatics',
    'Electrical Engineering',
    'Mechanical Engineering',
    'Aerospace Engineering',
    'Chemical Engineering',
    'Civil Engineering',
    'Environmental Engineering',
    'Materials Science and Engineering',
    'Industrial Engineering',
    'Biomedical Engineering',
    'Robotics',
    'Manufacturing Engineering',
    'Construction Engineering',
    'Construction Management',
    'Engineering Management',
  ],
  'The College of Liberal Arts and Sciences': [
    'Physics',
    'Chemistry',
    'Biochemistry',
    'Mathematics',
    'Statistics',
    'Actuarial Science',
    'Data Science',
    'Biological Sciences',
    'Microbiology',
    'Neuroscience',
    'Molecular Biosciences and Biotechnology',
    'Astrophysics',
    'Geology',
    'Environmental Science',
    'Psychology',
    'Economics',
    'Anthropology',
    'English',
    'History',
    'Political Science',
    'Sociology',
    'Philosophy',
    'Geography',
  ],
  'W. P. Carey School of Business': [
    'Accountancy',
    'Finance',
    'Marketing',
    'Management',
    'Supply Chain Management',
    'Business Analytics',
    'Information Systems',
    'Business Administration',
  ],
  'Herberger Institute for Design and the Arts': [
    'Architecture',
    'Industrial Design',
    'Graphic Design',
    'Interior Design',
    'Landscape Architecture',
    'Art',
    'Music',
    'Dance',
    'Theatre',
    'Film and Media Studies',
  ],
  'Walter Cronkite School of Journalism and Mass Communication': [
    'Journalism',
    'Sports Journalism',
    'Media Studies',
  ],
  'Watts College of Public Service and Community Solutions': [
    'Criminology and Criminal Justice',
    'Social Work',
    'Public Policy',
    'Urban and Regional Planning',
    'Nonprofit Leadership and Management',
    'Emergency Management and Homeland Security',
  ],
  'College of Health Solutions': [
    'Health Sciences',
    'Nutrition',
    'Kinesiology',
    'Public Health',
    'Speech and Hearing Sciences',
  ],
  'Edson College of Nursing and Health Innovation': [
    'Nursing',
    'Integrative Health',
  ],
  'Mary Lou Fulton Teachers College': [
    'Elementary Education',
    'Secondary Education',
    'Special Education',
    'Early Childhood Education',
  ],
  'College of Global Futures': [
    'Sustainability',
    'Sustainable Food Systems',
    'Environmental and Resource Management',
  ],
};
