/*
 * University of Colorado Boulder — undergraduate college/major catalog.
 * Generated 2026-07-06 from the official CU Boulder Catalog; do not hand-edit.
 * Verified against:
 *   https://catalog.colorado.edu/undergraduate/colleges-schools/ (2025-26 edition)
 * Note: Built from the per-degree pages under each college's Programs of Study
 * (only entries with a Bachelor of Arts/Science/Music/Fine Arts page; minors,
 * certificates and the post-baccalaureate BSACS dropped); degree suffixes
 * stripped and same-name BA/BS variants merged. College names use their
 * official full forms.
 */

export const COLLEGE_MAJORS: Record<string, string[]> = {
  'College of Arts and Sciences': [
    'Anthropology',
    'Art History',
    'Art Practices',
    'Asian Studies',
    'Astrophysical and Planetary Sciences',
    'Atmospheric and Oceanic Sciences',
    'Biochemistry',
    'Chemistry',
    'Chinese',
    'Cinema Studies',
    'Cinema Studies & Moving Image Arts',
    'Classics',
    'Dance',
    'Earth Science',
    'Ecology and Evolutionary Biology',
    'Economics',
    'English',
    'Environmental Studies',
    'Ethnic Studies',
    'French',
    'Geography',
    'German Studies',
    'History',
    'Humanities',
    'Integrative Physiology',
    'International Affairs',
    'Italian',
    'Japanese',
    'Jewish Studies',
    'Linguistics',
    'Mathematics',
    'Molecular, Cellular and Developmental Biology',
    'Neuroscience',
    'Philosophy',
    'Physics',
    'Political Science',
    'Psychology',
    'Public Health',
    'Religious Studies',
    'Russian Studies',
    'Sociology',
    'Spanish',
    'Speech, Language and Hearing Sciences',
    'Statistics and Data Science',
    'Theatre',
    'Women and Gender Studies',
  ],
  'Leeds School of Business': [
    'Business Administration',
    'Integrated Business and Engineering',
  ],
  'College of Communication, Media, Design and Information': [
    'Architecture',
    'Communication',
    'Environmental Products of Design',
    'Information Science',
    'Journalism',
    'Landscape Architecture',
    'Media Production',
    'Media Studies',
    'Strategic Communication',
    'Sustainable Planning and Urban Design',
  ],
  'School of Education': [
    'Education Studies',
    'Elementary Education',
    'Leadership and Community Engagement',
    'Middle and High School Teaching',
  ],
  'College of Engineering and Applied Science': [
    'Aerospace Engineering Sciences',
    'Applied Mathematics',
    'Architectural Engineering',
    'Biological Engineering',
    'Biomedical Engineering',
    'Chemical Engineering',
    'Civil Engineering',
    'Computer Science',
    'Creative Technology and Design',
    'Electrical Engineering',
    'Electrical and Computer Engineering',
    'Engineering Physics',
    'Environmental Engineering',
    'Mechanical Engineering',
  ],
  'College of Music': [
    'Music',
    'Music Education',
  ],
};
