/*
 * Carleton College — undergraduate college/major catalog.
 * Generated from live recon; majors are official undergraduate programs.
 */

export const COLLEGE_MAJORS: Record<string, string[]> = {
  'Mathematics and Natural Sciences': [
    'Biology',
    'Chemistry',
    'Biochemistry',
    'Physics',
    'Astronomy',
    'Mathematics',
    'Statistics',
    'Computer Science',
    'Geology',
    'Psychology',
    'Neuroscience',
    'Environmental Studies',
  ],
  'Social Sciences': [
    'Economics',
    'Political Science',
    'International Relations',
    'Sociology',
    'Anthropology',
    'Educational Studies',
    'Public Policy',
    'Archaeology',
    'Cognitive Science',
  ],
  'Humanities': [
    'English',
    'Creative Writing',
    'History',
    'Philosophy',
    'Religion',
    'Classics',
    'Greek',
    'Latin',
    'Linguistics',
    'French',
    'Spanish',
    'German',
    'Russian',
    'Chinese',
    'Japanese',
    'Arabic',
    'Africana Studies',
    'American Studies',
    'Asian Studies',
    'European Studies',
    'Latin American Studies',
    'Judaic Studies',
    'Middle East Studies',
  ],
  'Arts': [
    'Studio Art',
    'Art History',
    'Music',
    'Theater',
    'Dance',
    'Cinema and Media Studies',
  ],
};
