/*
 * Columbia University — undergraduate college/major catalog.
 * Columbia College, the Fu Foundation School of Engineering and Applied
 * Science, and the School of General Studies (whose students take the same
 * Arts & Sciences majors); reuses existing i18n labels where possible.
 */

export const COLLEGE_MAJORS: Record<string, string[]> = {
  'Columbia College': [
    'African American and African Diaspora Studies',
    'American Studies',
    'Anthropology',
    'Architecture',
    'Art History',
    'Astronomy',
    'Astrophysics',
    'Biochemistry',
    'Biology',
    'Chemistry',
    'Classics',
    'Comparative Literature and Society',
    'Computer Science',
    'Creative Writing',
    'Earth and Environmental Sciences',
    'East Asian Languages and Cultures',
    'Economics',
    'English',
    'Film and Media Studies',
    'French',
    'German',
    'History',
    'Human Rights',
    'Italian',
    'Latin American and Caribbean Studies',
    'Linguistics',
    'Mathematics',
    'Middle Eastern, South Asian, and African Studies',
    'Music',
    'Neuroscience and Behavior',
    'Philosophy',
    'Physics',
    'Political Science',
    'Psychology',
    'Religion',
    'Slavic Studies',
    'Sociology',
    'Spanish',
    'Statistics',
    'Sustainable Development',
    'Theatre',
    'Urban Studies',
    'Visual Arts',
    "Women's and Gender Studies",
  ],
  'Fu Foundation School of Engineering and Applied Science': [
    'Applied Mathematics',
    'Applied Physics',
    'Biomedical Engineering',
    'Chemical Engineering',
    'Civil Engineering',
    'Computer Engineering',
    'Computer Science',
    'Earth and Environmental Engineering',
    'Electrical Engineering',
    'Industrial Engineering and Operations Research',
    'Materials Science and Engineering',
    'Mechanical Engineering',
  ],
  'School of General Studies': [
    'Anthropology',
    'Computer Science',
    'Economics',
    'English',
    'History',
    'Mathematics',
    'Political Science',
    'Psychology',
    'Sociology',
  ],
};
