/*
 * Cornell University — undergraduate major catalog.
 * Compiled 2026-07-12 from Cornell's official student-facing sources; do not hand-edit.
 * Verified against:
 *   https://admissions.cornell.edu/academics/majors
 *   https://www.cornell.edu/academics/fields.cfm
 *   https://as.cornell.edu/majors-and-minors  •  https://cals.cornell.edu/education/degrees-programs
 * Notes: grouped by the enrolling college/school. Cornell lists several majors under
 * more than one enrolling college (a student may be admitted through any of them) —
 * e.g. Computer Science / Information Science / Statistical Science (Bowers CIS, enrolled
 * via A&S and/or Engineering), Applied Economics & Management (CALS + SC Johnson Business),
 * Biological/Environmental Engineering and Earth & Climate Sciences (CALS + Engineering).
 * Those appear under each enrolling college, mirroring the official picker.
 */

export const COLLEGE_MAJORS: Record<string, string[]> = {
  'College of Arts & Sciences': [
    'Africana Studies',
    'American Studies',
    'Anthropology',
    'Archaeology',
    'Asian Studies',
    'Astronomy',
    'Biological Sciences',
    'Biology & Society',
    'Chemistry',
    'China & Asia-Pacific Studies',
    'Classics',
    'Cognitive Science',
    'College Scholar Program',
    'Comparative Literature',
    'Computer Science',
    'Earth and Climate Sciences',
    'Economics',
    'English',
    'Environment and Sustainability',
    'Feminist, Gender & Sexuality Studies',
    'French',
    'German Studies',
    'Government',
    'History',
    'History of Art',
    'Information Science',
    'Italian',
    'Jewish Studies',
    'Latina/o Studies',
    'Linguistics',
    'Mathematics',
    'Music',
    'Near Eastern Studies',
    'Performing & Media Arts',
    'Philosophy',
    'Physics',
    'Psychology',
    'Public Policy',
    'Religious Studies',
    'Science, Technology, and Society',
    'Sociology',
    'Spanish',
    'Statistical Science',
  ],
  'College of Agriculture & Life Sciences': [
    'Agricultural Sciences',
    'Animal Science',
    'Applied Economics and Management',
    'Atmospheric Science',
    'Biological Engineering',
    'Biological Sciences',
    'Biology and Society',
    'Communication',
    'Earth and Climate Sciences',
    'Entomology',
    'Environment and Sustainability',
    'Environmental Engineering',
    'Food Science',
    'Global and Public Health Sciences',
    'Global Development',
    'Information Science',
    'Interdisciplinary Studies',
    'Landscape Architecture',
    'Nutritional Sciences',
    'Plant Sciences',
    'Statistics and Biometry',
    'Viticulture and Enology',
  ],
  'College of Engineering': [
    'Biological Engineering',
    'Biomedical Engineering',
    'Chemical Engineering',
    'Civil Engineering',
    'Computer Science',
    'Earth and Climate Sciences',
    'Electrical and Computer Engineering',
    'Engineering Physics',
    'Environmental Engineering',
    'Independent Major',
    'Information Science',
    'Materials Science and Engineering',
    'Mechanical Engineering',
    'Operations Research and Engineering',
  ],
  'College of Human Ecology': [
    'Design and Environmental Analysis',
    'Fashion Design and Management',
    'Fiber Science',
    'Global and Public Health Sciences',
    'Human Biology, Health, and Society',
    'Human Development',
    'Nutritional Sciences',
  ],
  'School of Industrial and Labor Relations': [
    'Industrial and Labor Relations',
  ],
  'College of Architecture, Art, and Planning': [
    'Architecture',
    'Fine Arts',
    'Urban and Regional Studies',
  ],
  'SC Johnson College of Business': [
    'Applied Economics and Management',
    'Hotel Administration',
  ],
  'Bowers College of Computing and Information Science': [
    'Computer Science',
    'Information Science',
    'Information Science, Systems, and Technology',
    'Statistical Science',
    'Statistics and Biometry',
  ],
  'Brooks School of Public Policy': [
    'Health Care Policy',
    'Public Policy',
  ],
};
