/*
 * Michigan State University — undergraduate college/major catalog.
 * Engineering + Natural Science lead; land-grant CANR, Broad Business, and the
 * residential-heavy arts/social-science colleges included.
 */

export const COLLEGE_MAJORS: Record<string, string[]> = {
  'College of Engineering': [
    'Computer Science',
    'Computer Engineering',
    'Electrical Engineering',
    'Mechanical Engineering',
    'Chemical Engineering',
    'Civil Engineering',
    'Environmental Engineering',
    'Materials Science and Engineering',
    'Biosystems Engineering',
    'Applied Engineering Sciences',
    'Computational Data Science',
  ],
  'College of Natural Science': [
    'Physics',
    'Chemistry',
    'Mathematics',
    'Statistics',
    'Astrophysics',
    'Biochemistry and Molecular Biology',
    'Microbiology',
    'Neuroscience',
    'Physiology',
    'Human Biology',
    'Biology',
    'Plant Biology',
    'Zoology',
    'Genomics and Molecular Genetics',
    'Geological Sciences',
    'Actuarial Science',
  ],
  'College of Agriculture and Natural Resources': [
    'Agribusiness Management',
    'Animal Science',
    'Crop and Soil Sciences',
    'Food Science',
    'Horticulture',
    'Forestry',
    'Fisheries & Wildlife',
    'Entomology',
    'Nutritional Sciences',
    'Packaging',
    'Environmental Studies and Sustainability',
  ],
  'Eli Broad College of Business': [
    'Accounting',
    'Finance',
    'Management',
    'Marketing',
    'Supply Chain Management',
    'Human Resource Management',
    'Hospitality Business',
  ],
  'College of Social Science': [
    'Psychology',
    'Economics',
    'Political Science',
    'Sociology',
    'Anthropology',
    'Geography',
    'Criminal Justice',
    'Social Work',
    'Human Development and Family Studies',
    'Urban and Regional Planning',
  ],
  'College of Arts and Letters': [
    'English',
    'History',
    'Philosophy',
    'Linguistics',
    'Studio Art',
    'Art History',
    'Religious Studies',
    'Women and Gender Studies',
  ],
  'College of Communication Arts and Sciences': [
    'Communication',
    'Journalism',
    'Advertising',
    'Media and Information',
    'Communication Sciences and Disorders',
  ],
  'College of Education': [
    'Kinesiology',
    'Athletic Training',
    'Elementary Education',
    'Special Education',
  ],
  'College of Music': [
    'Music',
    'Music Performance',
    'Music Composition',
    'Music Education',
    'Jazz Studies',
  ],
  'College of Nursing': [
    'Nursing',
  ],
};
