/*
 * University of Pittsburgh — undergraduate college/major catalog.
 * Swanson (Engineering) + SCI (Computing) + Dietrich sciences lead; professional schools included.
 */

export const COLLEGE_MAJORS: Record<string, string[]> = {
  'Swanson School of Engineering': [
    'Bioengineering',
    'Chemical Engineering',
    'Civil Engineering',
    'Computer Engineering',
    'Electrical Engineering',
    'Engineering Science',
    'Environmental Engineering',
    'Industrial Engineering',
    'Materials Science and Engineering',
    'Mechanical Engineering',
  ],
  'School of Computing and Information': [
    'Computer Science',
    'Information Science',
    'Computational Biology',
    'Digital Narrative and Interactive Design',
  ],
  'Kenneth P. Dietrich School of Arts and Sciences': [
    'Physics',
    'Astronomy',
    'Chemistry',
    'Mathematics',
    'Applied Mathematics',
    'Statistics',
    'Biological Sciences',
    'Neuroscience',
    'Molecular Biology',
    'Biochemistry',
    'Geology',
    'Environmental Science',
    'Environmental Studies',
    'Psychology',
    'Economics',
    'Political Science',
    'Sociology',
    'Anthropology',
    'History',
    'English',
    'Philosophy',
    'Communication',
    'Linguistics',
    'Religious Studies',
    'Africana Studies',
    'History and Philosophy of Science',
    'French',
    'Spanish',
    'German',
    'Music',
    'Theatre Arts',
    'Film and Media Studies',
    'History of Art and Architecture',
    'Urban Studies',
  ],
  'College of Business Administration': [
    'Accounting',
    'Finance',
    'Marketing',
    'Supply Chain Management',
    'Business Analytics',
    'Business Information Systems',
    'Human Resources Management',
    'Global Management',
  ],
  'School of Nursing': [
    'Nursing',
  ],
  'School of Health and Rehabilitation Sciences': [
    'Rehabilitation Science',
    'Health Information Management',
    'Emergency Medicine',
    'Communication Science and Disorders',
  ],
  'School of Education': [
    'Applied Developmental Psychology',
  ],
  'School of Social Work': [
    'Social Work',
  ],
};
