/*
 * Penn State — undergraduate college/major catalog.
 * Engineering + Eberly Science lead; land-grant colleges included.
 */

export const COLLEGE_MAJORS: Record<string, string[]> = {
  'College of Engineering': [
    'Computer Science',
    'Computer Engineering',
    'Electrical Engineering',
    'Mechanical Engineering',
    'Aerospace Engineering',
    'Biomedical Engineering',
    'Chemical Engineering',
    'Industrial Engineering',
  ],
  'Eberly College of Science': [
    'Physics',
    'Chemistry',
    'Mathematics',
    'Statistics',
    'Biology',
    'Biochemistry and Molecular Biology',
    'Astronomy and Astrophysics',
    'Premedicine',
  ],
  'Smeal College of Business': [
    'Finance',
    'Accounting',
    'Marketing',
    'Management',
    'Supply Chain and Information Systems',
    'Risk Management',
    'Real Estate',
  ],
  'College of Information Sciences and Technology': [
    'Information Sciences and Technology',
    'Cybersecurity Analytics and Operations',
    'Data Sciences',
    'Human-Centered Design and Development',
    'Enterprise Technology Integration',
  ],
  'College of Agricultural Sciences': [
    'Animal Science',
    'Food Science',
    'Plant Science',
    'Forest Ecosystem Management',
    'Agribusiness Management',
    'Agricultural and Biological Engineering',
    'Veterinary and Biomedical Sciences',
  ],
  'College of the Liberal Arts': [
    'Psychology',
    'Economics',
    'Political Science',
    'English',
    'History',
    'Sociology',
    'Criminology',
    'Philosophy',
  ],
  'College of Health and Human Development': [
    'Kinesiology',
    'Nutritional Sciences',
    'Biobehavioral Health',
    'Human Development and Family Studies',
    'Communication Sciences and Disorders',
    'Health Policy and Administration',
    'Hospitality Management',
  ],
  'College of Earth and Mineral Sciences': [
    'Materials Science and Engineering',
    'Meteorology and Atmospheric Science',
    'Geosciences',
    'Geography',
    'Petroleum and Natural Gas Engineering',
    'Energy Business and Finance',
    'Energy Engineering',
  ],
  'Donald P. Bellisario College of Communications': [
    'Journalism',
    'Advertising/Public Relations',
    'Film Production',
    'Telecommunications and Media Industries',
  ],
  'College of Arts and Architecture': [
    'Architecture',
    'Landscape Architecture',
    'Graphic Design',
    'Music',
    'Theatre',
    'Art History',
  ],
  'College of Nursing': [
    'Nursing',
  ],
  'College of Education': [
    'Elementary and Early Childhood Education',
    'Secondary Education',
    'Special Education',
    'Rehabilitation and Human Services',
    'Education and Public Policy',
  ],
};
