/*
 * Purdue University — undergraduate college/major catalog (launch set).
 * College->major taxonomy from the official catalog; reuses existing i18n
 * labels where possible. Expandable as more programs are added.
 */

export const COLLEGE_MAJORS: Record<string, string[]> = {
  'College of Engineering': [
    'Aeronautical and Astronautical Engineering',
    'Biomedical Engineering',
    'Chemical Engineering',
    'Civil Engineering',
    'Computer Engineering',
    'Construction Engineering',
    'Electrical Engineering',
    'Industrial Engineering',
    'Materials Engineering',
    'Mechanical Engineering',
    'Multidisciplinary Engineering',
    'Nuclear Engineering',
    'Environmental and Ecological Engineering',
  ],
  'College of Science': [
    'Artificial Intelligence',
    'Computer Science',
    'Data Science',
    'Mathematics',
    'Statistics',
    'Physics',
    'Chemistry',
    'Biology',
    'Biochemistry',
    'Actuarial Science',
    'Atmospheric Science',
    'Earth, Atmospheric, and Planetary Sciences',
  ],
  'College of Agriculture': [
    'Agribusiness',
    'Agricultural Economics',
    'Animal Sciences',
    'Biochemistry',
    'Crop, Soil and Agroecosystem Sciences',
    'Food Science',
    'Plant Science',
    'Natural Resources and Environmental Science',
  ],
  'Mitchell E. Daniels, Jr. School of Business': [
    'Accounting',
    'Economics',
    'Finance',
    'General Management',
    'Marketing',
    'Supply Chain and Operations Management',
    'Business Analytics and Information Management',
  ],
  'College of Liberal Arts': [
    'Economics',
    'English',
    'History',
    'Political Science',
    'Sociology',
    'Communication',
    'Philosophy',
    'Linguistics',
  ],
  'College of Health and Human Sciences': [
    'Nursing',
    'Nutrition Science',
    'Public Health',
    'Psychological Sciences',
    'Kinesiology',
    'Biomedical Health Sciences',
    'Hospitality and Tourism Management',
    'Developmental and Family Science',
    'Speech, Language, and Hearing Sciences',
  ],
  'Purdue Polytechnic Institute': [
    'Professional Flight',
    'Aviation Management',
    'Aeronautical Engineering Technology',
    'Construction Management',
    'Cybersecurity',
    'Electrical Engineering Technology',
    'Mechanical Engineering Technology',
    'Robotics Engineering Technology',
    'Computer and Information Technology',
  ],
  'College of Pharmacy': [
    'Pharmaceutical Sciences',
  ],
  'College of Education': [
    'Elementary Education',
    'Special Education',
  ],
  'College of Veterinary Medicine': [
    'Veterinary Nursing',
  ],
};
