/*
 * Stanford — undergraduate college/major catalog.
 * Generated 2026-06-12 from the officially-verified research dataset; do not hand-edit.
 * Verified against:
 *   https://majors.stanford.edu/majors
 *   https://majors.stanford.edu/interactive-search-majors-and-more
 *   https://majors.stanford.edu/opportunities/mathematics
 *   https://majors.stanford.edu/opportunities/mathematical-and-computational-science
 * Note: From the official Explore Majors portal filtered by school x degree type; minor/coterm/honors-only entries excluded; Mathematics included from knowledge (its portal entry is mis-tagged); CS+X joint majors fold into the listed majors.
 */

export const COLLEGE_MAJORS: Record<string, string[]> = {
  'School of Humanities and Sciences': [
    'African and African American Studies',
    'American Studies',
    'Anthropology',
    'Archaeology',
    'Art History',
    'Art Practice',
    'Asian American Studies',
    'Biology',
    'Chemistry',
    'Chicana/o - Latina/o Studies',
    'China Studies',
    'Classics',
    'Communication',
    'Comparative Literature',
    'Comparative Studies in Race and Ethnicity',
    'Data Science',
    'Data Science & Social Systems',
    'Data Science for Artistic and Cultural Analysis',
    'East Asian Studies',
    'Economics',
    'English',
    'Feminist, Gender, and Sexuality Studies',
    'Film and Media Studies',
    'French',
    'German Studies',
    'History',
    'Human Biology',
    'Iberian and Latin American Cultures',
    'International Relations',
    'Italian',
    'Japanese',
    'Jewish Studies',
    'Korean',
    'Linguistics',
    'Mathematics',
    'Music',
    'Native American Studies',
    'Philosophy',
    'Philosophy and Religious Studies',
    'Physics',
    'Political Science',
    'Psychology',
    'Public Policy',
    'Religious Studies',
    'Science, Technology, and Society',
    'Slavic Languages and Literatures',
    'Sociology',
    'Spanish',
    'Statistics',
    'Symbolic Systems',
    'Theater and Performance Studies',
    'Urban Studies',
  ],
  'School of Engineering': [
    'Aeronautics and Astronautics',
    'Atmosphere/Energy',
    'Bioengineering',
    'Biomechanical Engineering',
    'Biomedical Computation',
    'Chemical Engineering',
    'Civil Engineering',
    'Computer Science',
    'Design',
    'Electrical Engineering',
    'Engineering Physics',
    'Environmental Systems Engineering',
    'Management Science and Engineering',
    'Materials Science and Engineering',
    'Mechanical Engineering',
    'Sustainable Architecture + Engineering',
  ],
  'Stanford Doerr School of Sustainability': [
    'Earth Systems',
    'Earth and Planetary Sciences',
    'Energy Science and Engineering',
    'Geophysics',
  ],
};
