/*
 * UC Berkeley — undergraduate college/major catalog.
 * Generated 2026-06-12 from the officially-verified research dataset; do not hand-edit.
 * Verified against:
 *   https://admissions.berkeley.edu/majors/
 * Note: Verbatim from the official admissions majors list; M.E.T. 'X & Business Administration' simultaneous degrees count as majors, CS/Data Science/Statistics sit in the College of Computing, Data Science, and Society, 'Undeclared' placeholders excluded.
 */

export const COLLEGE_MAJORS: Record<string, string[]> = {
  'College of Letters and Science': [
    'African American Studies',
    'American Studies',
    'Analytics',
    'Ancient Greek and Roman Studies',
    'Anthropology',
    'Applied Mathematics',
    'Armenian',
    'Art, History of',
    'Art, Practice of',
    'Asian American and Asian Diaspora Studies',
    'Asian Area Studies I - China',
    'Asian Area Studies II - Japan',
    'Astrophysics',
    'Atmospheric Science',
    'Biochemistry and Molecular Biology',
    'Bosnian/Croatian/Serbian',
    'Celtic Studies',
    'Cell and Developmental Biology',
    'Chemistry',
    'Chicano Studies',
    'Chicanx Latinx Studies',
    'Chinese Language and Culture',
    'Cognitive Science',
    'Comparative Literature',
    'Czech',
    'Dance and Performance Studies',
    'Danish',
    'Developmental Studies',
    'Dutch Studies',
    'East Asian Religion, Thought, and Culture',
    'Economics',
    'Educational Sciences',
    'English',
    'Environmental Earth Science',
    'Ethnic Studies',
    'Film and Media',
    'Finnish',
    'French',
    'Gender and Women\'s Studies',
    'Genetics, Genomics, and Development',
    'Geography',
    'Geology',
    'Geophysics',
    'German',
    'Global Studies',
    'Greek',
    'Greek and Latin',
    'Hispanic Languages, Literature, and Bilingualism',
    'History',
    'Hungarian',
    'Immunology and Pathogenesis',
    'Integrative Biology',
    'Interdisciplinary Studies',
    'Italian Studies',
    'Japanese Language and Culture',
    'Korean Language and Culture',
    'Languages and Literature',
    'Languages, Literature, and Cultures of the Portuguese-Speaking World',
    'Languages, Literature, and Cultures of the Spanish-Speaking World',
    'Latin',
    'Latin American Languages, Literature, and Cultures',
    'Latin American Studies',
    'Legal Studies',
    'Linguistics',
    'Marine Science',
    'Mathematics',
    'Mathematics with Teaching Concentration',
    'Media Studies',
    'Middle Eastern Studies',
    'Middle Eastern Worlds',
    'Molecular Therapeutics',
    'Music',
    'Native American Studies',
    'Near Eastern Civilizations',
    'Neuroscience',
    'Norwegian',
    'Old Norse',
    'Peace and Conflict Studies',
    'Philosophy',
    'Physics',
    'Planetary Science',
    'Polish',
    'Political Economy',
    'Political Science',
    'Psychology',
    'Public Health',
    'Rhetoric',
    'Robinson Life Science, Business, and Entrepreneurship Program',
    'Russian',
    'Social Welfare',
    'Sociology',
    'South and Southeast Asian Studies',
    'Swedish',
    'Theater and Performance Studies',
  ],
  'College of Computing, Data Science, and Society': [
    'Computer Science',
    'Data Science',
    'Statistics',
  ],
  'College of Chemistry': [
    'Chemical Biology',
    'Chemical Engineering',
    'Chemistry',
  ],
  'College of Engineering': [
    'Aerospace Engineering',
    'Aerospace Engineering & Business Administration',
    'Bioengineering',
    'Bioengineering & Business Administration',
    'Civil Engineering',
    'Civil Engineering & Business Administration',
    'Electrical and Computer Engineering',
    'Electrical Engineering & Computer Sciences',
    'Electrical Engineering and Computer Sciences & Business Administration',
    'Energy Engineering',
    'Engineering Mathematics and Statistics',
    'Engineering Physics',
    'Environmental Engineering',
    'Environmental Engineering Science',
    'Industrial Engineering and Operations Research',
    'Industrial Engineering and Operations Research & Business Administration',
    'Materials Science and Engineering',
    'Materials Science and Engineering & Business Administration',
    'Mechanical Engineering',
    'Mechanical Engineering & Business Administration',
    'Nuclear Engineering',
  ],
  'College of Environmental Design': [
    'Architecture',
    'Landscape Architecture',
    'Sustainable Environmental Design',
    'Urban Studies',
  ],
  'Rausser College of Natural Resources': [
    'Conservation and Resource Studies',
    'Environmental Economics and Policy',
    'Environmental Sciences',
    'Forestry',
    'Genetics and Plant Biology',
    'Microbial Biology',
    'Molecular Environmental Biology',
    'Natural Resource Management',
    'Nutrition & Metabolic Biology',
    'Society and Environment',
  ],
  'Haas School of Business': [
    'Spieker Undergraduate Business Program',
  ],
};
