/*
 * UC Riverside — undergraduate college/major catalog.
 * Bourns Engineering + CNAS lead the STEM depth; CHASS carries the humanities/social-science mass.
 */

export const COLLEGE_MAJORS: Record<string, string[]> = {
  'Bourns College of Engineering': [
    'Bioengineering',
    'Chemical Engineering',
    'Computer Engineering',
    'Computer Science',
    'Computer Science with Business Applications',
    'Data Science',
    'Electrical Engineering',
    'Environmental Engineering',
    'Materials Science and Engineering',
    'Mechanical Engineering',
  ],
  'College of Natural and Agricultural Sciences': [
    'Biochemistry',
    'Biology',
    'Biomedical Sciences',
    'Cell, Molecular, and Developmental Biology',
    'Chemistry',
    'Earth Sciences',
    'Entomology',
    'Environmental Sciences',
    'Geology',
    'Geophysics',
    'Mathematics',
    'Applied Mathematics',
    'Microbiology',
    'Neuroscience',
    'Physics',
    'Plant Biology',
    'Statistics',
    'Sustainability Studies',
  ],
  'College of Humanities, Arts, and Social Sciences': [
    'Anthropology',
    'Art',
    'Art History',
    'Asian American Studies',
    'Business Economics',
    'Chicano Studies',
    'Comparative Literature',
    'Creative Writing',
    'Dance',
    'Economics',
    'English',
    'Ethnic Studies',
    'Gender and Sexuality Studies',
    'Global Studies',
    'History',
    'Liberal Studies',
    'Linguistics',
    'Media and Cultural Studies',
    'Music',
    'Philosophy',
    'Political Science',
    'Psychology',
    'Religious Studies',
    'Sociology',
    'Spanish',
    'Theatre, Film, and Digital Production',
  ],
  'School of Business': [
    'Business Administration',
  ],
  'School of Public Policy': [
    'Public Policy',
  ],
  'School of Education': [
    'Education, Society, and Human Development',
  ],
};
