/*
 * UC Santa Barbara — undergraduate college/major catalog.
 * Generated 2026-07-05 from the official UCSB Admissions majors list; do not hand-edit.
 * Verified against:
 *   https://admissions.ucsb.edu/majors
 * Note: Verbatim from the page's three college sections (L&S, COE, CCS); minors
 * and 5-year BS/MS program variants excluded; "for College of …" disambiguation
 * suffixes dropped (the college grouping already carries it). Art, Mathematics
 * and Physics appear in both L&S and CCS exactly as the page presents them.
 */

export const COLLEGE_MAJORS: Record<string, string[]> = {
  'College of Letters and Science': [
    'Actuarial Science',
    'Anthropology',
    'Applied Mathematics',
    'Aquatic Biology',
    'Art',
    'Asian American Studies',
    'Biochemistry',
    'Biological Sciences',
    'Biopsychology',
    'Black Studies',
    'Chemistry',
    'Chicano & Chicana Studies',
    'Chinese',
    'Classics',
    'Communication',
    'Comparative Literature',
    'Dance',
    'Earth Science',
    'East Asian Studies',
    'Ecology & Evolution',
    'Economics',
    'Economics & Accounting',
    'English',
    'Environmental Studies',
    'Feminist Studies',
    'Film & Media Studies',
    'Financial Mathematics & Statistics',
    'French',
    'Geography',
    'German',
    'Global Studies',
    'History',
    'History of Art & Architecture',
    'History of Policy, Law, & Governance',
    'Hydrologic Sciences & Policy',
    'Italian Studies',
    'Japanese',
    'Language, Culture & Society',
    'Latin American & Iberian Studies',
    'Linguistics',
    'Mathematics',
    'Medieval Studies',
    'Middle East Studies',
    'Molecular & Cellular Biology',
    'Music Performance/Music Studies',
    'Philosophy',
    'Physics',
    'Physiology',
    'Political Science',
    'Portuguese',
    'Psychological & Brain Sciences',
    'Religious Studies',
    'Russian & East European Studies',
    'Sociology',
    'Spanish',
    'Statistics & Data Science',
    'Theater',
    'Zoology',
  ],
  'Robert Mehrabian College of Engineering': [
    'Artificial Intelligence',
    'Chemical Engineering',
    'Computer Engineering',
    'Computer Science',
    'Electrical Engineering',
    'Mechanical Engineering',
  ],
  'College of Creative Studies': [
    'Art',
    'Biology',
    'Chemistry and Biochemistry',
    'Computing',
    'Marine Science',
    'Mathematics',
    'Music Composition',
    'Physics',
    'Writing and Literature',
  ],
};
