/*
 * UC San Diego — undergraduate school/major catalog.
 * Generated 2026-07-02 from the officially-verified majors dataset; do not hand-edit.
 * Verified against:
 *   https://admissions.ucsd.edu/why/majors/index.html
 *   https://catalog.ucsd.edu/undergraduate/degrees-offered/index.html (cross-check)
 * Note: Verbatim from the UCSD Admissions "Majors and Programs" page; BA/BS
 * duplicates merged; "Selective major" footnote markers and degree suffixes
 * stripped; section headings expanded to the official school names. UCSD's
 * residential colleges (Revelle, Muir, …) are not academic units and are not
 * used for grouping. "Joint Major Mathematics & Economics" is listed under both
 * Physical Sciences and Social Sciences exactly as the page presents it.
 */

export const COLLEGE_MAJORS: Record<string, string[]> = {
  'School of Arts and Humanities': [
    'Black Diaspora and African American Studies',
    'Chicanx and Latinx Studies',
    'Chinese Studies',
    'Cinematic Arts',
    'Classical Studies',
    'German Studies',
    'History',
    'Italian Studies',
    'Japanese Studies',
    'Jewish Studies',
    'Literary Arts',
    'Literature/Writing',
    'Literatures in English',
    'Literatures in Spanish',
    'World Literature and Culture',
    'Music',
    'Music/Humanities',
    'Interdisciplinary Computing and the Arts',
    'Philosophy',
    'Russian, East European, and Eurasian Studies',
    'Study of Religion',
    'Theatre',
    'Dance',
    'Global South Studies',
    'Visual Arts (Art History/Criticism)',
    'Visual Arts (Media)',
    'Visual Arts (Studio)',
    'Speculative Design',
  ],
  'School of Biological Sciences': [
    'Ecology, Behavior & Evolution',
    'General Biology',
    'Microbiology',
    'Biology with a Specialization in Bioinformatics',
    'Human Biology',
    'Molecular and Cell Biology',
    'Neurobiology',
  ],
  'Halıcıoğlu Data Science Institute': [
    'Data Science',
  ],
  'Jacobs School of Engineering': [
    'Bioengineering',
    'Bioengineering: Biotechnology',
    'Bioengineering: Bioinformatics',
    'Bioengineering: BioSystems',
    'Artificial Intelligence',
    'Computer Engineering',
    'Computer Science',
    'Computer Science with Specialization in Bioinformatics',
    'Electrical Engineering',
    'Engineering Physics',
    'Electrical Engineering & Society',
    'Aerospace Engineering',
    'Aerospace Engineering with Specialization in Aerothermodynamics',
    'Aerospace Engineering with Specialization in Astrodynamics and Space Applications',
    'Aerospace Engineering with Specialization in Flight Dynamics and Controls',
    'Mechanical Engineering',
    'Mechanical Engineering with a Specialization in Controls and Robotics',
    'Mechanical Engineering with a Specialization in Fluid Mechanics and Thermal Systems',
    'Mechanical Engineering with a Specialization in Materials Science and Engineering',
    'Mechanical Engineering with a Specialization in Mechanics of Materials',
    'Mechanical Engineering with a Specialization in Renewable Energy and Environmental Flows',
    'Chemical Engineering',
    'NanoEngineering',
    'Structural Engineering',
  ],
  'School of Physical Sciences': [
    'Astronomy & Astrophysics',
    'Chemistry',
    'Biochemistry',
    'Environmental Chemistry',
    'Pharmacological Chemistry',
    'Molecular Synthesis',
    'Applied Mathematics',
    'Mathematical Biology',
    'Mathematics',
    'Mathematics—Computer Science',
    'Mathematics—Applied Science',
    'Mathematics—Secondary Education',
    'Joint Major Mathematics & Economics',
    'Probability and Statistics',
    'Physics—Biophysics',
    'Physics with Specialization in Earth Sciences',
    'Physics',
    'General Physics',
    'General Physics/Secondary Education',
    'Physics with Specialization in Materials Physics',
    'Physics with Specialization in Computational Physics',
    'Physics with Specialization in Astrophysics',
  ],
  'Herbert Wertheim School of Public Health': [
    'Public Health',
    'Public Health with Concentration in Biostatistics',
    'Public Health with Concentration in Climate and Environmental Sciences',
    'Public Health with Concentration in Community Health Sciences',
    'Public Health with Concentration in Epidemiology',
    'Public Health with Concentration in Health Policy and Management Sciences',
    'Public Health with Concentration in Medicine Sciences',
  ],
  'Scripps Institution of Oceanography': [
    'Environmental Systems—Earth Sciences',
    'Environmental Systems—Ecology, Behavior and Evolution',
    'Environmental Systems—Environmental Chemistry',
    'Environmental Systems—Environmental Policy',
    'Geosciences',
    'Marine Biology',
    'Oceanic & Atmospheric Sciences',
  ],
  'School of Social Sciences': [
    'Anthropology with a Concentration in Biological Anthropology',
    'Anthropology with a Concentration in Climate Change and Human Solutions',
    'Anthropology with a Concentration in Archaeology',
    'Anthropology with a Concentration in Sociocultural Anthropology',
    'Biological Anthropology',
    'Environmental Anthropology',
    'Cognitive Science',
    'Cognitive Science with Specialization in Neuroscience',
    'Cognitive Science with Specialization in Clinical Aspects of Cognition',
    'Cognitive Science with Specialization in Design and Interaction',
    'Cognitive Science with Specialization in Language and Culture',
    'Cognitive Science with Specialization in Machine Learning and Neural Computation',
    'Cognitive and Behavioral Neuroscience',
    'Communication',
    'Media Industries and Communication',
    'Critical Gender Studies',
    'Business Economics',
    'Economics',
    'Joint Major Mathematics & Economics',
    'Education Sciences',
    'Ethnic Studies',
    'Global Health',
    'Human Developmental Sciences',
    'Human Developmental Sciences with a Specialization in Equity and Diversity',
    'Human Developmental Sciences with a Specialization in Healthy Aging',
    'International Studies—Anthropology',
    'International Studies—Economics',
    'International Studies—History',
    'International Studies—International Business',
    'International Studies—Linguistics',
    'International Studies—Literature',
    'International Studies—Philosophy',
    'International Studies—Political Science',
    'International Studies—Sociology',
    'Latin American Studies',
    'Latin American Studies with a Concentration in Mexico',
    'Latin American Studies with a Concentration in Migration and Border Studies',
    'Linguistics',
    'Linguistics - Language and Society',
    'Linguistics - Cognition and Language',
    'Linguistics - Language Studies',
    'Linguistics - Speech and Language Sciences',
    'Political Science - General Political Science',
    'Political Science - American Politics',
    'Political Science - Comparative Politics',
    'Political Science - Data Analytics',
    'Political Science - International Relations',
    'Political Science - Political Theory',
    'Political Science - Public Law',
    'Political Science - Public Policy',
    'Political Science - Race, Ethnicity, and Politics',
    'Psychology',
    'Psychology with a Specialization in Clinical Psychology',
    'Psychology with a Specialization in Cognitive Psychology',
    'Psychology with a Specialization in Developmental Psychology',
    'Psychology with a Specialization in Human Health',
    'Psychology with a Specialization in Sensation and Perception',
    'Psychology with a Specialization in Social Psychology',
    'Business Psychology',
    'Sociology',
    'Sociology - American Studies',
    'Sociology - Culture and Communication',
    'Sociology - Economy and Society',
    'Sociology - International Studies',
    'Sociology - Law and Society',
    'Sociology - Science and Medicine',
    'Sociology - Social Inequalities',
    'Urban Studies and Planning',
    'Real Estate and Development',
  ],
};
