/*
 * Georgia — undergraduate college/major catalog.
 * Franklin College carries the arts-and-sciences core; land-grant (CAES,
 * Warnell, FACS) and professional colleges included.
 */

export const COLLEGE_MAJORS: Record<string, string[]> = {
  'Franklin College of Arts and Sciences': [
    'Computer Science',
    'Chemistry',
    'Physics',
    'Astrophysics',
    'Mathematics',
    'Statistics',
    'Biology',
    'Biochemistry and Molecular Biology',
    'Cellular Biology',
    'Genetics',
    'Microbiology',
    'Plant Biology',
    'Marine Sciences',
    'Geology',
    'Geography',
    'Psychology',
    'Cognitive Science',
    'Anthropology',
    'Sociology',
    'Criminal Justice',
    'History',
    'English',
    'Philosophy',
    'Religion',
    'Classics',
    'Comparative Literature',
    'Spanish',
    'French',
    'German',
    'Russian',
    'Linguistics',
    'Communication Studies',
    'Theatre',
    'Film Studies',
    'Music',
    'Studio Art',
    'Art History',
    'Dance',
    'African American Studies',
    "Women's Studies",
  ],
  'College of Engineering': [
    'Computer Systems Engineering',
    'Electrical and Electronics Engineering',
    'Mechanical Engineering',
    'Civil Engineering',
    'Environmental Engineering',
    'Agricultural Engineering',
    'Biological Engineering',
    'Biochemical Engineering',
    'Chemical Engineering',
  ],
  'Terry College of Business': [
    'Accounting',
    'Economics',
    'Finance',
    'Risk Management and Insurance',
    'Real Estate',
    'Management',
    'Management Information Systems',
    'Marketing',
    'International Business',
  ],
  'Grady College of Journalism and Mass Communication': [
    'Journalism',
    'Advertising',
    'Public Relations',
    'Entertainment and Media Studies',
  ],
  'College of Agricultural and Environmental Sciences': [
    'Agribusiness',
    'Agricultural and Applied Economics',
    'Agricultural Communication',
    'Agricultural Education',
    'Animal Science',
    'Avian Biology',
    'Crop and Soil Sciences',
    'Entomology',
    'Environmental Economics and Management',
    'Food Science',
    'Horticulture',
    'Poultry Science',
  ],
  'Warnell School of Forestry and Natural Resources': [
    'Forestry',
    'Fisheries and Wildlife',
    'Natural Resource Management and Sustainability',
  ],
  'College of Family and Consumer Sciences': [
    'Financial Planning',
    'Consumer Economics',
    'Fashion Merchandising',
    'Human Development and Family Science',
    'Nutritional Sciences',
    'Dietetics',
  ],
  'Mary Frances Early College of Education': [
    'Elementary Education',
    'Middle Grades Education',
    'Special Education',
    'Communication Sciences and Disorders',
    'Kinesiology',
    'Health and Physical Education',
  ],
  'College of Public Health': [
    'Environmental Health',
    'Health Promotion',
  ],
  'School of Public and International Affairs': [
    'Political Science',
    'International Affairs',
  ],
  'Odum School of Ecology': [
    'Ecology',
  ],
  'College of Environment and Design': [
    'Landscape Architecture',
  ],
  'College of Pharmacy': [
    'Pharmaceutical Sciences',
  ],
  'School of Social Work': [
    'Social Work',
  ],
};
