/*
 * University of Georgia — undergraduate college/major catalog.
 * Generated from live recon; majors are official undergraduate programs.
 */

export const COLLEGE_MAJORS: Record<string, string[]> = {
  'Franklin College of Arts and Sciences': [
    'Computer Science',
    'Physics',
    'Astronomy',
    'Chemistry',
    'Mathematics',
    'Statistics',
    'Genetics',
    'Biology',
    'Plant Biology',
    'Cellular Biology',
    'Microbiology',
    'Marine Sciences',
    'Geography',
    'Geology',
    'Psychology',
    'English',
    'Creative Writing',
    'History',
    'Philosophy',
    'Classics',
    'Religion',
    'Linguistics',
    'Sociology',
    'Anthropology',
    'Music',
    'Theatre',
    'Film Studies',
    'Communication Studies',
    'African American Studies',
  ],
  'College of Engineering': [
    'Computer Systems Engineering',
    'Electrical and Electronics Engineering',
    'Mechanical Engineering',
    'Civil Engineering',
    'Environmental Engineering',
    'Agricultural Engineering',
    'Biological Engineering',
    'Biochemical Engineering',
  ],
  'Terry College of Business': [
    'Accounting',
    'Finance',
    'Marketing',
    'Management',
    'Management Information Systems',
    'Economics',
    'International Business',
  ],
  'Warnell School of Forestry and Natural Resources': [
    'Forestry',
    'Wildlife Sciences',
    'Fisheries and Aquatic Sciences',
    'Natural Resource Management',
  ],
  'Grady College of Journalism and Mass Communication': [
    'Journalism',
    'Advertising',
    'Public Relations',
    'Entertainment and Media Studies',
  ],
  'College of Agricultural and Environmental Sciences': [
    'Agricultural Sciences',
    'Animal Science',
    'Food Science',
    'Horticulture',
    'Entomology',
    'Plant Sciences',
  ],
};
