/*
 * UMass Amherst — undergraduate college/major catalog.
 * CICS + Riccio engineering + the campus colleges on the shared Drupal.
 */

export const COLLEGE_MAJORS: Record<string, string[]> = {
  'Manning College of Information & Computer Sciences': [
    'Computer Science',
    'Informatics',
    'Data Science',
  ],
  'Riccio College of Engineering': [
    'Biomedical Engineering',
    'Chemical Engineering',
    'Civil Engineering',
    'Electrical Engineering',
    'Computer Engineering',
    'Mechanical Engineering',
    'Industrial Engineering',
    'Environmental Engineering',
  ],
  'College of Natural Sciences': [
    'Physics',
    'Astronomy',
    'Chemistry',
    'Biology',
    'Biochemistry & Molecular Biology',
    'Microbiology',
    'Mathematics',
    'Statistics',
    'Food Science',
    'Environmental Science',
    'Geology',
    'Geography',
    'Psychology',
    'Neuroscience',
    'Animal Science',
    'Sustainable Food & Farming',
    'Building & Construction Technology',
  ],
  'College of Social & Behavioral Sciences': [
    'Economics',
    'Sociology',
    'Political Science',
    'Communication',
    'Anthropology',
    'Linguistics',
    'Resource Economics',
    'Journalism',
    'Public Policy',
    'Landscape Architecture',
    'Legal Studies',
  ],
  'College of Humanities & Fine Arts': [
    'History',
    'English',
    'Philosophy',
    'Classics',
    'Comparative Literature',
    'Studio Art',
    'Art History',
    'Theater',
    'Architecture',
    'Music',
    'Dance',
    'Afro-American Studies',
    'Women/Gender/Sexuality Studies',
    'Spanish & Portuguese Studies',
    'French & Francophone Studies',
  ],
  'Isenberg School of Management': [
    'Accounting',
    'Finance',
    'Management',
    'Marketing',
    'Operations & Information Management',
    'Hospitality & Tourism Management',
    'Sport Management',
  ],
  'College of Education': [
    'Education',
    'Early Childhood Education',
    'Elementary Education',
    'Secondary Education',
    'Special Education',
  ],
  'Elaine Marieb College of Nursing': [
    'Nursing',
  ],
  'School of Public Health & Health Sciences': [
    'Public Health Sciences',
    'Kinesiology',
    'Nutrition',
    'Communication Disorders',
    'Biostatistics',
    'Epidemiology',
    'Environmental Health Sciences',
  ],
  'Stockbridge School of Agriculture': [
    'Sustainable Food & Farming',
    'Horticultural Science',
    'Turfgrass Science & Management',
    'Plant & Soil Sciences',
    'Arboriculture & Urban Forestry',
  ],
};
