/*
 * University of Michigan — undergraduate college/major catalog.
 * Generated 2026-06-12 from the officially-verified research dataset; do not hand-edit.
 * Verified against:
 *   http://web.archive.org/web/20260529103657/https://admissions.umich.edu/academics-majors/majors-degrees
 * Note: From a 2026-05-29 Wayback snapshot of the official admissions Majors & Degrees page (live umich.edu 403s behind Cloudflare); sub-majors and certificates excluded; cross-listed majors (CS, Data Science, Interarts Performance, IBE) genuinely appear under two units.
 */

export const COLLEGE_MAJORS: Record<string, string[]> = {
  'College of Literature, Science, and the Arts (LSA)': [
    'Afroamerican and African Studies',
    'American Culture',
    'Anthropology',
    'Archaeology of the Ancient Mediterranean',
    'Arts and Ideas in the Humanities',
    'Asian Studies',
    'Astronomy and Astrophysics',
    'Biochemistry',
    'Biology',
    'Biology, Health, and Society',
    'Biomolecular Science',
    'Biophysics',
    'Biopsychology, Cognition, and Neuroscience',
    'Cellular and Molecular Biomedical Science',
    'Chemistry',
    'Classical Civilization',
    'Classical Languages and Literatures',
    'Cognitive Science',
    'Communication and Media',
    'Comparative Literature, Arts, and Media',
    'Computer Science',
    'Creative Writing and Literature',
    'Data Science',
    'Drama',
    'Earth and Environmental Sciences',
    'Ecology, Evolution, and Biodiversity',
    'Economics',
    'English',
    'Environment',
    'Film, Television, and Media',
    'French and Francophone Studies',
    'Gender and Health',
    'General Studies',
    'German',
    'Greek (Ancient) Language and Literature',
    'Greek (Modern) Language and Culture',
    'History',
    'History of Art',
    'Human Origins, Biology, and Behavior',
    'Interdisciplinary Astronomy',
    'Interdisciplinary Chemical Sciences',
    'Interdisciplinary Physics',
    'International Studies',
    'Italian',
    'Judaic Studies',
    'Latin American and Caribbean Studies',
    'Latin Language and Literature',
    'Latina/Latino Studies',
    'Linguistics',
    'Mathematics',
    'Microbiology',
    'Middle East Studies',
    'Middle Eastern and North African Studies',
    'Molecular, Cellular, and Developmental Biology',
    'Neuroscience',
    'Organizational Studies',
    'Philosophy',
    'Philosophy, Politics, and Economics',
    'Physics',
    'Plant Biology',
    'Polish',
    'Political Science',
    'Psychology',
    'Romance Languages and Literatures',
    'Russian',
    'Russian, East European, and Eurasian Studies',
    'Social Theory and Practice',
    'Sociology',
    'Spanish',
    'Statistics',
    'Translation',
    'Women\'s and Gender Studies',
  ],
  'College of Engineering': [
    'Aerospace Engineering',
    'Biomedical Engineering',
    'Chemical Engineering',
    'Civil Engineering',
    'Climate and Meteorology',
    'Computer Engineering',
    'Computer Science',
    'Data Science',
    'Electrical Engineering',
    'Engineering Physics',
    'Environmental Engineering',
    'Industrial and Operations Engineering',
    'Integrated Business and Engineering at Michigan',
    'Materials Science and Engineering',
    'Mechanical Engineering',
    'Naval Architecture and Marine Engineering',
    'Nuclear Engineering and Radiological Sciences',
    'Robotics',
    'Space Sciences and Engineering',
  ],
  'Ross School of Business': [
    'Business',
    'Integrated Business and Engineering at Michigan',
  ],
  'School of Music, Theatre & Dance (SMTD)': [
    'Composition',
    'Dance',
    'Interarts Performance',
    'Jazz & Contemporary Improvisation',
    'Music',
    'Music Education',
    'Music Theory',
    'Musical Theatre',
    'Musicology',
    'Organ',
    'Performing Arts Technology',
    'Piano',
    'Strings',
    'Theatre & Drama',
    'Voice & Opera',
    'Winds & Percussion',
  ],
  'Stamps School of Art & Design': [
    'Art and Design',
    'Interarts Performance',
  ],
  'Taubman College of Architecture & Urban Planning': [
    'Architecture',
    'Urban Technology',
  ],
  'School of Kinesiology': [
    'Applied Exercise Science',
    'Movement Science',
    'Sport Management',
  ],
  'Marsal Family School of Education': [
    'Elementary Teacher Education',
    'Learning, Equity, and Problem Solving for the Public Good (LEAPS)',
    'Secondary Teacher Education',
  ],
  'School of Information': [
    'Information Analysis and Design',
    'User Experience Design',
  ],
  'School of Public Health': [
    'Community and Global Public Health',
    'Public Health Sciences',
  ],
  'College of Pharmacy': [
    'Pharmaceutical Sciences',
  ],
  'School of Dentistry': [
    'Dental Hygiene',
  ],
  'School of Nursing': [
    'Nursing',
  ],
  'Ford School of Public Policy': [
    'Public Policy',
  ],
};
