/*
 * Minnesota — undergraduate college/major catalog.
 * CSE carries the STEM majors; land-grant colleges (CFANS, CBS) and Carlson round it out.
 */

export const COLLEGE_MAJORS: Record<string, string[]> = {
  'College of Science & Engineering (CSE)': [
    'Computer Science',
    'Electrical Engineering',
    'Mechanical Engineering',
    'Biomedical Engineering',
    'Chemical Engineering',
    'Aerospace Engineering & Mechanics',
    'Chemistry',
    'Physics',
    'Mathematics',
    'Civil Engineering',
    'Materials Science & Engineering',
    'Data Science',
  ],
  'College of Liberal Arts (CLA)': [
    'Psychology',
    'Economics',
    'Political Science',
    'Sociology',
    'English',
    'History',
    'Statistics',
    'Linguistics',
    'Philosophy',
    'Journalism & Mass Communication',
    'Geography',
    'Anthropology',
  ],
  'College of Biological Sciences (CBS)': [
    'Biology',
    'Biochemistry',
    'Genetics, Cell Biology & Development',
    'Ecology, Evolution & Behavior',
    'Plant Biology',
    'Neuroscience',
    'Microbiology',
  ],
  'College of Food, Agricultural & Natural Resource Sciences (CFANS)': [
    'Food Science',
    'Animal Science',
    'Agronomy & Plant Genetics',
    'Forest & Natural Resource Management',
    'Horticulture',
    'Fisheries & Wildlife',
    'Environmental Sciences',
    'Bioproducts & Biosystems Engineering',
    'Nutrition',
    'Applied Economics',
  ],
  'Carlson School of Management (CSOM)': [
    'Accounting',
    'Finance',
    'Marketing',
    'Supply Chain & Operations Management',
    'Information Systems',
    'Entrepreneurial Management',
    'Human Resources & Industrial Relations',
  ],
  'College of Education & Human Development (CEHD)': [
    'Elementary Education',
    'Child Psychology',
    'Family Social Science',
    'Kinesiology',
    'Special Education',
    'Youth Studies',
  ],
  'College of Design (CDes)': [
    'Architecture',
    'Landscape Architecture',
    'Graphic Design',
    'Apparel Design',
    'Interior Design',
    'Product Design',
    'Retail Merchandising',
    'Housing Studies',
  ],
  'School of Nursing': [
    'Nursing',
  ],
  'College of Continuing & Professional Studies (CCAPS)': [
    'Health Services Management',
    'Information Technology Infrastructure',
    'Construction Management',
    'Multidisciplinary Studies',
  ],
};
