/*
 * University of Pennsylvania — undergraduate college/major catalog.
 * The four undergraduate schools and their majors; reuses existing i18n
 * labels where possible. Faculty coverage spans all twelve Penn schools;
 * the catalog reflects what undergraduates can study.
 */

export const COLLEGE_MAJORS: Record<string, string[]> = {
  'College of Arts and Sciences': [
    'Africana Studies',
    'Anthropology',
    'Art History',
    'Biochemistry',
    'Biology',
    'Biophysics',
    'Chemistry',
    'Cinema & Media Studies',
    'Classical Studies',
    'Cognitive Science',
    'Communication',
    'Comparative Literature',
    'Criminology',
    'Earth Science',
    'East Asian Studies',
    'Economics',
    'English',
    'Environmental Studies',
    'Fine Arts',
    'French',
    'German',
    'Health & Societies',
    'History',
    'History & Sociology of Science',
    'International Relations',
    'Italian',
    'Linguistics',
    'Mathematics',
    'Middle Eastern Studies',
    'Music',
    'Neuroscience',
    'Philosophy',
    'Physics',
    'Political Science',
    'Psychology',
    'Religious Studies',
    'Russian',
    'Sociology',
    'South Asia Studies',
    'Spanish',
    'Theatre Arts',
    'Urban Studies',
  ],
  'School of Engineering and Applied Science': [
    'Artificial Intelligence',
    'Bioengineering',
    'Chemical & Biomolecular Engineering',
    'Computer Engineering',
    'Computer Science',
    'Digital Media Design',
    'Electrical Engineering',
    'Materials Science & Engineering',
    'Mechanical Engineering',
    'Networked & Social Systems Engineering',
    'Systems Science & Engineering',
  ],
  'The Wharton School': [
    'Accounting',
    'Business Analytics',
    'Business Economics & Public Policy',
    'Entrepreneurship & Innovation',
    'Finance',
    'Health Care Management & Policy',
    'Legal Studies & Business Ethics',
    'Management',
    'Marketing',
    'Operations, Information & Decisions',
    'Real Estate',
    'Statistics',
  ],
  'School of Nursing': ['Nursing'],
};
