/*
 * University of Washington — undergraduate college/major catalog.
 * Generated 2026-06-12 from the officially-verified research dataset; do not hand-edit.
 * Verified against:
 *   https://advising.uw.edu/degree-overview/majors/list-of-undergraduate-majors/
 *   https://admit.washington.edu/apply/majors/
 * Note: Verbatim from the UAA advising List of Undergraduate Majors with the admissions majors list as cross-check; legacy duplicate Computer Science line under Arts & Sciences deduplicated; options/concentrations folded into parent majors; B.M. performance majors are distinct per the official list.
 */

export const COLLEGE_MAJORS: Record<string, string[]> = {
  'College of Arts and Sciences': [
    'American Ethnic Studies',
    'American Indian Studies',
    'Anthropology',
    'Applied and Computational Mathematical Sciences',
    'Applied Mathematics',
    'Art',
    'Art History',
    'Asian Languages and Cultures',
    'Asian Studies',
    'Astronomy',
    'Biochemistry',
    'Biology',
    'Chemistry',
    'Chinese',
    'Cinema & Media Studies',
    'Classical Studies',
    'Classics',
    'Communication',
    'Comparative History of Ideas',
    'Comparative Religion',
    'Composition (Music)',
    'Computational Finance and Risk Management',
    'Dance',
    'Danish',
    'Design',
    'Drama',
    'Economics',
    'English',
    'Ethnomusicology',
    'European Studies',
    'Finnish',
    'French',
    'Gender, Women, and Sexuality Studies',
    'Geography',
    'German Studies',
    'Global Literary Studies',
    'Greek',
    'Guitar',
    'History',
    'History and Philosophy of Science',
    'Individualized Studies',
    'Integrated Social Sciences',
    'International Studies',
    'Japanese',
    'Jazz Studies',
    'Jewish Studies',
    'Korean',
    'Latin',
    'Latin American and Caribbean Studies',
    'Law, Societies, and Justice',
    'Linguistics',
    'Mathematics',
    'Microbiology',
    'Middle Eastern Languages and Cultures',
    'Music',
    'Music Education',
    'Neuroscience',
    'Norwegian',
    'Orchestral Instruments',
    'Organ (Music)',
    'Percussion',
    'Philosophy',
    'Physics',
    'Piano',
    'Political Science',
    'Psychology',
    'Scandinavian Studies',
    'Slavic Languages and Literatures',
    'Sociology',
    'South Asian Languages and Literature',
    'Spanish',
    'Speech and Hearing Sciences',
    'Statistics',
    'Swedish',
    'Voice (Music)',
  ],
  'College of Built Environments': [
    'Architectural Design',
    'Architecture',
    'Community, Environment, and Planning',
    'Construction Management',
    'Environmental Design and Sustainability',
    'Landscape Architecture',
    'Real Estate',
  ],
  'College of Education': [
    'Early Care and Education',
    'Early Childhood and Family Studies',
    'Education Studies',
    'Education, Communities, and Organizations',
  ],
  'College of Engineering': [
    'Aeronautics and Astronautics',
    'Bioengineering',
    'Chemical Engineering',
    'Civil Engineering',
    'Computer Engineering',
    'Computer Science',
    'Electrical and Computer Engineering',
    'Environmental Engineering',
    'Human Centered Design and Engineering',
    'Industrial Engineering',
    'Materials Science and Engineering',
    'Mechanical Engineering',
  ],
  'College of the Environment': [
    'Aquatic Conservation & Ecology',
    'Atmospheric Sciences',
    'Earth and Space Sciences',
    'Environmental Science and Terrestrial Resource Management',
    'Environmental Studies',
    'Marine Biology',
    'Oceanography',
    'Sustainable Bioresource Systems Engineering',
  ],
  'Daniel J. Evans School of Public Policy & Governance': [
    'Public Service and Policy',
  ],
  'Information School': [
    'Informatics',
  ],
  'Michael G. Foster School of Business': [
    'Business Administration',
  ],
  'School of Medicine': [
    'Medical Laboratory Science',
  ],
  'School of Nursing': [
    'Nursing',
  ],
  'School of Public Health': [
    'Environmental Public Health',
    'Food Systems, Nutrition, and Health',
    'Health Informatics and Health Information Management',
    'Public Health - Global Health',
  ],
  'School of Social Work': [
    'Social Welfare',
  ],
};
