/*
 * Virginia Tech — undergraduate college/major catalog.
 * Engineering + Science lead; land-grant colleges included.
 */

export const COLLEGE_MAJORS: Record<string, string[]> = {
  'College of Engineering': [
    'Computer Science',
    'Electrical Engineering',
    'Computer Engineering',
    'Mechanical Engineering',
    'Aerospace Engineering',
    'Chemical Engineering',
    'Civil Engineering',
    'Industrial and Systems Engineering',
    'Materials Science and Engineering',
    'Mining Engineering',
    'Biological Systems Engineering',
  ],
  'College of Science': [
    'Physics',
    'Chemistry',
    'Mathematics',
    'Statistics',
    'Biological Sciences',
    'Psychology',
    'Economics',
    'Neuroscience',
    'Geosciences',
    'Computational Modeling and Data Analytics',
    'Nanoscience',
  ],
  'College of Agriculture and Life Sciences': [
    'Animal and Poultry Sciences',
    'Biochemistry',
    'Food Science and Technology',
    'Human Nutrition, Foods, and Exercise',
    'Agribusiness',
    'Environmental Science',
    'Plant Science',
    'Landscape Horticulture and Design',
  ],
  'College of Natural Resources and Environment': [
    'Wildlife Conservation',
    'Fish Conservation',
    'Forestry',
    'Sustainable Biomaterials',
    'Packaging Systems and Design',
    'Geography',
    'Meteorology',
    'Environmental Resources Management',
  ],
  'Pamplin College of Business': [
    'Accounting and Information Systems',
    'Business Information Technology',
    'Finance',
    'Management',
    'Marketing',
    'Hospitality and Tourism Management',
    'Real Estate',
  ],
  'College of Liberal Arts and Human Sciences': [
    'English',
    'History',
    'Political Science',
    'Sociology',
    'Communication',
    'Human Development and Family Science',
    'Criminology',
    'National Security and Foreign Affairs',
  ],
  'College of Architecture, Arts, and Design': [
    'Architecture',
    'Industrial Design',
    'Interior Design',
    'Landscape Architecture',
    'Building Construction',
    'Art',
    'Music',
    'Theatre',
  ],
};
