/*
 * UW-Madison — undergraduate college/major catalog.
 * Generated 2026-06-12 from the officially-verified research dataset; do not hand-edit.
 * Verified against:
 *   https://guide.wisc.edu/undergraduate/
 *   https://guide.wisc.edu/undergraduate/letters-science/
 *   https://guide.wisc.edu/undergraduate/agricultural-life-sciences/
 *   https://guide.wisc.edu/undergraduate/engineering/
 *   https://guide.wisc.edu/undergraduate/business/
 *   https://guide.wisc.edu/undergraduate/education/
 *   https://guide.wisc.edu/undergraduate/human-ecology/
 *   https://guide.wisc.edu/undergraduate/nursing/
 *   https://guide.wisc.edu/undergraduate/pharmacy/
 * Note: Extracted verbatim from each school/college's Degrees/Majors list in the official Guide; certificates and 'Individual Major' options excluded; BA/BS/BFA duplicates merged; majors offered through both CALS and L&S listed once under CALS.
 */

export const COLLEGE_MAJORS: Record<string, string[]> = {
  'College of Letters & Science': [
    'African American Studies',
    'African Cultural Studies',
    'Anthropology',
    'Applied Mathematics, Engineering, and Physics',
    'Applied Social Science',
    'Art History',
    'Asian Languages and Cultures',
    'Astronomy-Physics',
    'Atmospheric and Oceanic Sciences',
    'Botany',
    'Cartography and Geographic Information Systems',
    'Chemistry',
    'Chicanx/e and Latinx/e Studies',
    'Chinese',
    'Classical Humanities',
    'Classics',
    'Communication Arts',
    'Communication Sciences and Disorders',
    'Computer Sciences',
    'Conservation Biology',
    'Data Science',
    'Economics',
    'English',
    'Environmental Studies',
    'French',
    'Gender and Women\'s Studies',
    'Geography',
    'Geology and Geophysics',
    'German',
    'History',
    'Information Science',
    'International Studies',
    'Italian',
    'Japanese',
    'Jewish Studies',
    'Journalism',
    'Korean Language and Culture',
    'Landscape Architecture',
    'Landscape and Urban Studies',
    'Latin',
    'Latin American, Caribbean, and Iberian Studies',
    'Legal Studies',
    'Linguistics',
    'Mathematics',
    'Molecular and Cell Biology',
    'Music',
    'Music: Education',
    'Music: Performance',
    'Neurobiology',
    'Philosophy',
    'Physics',
    'Polish',
    'Political Science',
    'Portuguese',
    'Psychology',
    'Public Policy',
    'Religious Studies',
    'Russian',
    'Scandinavian Studies',
    'Social Welfare',
    'Social Work',
    'Sociology',
    'Spanish',
    'Statistics',
    'Zoology',
  ],
  'College of Agricultural and Life Sciences': [
    'Agricultural Business Management',
    'Agricultural and Applied Economics',
    'Agroecology',
    'Agronomy',
    'Animal Sciences',
    'Animal and Veterinary Biosciences',
    'Biochemistry',
    'Biological Systems Engineering',
    'Biology',
    'Community and Environmental Sociology',
    'Dairy Science',
    'Dairy and Food Animal Management',
    'Entomology',
    'Environmental Sciences',
    'Food Science',
    'Forest Science',
    'Genetics and Genomics',
    'Global Health',
    'Horticulture',
    'Life Sciences Communication',
    'Microbiology',
    'Nutritional Sciences',
    'Plant Pathology',
    'Plant Science and Technology',
    'Soil Science',
    'Wildlife Ecology',
  ],
  'College of Engineering': [
    'Aerospace Engineering',
    'Biomedical Engineering',
    'Chemical Engineering',
    'Civil Engineering',
    'Computer Engineering',
    'Electrical Engineering',
    'Engineering Mechanics',
    'Engineering Physics',
    'Environmental Engineering',
    'Geological Engineering',
    'Industrial Engineering',
    'Materials Science and Engineering',
    'Mechanical Engineering',
    'Naval Science',
    'Nuclear Engineering',
  ],
  'School of Business': [
    'Business Administration: Human Resources',
    'Business Administration: Management',
    'Business Administration: Marketing',
    'Business: Accounting',
    'Business: Actuarial Science',
    'Business: Entrepreneurship',
    'Business: Finance, Investment, and Banking',
    'Business: Human Resource Management',
    'Business: Information Systems',
    'Business: International Business',
    'Business: Management',
    'Business: Management and Human Resources',
    'Business: Marketing',
    'Business: Operations and Technology Management',
    'Business: Real Estate and Urban Land Economics',
    'Business: Risk Management and Insurance',
    'Business: Supply Chain Management',
  ],
  'School of Education': [
    'Art',
    'Art Education',
    'Dance',
    'Educational Policy Studies',
    'Elementary Education',
    'Elementary Education and Special Education',
    'Health Promotion and Health Equity',
    'Kinesiology',
    'Physical Education',
    'Rehabilitation Psychology',
    'Special Education',
    'Theatre and Drama',
  ],
  'School of Human Ecology': [
    'Community and Organizational Development',
    'Consumer Behavior and Marketplace Studies',
    'Consumer Finance and Financial Planning',
    'Consumer Marketplace Studies',
    'Design, Innovation, and Society',
    'Human Development and Family Studies',
    'Interior Architecture',
    'Personal Finance',
    'Textiles and Fashion Design',
  ],
  'School of Nursing': [
    'Nursing',
  ],
  'School of Pharmacy': [
    'Pharmacology and Toxicology',
  ],
};
