/*
 * Yale University — undergraduate college/major catalog.
 * Yale College's four curricular divisions (majors are Yale College AB/BS
 * programs, not graduate-only degrees); engineering majors sit in SEAS.
 * Reuses existing i18n labels where possible.
 */

export const COLLEGE_MAJORS: Record<string, string[]> = {
  'Arts and Humanities': [
    'African American Studies',
    'American Studies',
    'Archaeological Studies',
    'Architecture',
    'Art',
    'Classics',
    'Comparative Literature',
    'East Asian Languages and Literatures',
    'English',
    'Film and Media Studies',
    'French',
    'German Studies',
    'History of Art',
    'Humanities',
    'Italian Studies',
    'Jewish Studies',
    'Linguistics',
    'Music',
    'Near Eastern Languages and Civilizations',
    'Philosophy',
    'Religious Studies',
    'Russian',
    'Spanish',
    'Portuguese',
    'Theater, Dance and Performance Studies',
  ],
  'Social Sciences': [
    'Anthropology',
    'Economics',
    'Ethics, Politics and Economics',
    'Ethnicity, Race and Migration',
    'Global Affairs',
    'History',
    'History of Science, Medicine and Public Health',
    'Political Science',
    'Psychology',
    'Sociology',
    "Women's, Gender and Sexuality Studies",
    'Urban Studies',
  ],
  'Sciences': [
    'Astronomy',
    'Astrophysics',
    'Chemistry',
    'Earth and Planetary Sciences',
    'Ecology and Evolutionary Biology',
    'Molecular Biophysics and Biochemistry',
    'Molecular, Cellular and Developmental Biology',
    'Neuroscience',
    'Physics',
    'Mathematics',
    'Statistics and Data Science',
    'Cognitive Science',
    'Environmental Studies',
  ],
  'School of Engineering and Applied Science': [
    'Applied Mathematics',
    'Applied Physics',
    'Biomedical Engineering',
    'Chemical Engineering',
    'Computer Science',
    'Computer Science and Economics',
    'Computer Science and Mathematics',
    'Computer Science and Psychology',
    'Electrical Engineering',
    'Electrical Engineering and Computer Science',
    'Environmental Engineering',
    'Mechanical Engineering',
  ],
};
