import { act, fireEvent, render, screen, waitFor, within } from '@testing-library/react';
import { webcrypto } from 'node:crypto';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { useState } from 'react';
import { DEFAULT_PROFILE } from '@/app/home/types';
import { createEmptyResumeMaster } from '@/lib/resume-master';
import { createTargetResume, type TargetResumeV1 } from '@/lib/target-resume';
import type { ResumeFact } from '@/lib/types';
import type { TargetResumeSupportGroup } from '@/lib/target-resume-support';
import type { useResumeSupplement } from './use-resume-supplement';
import ResumeExperienceAssignmentPanel from './ResumeExperienceAssignmentPanel';
import TargetResumeSupportPanel from './TargetResumeSupportPanel';
const mocked=vi.hoisted(()=>({controller:null as unknown,locale:'en'}));
vi.mock('@/i18n/client',()=>({useLocale:()=>mocked.locale}));
vi.mock('./use-resume-supplement',()=>({useResumeSupplement:()=>mocked.controller}));
type Controller=ReturnType<typeof useResumeSupplement>;
const fact=(id:string,value:string):ResumeFact=>({id,value,revision:1,status:'confirmed',source:{kind:'manual'}});
function setup(){const master=createEmptyResumeMaster('master');master.activities=[{id:'activity',kind:'project',title:fact('title','Current project'),details:[{id:'old',revision:1},{id:'support',revision:1}]},{id:'other',kind:'research',title:{...fact('other-title','UNCONFIRMED OLD TITLE'),status:'candidate'},details:[]}];const profile={...DEFAULT_PROFILE,research_interests:'Perception interests are not acquired skills.',resume_master:master,experience_entries:[{id:'old',revision:1,status:'confirmed' as const,text:'Full original: I did not lead the project.',source:{kind:'manual' as const}},{id:'support',revision:1,status:'confirmed' as const,text:'My individual contribution was writing Python tests.',source:{kind:'manual' as const}},{id:'unbound',revision:1,status:'confirmed' as const,text:'Complete unbound original 王.',source:{kind:'manual' as const}}]};const token={uid:'owner',epoch:1,generation:0};const view={viewId:'view1',revision:1,token,baseProfile:profile,renderedProfile:profile,identityGeneration:1,source:'hydration' as const};const controller:Controller={view,acceptedView:view,phase:'ready',error:null,ownerScopeKey:'owner',operationLocked:false,confirmedEntryId:null,acceptCurrent:vi.fn(),assign:vi.fn().mockResolvedValue({durable:false,reason:'record-failed'}),confirm:vi.fn(),retryRecorded:vi.fn(),baseline:vi.fn(activityId=>({view,activityId,targetKey:'target'}))};mocked.controller=controller;return {profile,controller};}
beforeEach(()=>{vi.stubGlobal('crypto',webcrypto);mocked.locale='en';});afterEach(()=>vi.unstubAllGlobals());
describe('assignment review',()=>{
 it('shows full originals and only current confirmed activity labels before explicit confirmation',async()=>{const {controller}=setup();render(<ResumeExperienceAssignmentPanel targetKey="target"/>);await screen.findByText('Complete unbound original 王.');expect(screen.queryByText('UNCONFIRMED OLD TITLE')).not.toBeInTheDocument();expect(screen.getByRole('option',{name:'Activity 2 — review its name'})).toBeInTheDocument();fireEvent.click(screen.getByRole('radio'));fireEvent.change(screen.getByRole('combobox'),{target:{value:'activity'}});expect(screen.getByText('Full original: I did not lead the project.')).toBeVisible();expect(screen.getByRole('button',{name:'Save assignment'})).toBeDisabled();fireEvent.click(screen.getByRole('checkbox'));fireEvent.click(screen.getByRole('button',{name:'Save assignment'}));await waitFor(()=>expect(controller.assign).toHaveBeenCalledWith({entryId:'unbound',entryRevision:1,activityId:'activity'},expect.objectContaining({view:controller.view})));expect(screen.getByRole('radio')).toBeChecked();});
 it('new accepted view clears confirmation while preserving choices and failed-save text',async()=>{const {controller}=setup();const {rerender}=render(<ResumeExperienceAssignmentPanel targetKey="target"/>);await screen.findByText('Complete unbound original 王.');fireEvent.click(screen.getByRole('radio'));fireEvent.change(screen.getByRole('combobox'),{target:{value:'activity'}});fireEvent.click(screen.getByRole('checkbox'));mocked.controller={...controller,phase:'save-error'};rerender(<ResumeExperienceAssignmentPanel targetKey="target"/>);expect(screen.getByRole('radio')).toBeChecked();expect(screen.getByRole('alert')).toHaveTextContent('not saved');mocked.controller={...controller,view:{...controller.view!,viewId:'view2'}};rerender(<ResumeExperienceAssignmentPanel targetKey="target"/>);await screen.findByText('Complete unbound original 王.');expect(screen.getByRole('checkbox')).not.toBeChecked();expect(screen.getByRole('combobox')).toHaveValue('activity');expect(controller.assign).not.toHaveBeenCalled();});
});
describe('support source review',()=>{
 async function mount(){const {profile}=setup();const draft=await createTargetResume(profile,{opportunity_id:'opp',title:'Lab',organization:'University',source_url:'',description:'Python',requirements:['Python'],context_version:4,lab:{version:1,status:'unavailable',snapshot:null},research:{version:1,status:'unavailable',snapshot:null},criteria:{eligibility:{},timing:{},application:{},setting:{},availability:{},attribution:{}}},'draft');const changed=vi.fn();function Host({current=draft}:{current?:TargetResumeV1}){const [groups,setGroups]=useState<TargetResumeSupportGroup[]>([]);return <TargetResumeSupportPanel draft={current} groups={groups} enabled onChange={value=>{changed(value);setGroups(value);}}/>;}render(<Host/>);fireEvent.click(screen.getByText('Choose supporting details'));return {draft,changed};}
 it('does not authorize checked sources until the single review action; editing revokes prior authorization',async()=>{const {draft,changed}=await mount();const target=draft.document.sections.flatMap(s=>s.blocks.flatMap(b=>b.lines)).find(l=>l.evidence.id==='old')!;fireEvent.change(screen.getByRole('combobox'),{target:{value:target.id}});expect(screen.getByText(target.original,{selector:'pre'})).toBeVisible();fireEvent.click(screen.getByRole('checkbox'));expect(changed).toHaveBeenLastCalledWith([]);expect(screen.getByText('My individual contribution was writing Python tests.',{selector:'pre'})).toBeVisible();fireEvent.click(screen.getByRole('button',{name:'Reviewed: use these sources for this rewrite'}));expect(changed.mock.calls.at(-1)![0][0]).toMatchObject({unit_id:target.id,confirmed:true});fireEvent.click(screen.getByRole('checkbox'));expect(changed).toHaveBeenLastCalledWith([]);expect(screen.getByRole('button',{name:'Reviewed: use these sources for this rewrite'})).toBeDisabled();});
});
