import { afterEach, describe, expect, it, vi } from 'vitest';
import { cleanup, fireEvent, render, screen } from '@testing-library/react';

vi.mock('@/i18n/client', () => ({
  useT: () => ({
    locale: 'en',
    t: (key: string, vars?: Record<string, string | number>) =>
      vars ? `${key}:${Object.values(vars).join(',')}` : key,
  }),
}));

import UniversitySwitcherModal from './UniversitySwitcherModal';
import { SCHOOL_COVERAGE_SCHEMA, displayCoverageCount } from '@/lib/school-coverage';
import { SCHOOL_STATS, SCHOOLS } from '@/lib/schools';

function renderModal(initialSelectedSlug = 'uiuc') {
  const onCancel = vi.fn();
  const onConfirm = vi.fn();
  render(
    <UniversitySwitcherModal
      initialSelectedSlug={initialSelectedSlug}
      onCancel={onCancel}
      onConfirm={onConfirm}
    />,
  );
  return { onCancel, onConfirm };
}

afterEach(() => {
  cleanup();
  vi.clearAllMocks();
});

describe('UniversitySwitcherModal — rendering', () => {
  it('renders a card for every registered school', () => {
    renderModal();
    for (const school of SCHOOLS) {
      expect(screen.getByTestId(`university-card-${school.slug}`)).toBeInTheDocument();
    }
  });

  it('marks the initial school as selected (aria-pressed)', () => {
    renderModal('ucb');
    expect(screen.getByTestId('university-card-ucb')).toHaveAttribute('aria-pressed', 'true');
    expect(screen.getByTestId('university-card-uiuc')).toHaveAttribute('aria-pressed', 'false');
  });

  it('shows coverage chips: counts for live schools, pending note otherwise', () => {
    renderModal();
    // Expected chip text derives from the registry (which itself derives from
    // school-stats.json, generated by the backend's own coverage function), so
    // this test never goes stale as the corpus grows. getAllByText because two
    // schools can floor to the same rounded count (uw and utexas both show
    // 2,200 today).
    const chipText = (slug: string) => {
      const school = SCHOOLS.find((s) => s.slug === slug)!;
      const count = displayCoverageCount(school.coverage.campusOpportunities as number);
      return `universitySwitcher.coverageCampus:${count.toLocaleString()}`;
    };
    expect(screen.getAllByText(chipText('uiuc')).length).toBeGreaterThanOrEqual(1);
    expect(screen.getAllByText(chipText('ucb')).length).toBeGreaterThanOrEqual(1);
    // Derive the expected pending count from the registry rather than a fixed
    // "minus N live schools" — the live set grows as campus collectors ship
    // (UIUC, UCB, Princeton, …).
    const pendingCount = SCHOOLS.filter(
      (s) => s.coverage.campusOpportunities === 'pending',
    ).length;
    // queryAllByText (not getAllByText) so the assertion holds at zero — every
    // school now ships a live campus count, but the registry-derived check keeps
    // working if a future pending-coverage school is added.
    expect(screen.queryAllByText('universitySwitcher.coveragePending').length).toBe(pendingCount);
  });

  it('shows a real catalog counts line on every card, no pending-catalog note left', () => {
    renderModal();
    expect(screen.getAllByText(/universitySwitcher\.catalogSummary:/).length).toBe(SCHOOLS.length);
    expect(screen.queryByText('universitySwitcher.catalogPending')).toBeNull();
    // Counts come straight from the registry (mock t renders "key:colleges,majors").
    expect(screen.getByText('universitySwitcher.catalogSummary:12,142')).toBeInTheDocument(); // uiuc
    expect(screen.getByText('universitySwitcher.catalogSummary:7,136')).toBeInTheDocument(); // ucb
    expect(screen.getByText('universitySwitcher.catalogSummary:3,72')).toBeInTheDocument(); // stanford
  });
});

describe('UniversitySwitcherModal — search', () => {
  it('filters cards by name', () => {
    renderModal();
    fireEvent.change(screen.getByRole('textbox'), { target: { value: 'Berkeley' } });
    expect(screen.getByTestId('university-card-ucb')).toBeInTheDocument();
    expect(screen.queryByTestId('university-card-uiuc')).toBeNull();
  });

  it('filters by Chinese name and by location', () => {
    renderModal();
    const input = screen.getByRole('textbox');
    fireEvent.change(input, { target: { value: '斯坦福' } });
    expect(screen.getByTestId('university-card-stanford')).toBeInTheDocument();
    expect(screen.queryByTestId('university-card-ucb')).toBeNull();
    fireEvent.change(input, { target: { value: 'Ann Arbor' } });
    expect(screen.getByTestId('university-card-umich')).toBeInTheDocument();
  });

  it('shows the empty state when nothing matches', () => {
    renderModal();
    fireEvent.change(screen.getByRole('textbox'), { target: { value: 'Hogwarts' } });
    expect(screen.getByText('universitySwitcher.noMatch:Hogwarts')).toBeInTheDocument();
  });
});

describe('UniversitySwitcherModal — select + confirm/cancel', () => {
  it('select then confirm reports the new slug', () => {
    const { onConfirm } = renderModal('uiuc');
    fireEvent.click(screen.getByTestId('university-card-ucb'));
    expect(screen.getByTestId('university-card-ucb')).toHaveAttribute('aria-pressed', 'true');
    fireEvent.click(screen.getByText('universitySwitcher.confirm'));
    expect(onConfirm).toHaveBeenCalledWith('ucb');
  });

  it('confirm without changing selection reports the initial slug', () => {
    const { onConfirm } = renderModal('uiuc');
    fireEvent.click(screen.getByText('universitySwitcher.confirm'));
    expect(onConfirm).toHaveBeenCalledWith('uiuc');
  });

  it('cancel and Escape both call onCancel without confirming', () => {
    const { onCancel, onConfirm } = renderModal();
    fireEvent.click(screen.getByText('common.cancel'));
    fireEvent.keyDown(document, { key: 'Escape' });
    expect(onCancel).toHaveBeenCalledTimes(2);
    expect(onConfirm).not.toHaveBeenCalled();
  });

  it('backdrop click cancels', () => {
    const { onCancel } = renderModal();
    const dialog = screen.getByRole('dialog');
    fireEvent.click(dialog.firstElementChild as Element);
    expect(onCancel).toHaveBeenCalledTimes(1);
  });
});

describe('UniversitySwitcherModal — live coverage counts', () => {
  const originalFetch = globalThis.fetch;

  afterEach(() => { globalThis.fetch = originalFetch; });

  function mockCoverage(body: unknown, ok = true) {
    const fetchMock = vi.fn(async () => ({ ok, json: async () => body }));
    globalThis.fetch = fetchMock as unknown as typeof fetch;
    return fetchMock;
  }

  const chip = (n: number) =>
    `universitySwitcher.coverageCampus:${displayCoverageCount(n).toLocaleString()}`;

  it('renders the backend total_count, not the listing half', async () => {
    mockCoverage({
      schema: SCHOOL_COVERAGE_SCHEMA,
      schools: {
        jhu: {
          listing_count: 27,
          faculty_contact_count: 4554,
          unreviewed_count: 0,
          total_count: 4581,
        },
      },
    });
    renderModal();

    expect((await screen.findAllByText(chip(4581))).length).toBeGreaterThanOrEqual(1);
    // 27 is what the chip showed before the fix — a 165x understatement.
    expect(screen.queryByText(chip(27))).not.toBeInTheDocument();
  });

  it('does not add faculty contacts on top of an already-combined total', async () => {
    mockCoverage({
      schema: SCHOOL_COVERAGE_SCHEMA,
      schools: {
        jhu: {
          listing_count: 27,
          faculty_contact_count: 4554,
          unreviewed_count: 0,
          total_count: 4581,
        },
      },
    });
    renderModal();

    await screen.findAllByText(chip(4581));
    expect(screen.queryByText(chip(4581 + 4554))).not.toBeInTheDocument();
  });

  it('ignores a legacy listings-only body and keeps the static number', async () => {
    // The pre-fix response shape, which an HTTP cache or a not-yet-rolled
    // backend instance can still serve. Reading `counts` from it is the bug.
    mockCoverage({ counts: { jhu: 27 }, faculty_contacts: { jhu: 4554 } });
    renderModal();

    const jhu = SCHOOLS.find((s) => s.slug === 'jhu')!;
    expect(
      (await screen.findAllByText(chip(jhu.coverage.campusOpportunities as number))).length,
    ).toBeGreaterThanOrEqual(1);
    expect(screen.queryByText(chip(27))).not.toBeInTheDocument();
  });

  it('keeps the static number when the request fails', async () => {
    mockCoverage(null, false);
    renderModal();

    const jhu = SCHOOLS.find((s) => s.slug === 'jhu')!;
    expect(
      (await screen.findAllByText(chip(jhu.coverage.campusOpportunities as number))).length,
    ).toBeGreaterThanOrEqual(1);
  });

  it('does not jump between the static and live numbers for the same dataset', async () => {
    // The hydration jump this fix removes: the chip rendered the static
    // listings+faculty number (~4,500), then fell to the live listings-only
    // number (28). Same data on both sides must now render the same chip.
    const jhu = SCHOOLS.find((s) => s.slug === 'jhu')!;
    const staticTotal = jhu.coverage.campusOpportunities as number;
    mockCoverage({
      schema: SCHOOL_COVERAGE_SCHEMA,
      schools: {
        jhu: {
          listing_count: SCHOOL_STATS.jhu!.listing_count,
          faculty_contact_count: SCHOOL_STATS.jhu!.faculty_contact_count,
          unreviewed_count: 0,
          total_count: staticTotal,
        },
      },
    });
    renderModal();

    // Before the fetch resolves: the static number.
    expect(screen.getAllByText(chip(staticTotal)).length).toBeGreaterThanOrEqual(1);
    // After it resolves: the same number, because both mean the same thing.
    expect((await screen.findAllByText(chip(staticTotal))).length).toBeGreaterThanOrEqual(1);
  });

  it('shows the pending note rather than a zero for an unmeasured school', async () => {
    mockCoverage({ schema: SCHOOL_COVERAGE_SCHEMA, schools: {} });
    renderModal();

    await screen.findAllByText(chip(SCHOOLS[0].coverage.campusOpportunities as number));
    // Every registry school still has a static number, so nothing renders "0".
    expect(screen.queryByText('universitySwitcher.coverageCampus:0')).not.toBeInTheDocument();
  });
});
