"""University of Chicago faculty config (via the faculty_graph engine).

Thirty departments across the College's divisions + the professional schools,
verified Jul 2026 (per-department directory probes; raw HTML/JSON snapshots
reviewed by hand before selectors were pinned).

  * **Live scrape (21 departments), five directory families:**
      - *WordPress+FacetWP* -- CS (single-page card grid, per-profile "Focus
        Areas" enrich).
      - *PSD MixItUp* -- Statistics, Mathematics, Physics, Astronomy (one CMS,
        shared selector set; no listing email, so a gated per-profile mailto
        pass backfills it). Geophysical Sciences is a MixItUp *variant* (no
        people_content wrapper, no listing email either).
      - *Drupal Views "bio-*"* -- Economics, Psychology + the five Social
        Sciences Division depts (Sociology, Political Science, History,
        Anthropology, Comparative Human Development). Paginated, emailed,
        interest-tagged; the /people/faculty view is ladder-clean (emeriti on a
        separate page).
      - *Drupal Views "profile-tile"* (Humanities Division) -- Philosophy
        (section-sliced to Core Faculty), English, Linguistics. Single-page,
        emailed; mixes instructional/visiting/teaching-fellow roles, so a
        title/section filter is mandatory.
      - *PME card-spotlight* -- emailed + research topics via taxonomy spans.
      - *Professional-school directories* -- Harris (teaser-table, profile-type
        field filter), Law (profile-list, profile_type=103 view), Crown Family
        School (person-card, capital-T "mailTo:" recovered by _clean_email),
        Divinity (faceted-path faculty view, no listing email -> gated profile
        mailto pass). Booth is deliberately omitted (a JS-only Coveo search with
        no scrapable feed); the Data Science Institute is skipped (its whole
        roster is cross-appointed CS/Stat/Harris/etc. -- adding it would
        double-count).
  * **Curated seeds from the sites' own JSON APIs (9 departments).** Chemistry's
    directory page and the eight BSD department sites (Ecology & Evolution,
    Neurobiology, Human Genetics, Molecular Genetics & Cell Biology,
    Biochemistry & Molecular Biology, Organismal Biology & Anatomy, Public
    Health Sciences, Microbiology) are JS-only shells; the shared BSD data
    endpoint (bsd-data.prod.uchicago.edu/api/faculty_index) additionally
    requires a uchicago Referer header the engine doesn't send. Their rosters
    were pulled from the APIs (chemistry: live-ucchem.pantheonsite.io/api/
    faculty_index) in Jul 2026 and frozen as curated ``faculty(...)`` seeds --
    the Michigan model. Each BSD seed keeps its PRIMARY appointment only
    (``department[0]`` -- the API repeats joint appointments in every dept they
    touch) and links to the stable ``profiles.uchicago.edu`` research-network
    URL. Migrate to live ``json_dir`` blocks if the engine grows per-source
    headers + relative-link joins.

BSD department chairs carry the literal title "Chair" (Carole Ober, David
Freedman, ...), not "...Professor", so the BSD dumps used a drop-only rank
filter -- requiring "professor" would have dropped every chair. Emails are
absent from all nine API rosters and from the PSD/geosci MixItUp listings;
records there ship as linked, keyworded cold-email targets, like the UW Arts &
Sciences departments.

Single source ("uchicago_faculty") across all departments (the UIUC model); the
department rides on each record's ``department`` field, and ids are namespaced
by department short-code so they never collide. Audience "unknown" (per-prof
openness).
"""

from __future__ import annotations

from .. import faculty_graph
from ..faculty_graph import faculty


# The four PSD departments (Statistics, Mathematics, Physics, Astronomy) share
# one custom-CMS "MixItUp" directory: a single server-rendered <li class="mix
# <role>"> list per site, filtered client-side. The role classes differ per
# site (math isolates ladder faculty as "professors"; the others mix ranks
# inside "faculty"), so the card selector and title filter are parameters.
def _psd(short: str, name: str, majors: list[str], url: str, *,
         card: str = "li.mix.faculty", ladder_filter: dict | None = None) -> dict:
    return {"short": short, "name": name, "majors": majors, "directory_url": url,
            "scrape": {"url": url,
                       "selectors": {"card": card,
                                     "name": ".people_content h3 span",
                                     "link": "a",
                                     "title": ".people_content h3 b"},
                       # The MixItUp listing cards carry no email; each professor's
                       # profile page keeps a personal mailto. Backfill it via the
                       # gated per-profile pass (OFE_ENRICH_PROFILES=1 for the
                       # one-shot generation run; off in weekly CI, where the
                       # already-enriched emails carry forward through the merge).
                       "profile_enrich": {"email_selector": "a[href^='mailto:']",
                                          "throttle": 0.75},
                       **({"ladder_filter": ladder_filter} if ladder_filter else {})}}


# Economics and Psychology share the university's Drupal Views directory theme:
# paginated ?page=N views with emailed, interest-tagged cards. Emeriti mix into
# the Economics view (Psychology keeps them on a separate URL); one drop rule
# covers both.
def _views(short: str, name: str, majors: list[str], url: str, *,
           max_pages: int) -> dict:
    return {"short": short, "name": name, "majors": majors, "directory_url": url,
            "scrape": {"url": url,
                       "selectors": {"card": "div.views-row",
                                     "name": "h2.no-tags > a",
                                     "link": "h2.no-tags > a",
                                     "title": "div.bio-subtitle",
                                     "email": "div.bio-email a",
                                     "research": "div.bio-interest"},
                       "paginate": {"param": "page", "start": 1, "max": max_pages},
                       "ladder_filter": {"drop": r"emerit"}}}


# The Humanities Division uses a SECOND Drupal Views variant ("profile-tile"):
# tiles carry the name in ``h2.info > a > span`` and use ``field--name-field-*``
# divs for title/email, with no research field. These pages are single-page (no
# pagination) and mix ladder with instructional/visiting/teaching-fellow roles,
# so a ladder_filter (or a section slice for the sectioned Philosophy page) is
# mandatory, unlike the ladder-clean Family-A faculty views.
def _tile(short: str, name: str, majors: list[str], url: str, *,
          ladder_filter: dict | None = None, section_filter: dict | None = None) -> dict:
    scrape = {"url": url,
              "selectors": {"card": "div.views-row",
                            "name": "h2.info > a > span",
                            "link": "h2.info > a",
                            "title": "div.field--name-field-person-faculty-title",
                            "email": "div.field--name-field-person-email > a"}}
    if ladder_filter:
        scrape["ladder_filter"] = ladder_filter
    if section_filter:
        scrape["section_filter"] = section_filter
    return {"short": short, "name": name, "majors": majors,
            "directory_url": url, "scrape": scrape}


SCHOOL: dict = {
    "school_slug": "uchicago",
    "source": "uchicago_faculty",
    "organization": "University of Chicago",
    "location": "Chicago, IL",
    "id_prefix": "uchicago",
    "audience": "unknown",
    "work_auth_notes": (
        "External campus (University of Chicago) -- work authorization depends "
        "on the arrangement; ask the professor."
    ),
    "departments": [
        {
            "short": "CS",
            "name": "Department of Computer Science",
            "majors": ["Computer Science", "Data Science"],
            "directory_url": "https://cs.uchicago.edu/people/uchicago-faculty/full-time-faculty/",
            "scrape": {
                "url": "https://cs.uchicago.edu/people/uchicago-faculty/full-time-faculty/",
                "selectors": {
                    "card": "div.card.card--person",
                    "name": "h3.card__title",
                    "link": "a.card__url",
                    "title": "div.card__position",
                },
                "ladder_filter": {
                    "require": r"professor",
                    "drop": r"emerit|clinical|instructional|research (assistant|associate) professor|masters",
                },
                # The listing carries name/title only; each profile keeps a
                # "<strong>Focus Areas:</strong> <em>A, B</em>" block (gated
                # per-profile enrich, OFE_ENRICH_PROFILES=1).
                "profile_enrich": {
                    "research_html_re": r"Focus Areas?:\s*</strong>\s*<em>(.*?)</em>",
                    "throttle": 1.0,
                },
            },
        },
        _psd("STAT", "Department of Statistics",
             ["Statistics", "Data Science", "Computational and Applied Mathematics"],
             "https://stat.uchicago.edu/people/",
             ladder_filter={"require": r"professor",
                            "drop": r"emerit|instructional|part-time|visiting|lecturer"}),
        _psd("MATH", "Department of Mathematics",
             ["Mathematics", "Computational and Applied Mathematics"],
             "https://mathematics.uchicago.edu/people/",
             # ladder faculty already isolated by the "professors" role class;
             # instructional/visiting/Dickson instructors carry other classes.
             card="li.mix.professors",
             ladder_filter={"drop": r"emerit"}),
        _psd("PHYS", "Department of Physics",
             ["Physics", "Astrophysics"],
             "https://physics.uchicago.edu/people/",
             ladder_filter={"require": r"professor",
                            "drop": r"emerit|lecturer|instructional|research professor|part-time|scientist|visiting"}),
        _psd("ASTRO", "Department of Astronomy and Astrophysics",
             ["Astrophysics", "Physics"],
             "https://astrophysics.uchicago.edu/people/",
             # the site splits research-faculty/emeriti into their own role
             # classes; within "faculty" the chair/deputy-chair titles carry no
             # "Professor" word, so drop-only.
             ladder_filter={"drop": r"emerit|research professor|lecturer|instructional|part-time|scientist|visiting|postdoc"}),
        _views("ECON", "Kenneth C. Griffin Department of Economics",
               ["Economics"],
               "https://economics.uchicago.edu/people/faculty", max_pages=6),
        _views("PSYCH", "Department of Psychology",
               ["Psychology"],
               "https://psychology.uchicago.edu/people/faculty", max_pages=5),
        # Social Sciences Division — same Family-A bio-* Drupal Views as Econ/
        # Psych. Each dept's /people/faculty view is ladder-clean (emeriti live
        # on a separate page), so the drop-emerit in _views is just a safety net.
        _views("SOC", "Department of Sociology", ["Sociology"],
               "https://sociology.uchicago.edu/people/faculty", max_pages=3),
        _views("POLISCI", "Department of Political Science", ["Political Science"],
               "https://political-science.uchicago.edu/people/faculty", max_pages=4),
        _views("HIST", "Department of History", ["History"],
               "https://history.uchicago.edu/people/faculty", max_pages=5),
        # Anthropology's path is capitalized — the server 403s /people/faculty
        # and redirects /people/faculty -> /People/Faculty.
        _views("ANTHRO", "Department of Anthropology", ["Anthropology"],
               "https://anthropology.uchicago.edu/People/Faculty", max_pages=3),
        _views("HDEV", "Department of Comparative Human Development",
               ["Comparative Human Development"],
               "https://humdev.uchicago.edu/people/faculty", max_pages=3),
        # Humanities Division — Family-B profile-tile. Philosophy is sectioned
        # (slice the Core Faculty group); English + Linguistics are flat lists
        # mixing instructional/visiting/teaching-fellow roles, gated by title.
        _tile("PHIL", "Department of Philosophy", ["Philosophy"],
              "https://philosophy.uchicago.edu/people/profiles",
              section_filter={"heading": "h3", "include": r"core faculty"},
              ladder_filter={"drop": r"emerit|instructional|visiting|lecturer"}),
        _tile("ENGL", "Department of English Language and Literature",
              ["English Language and Literature", "Creative Writing"],
              "https://english.uchicago.edu/people/faculty-and-lecturers",
              # exclude on the literal "Collegiate Assistant Professor" (a
              # Harper-Schmidt fellowship), not bare "Collegiate" — else a real
              # Associate Professor in the Humanities Collegiate Division drops.
              ladder_filter={"require": r"\bprofessor\b",
                             "drop": r"instructional|visiting|collegiate assistant professor"
                                     r"|teaching fellow|harper-schmidt|advisor|postdoc|emerit"}),
        _tile("LING", "Department of Linguistics", ["Linguistics"],
              "https://linguistics.uchicago.edu/people/profiles",
              ladder_filter={"drop": r"instructional|teaching fellow|postdoc|emerit"}),
        # Physical Sciences — Geophysical Sciences is a MixItUp variant with a
        # different inner markup than the Stat/Math/Physics/Astro sites (no
        # people_content wrapper); the listing carries no email.
        {
            "short": "GEOS",
            "name": "Department of the Geophysical Sciences",
            "majors": ["Geophysical Sciences", "Environmental Science", "Climate and Sustainable Growth"],
            "directory_url": "https://geosci.uchicago.edu/people/",
            "scrape": {
                "url": "https://geosci.uchicago.edu/people/",
                "selectors": {"card": "li.mix.academic-faculty",
                              "name": "h2 > a", "link": "h2 > a",
                              "title": "h2 > small",
                              "research": "dl > dd"},
                "ladder_filter": {"drop": r"emerit"},
            },
        },
        # Professional schools. Each has its own directory theme; Booth is
        # deliberately omitted (a JS-only Coveo search with no scrapable feed).
        {
            "short": "HARRIS",
            "name": "Harris School of Public Policy",
            "majors": ["Public Policy Studies", "Economics"],
            "directory_url": "https://harris.uchicago.edu/directory",
            "scrape": {
                "url": "https://harris.uchicago.edu/directory",
                "selectors": {"card": "article.teaser-table--profile",
                              "name": "h2.teaser-table--title a",
                              "link": "h2.teaser-table--title a",
                              "title": "div.teaser-table--job-title .field__item",
                              "email": "div.teaser-table--link a[href^='mailto:' i]"},
                # the directory mixes Faculty / Lecturer / PhD Student / Staff /
                # Visiting Academic as a per-card profile-type; keep Faculty, then
                # require "professor" to drop the Research Associates within it.
                "field_filter": {"selector": "div.teaser-table--profile-type", "include": r"Faculty"},
                "ladder_filter": {"require": r"professor", "drop": r"emerit|visiting|lecturer"},
                "paginate": {"param": "page", "start": 1, "max": 4},
            },
        },
        {
            "short": "LAW",
            "name": "University of Chicago Law School",
            "majors": ["Law, Letters, and Society"],
            # profile_type=103 is the Full-Time Teaching Faculty view; the title
            # filter drops the clinical/practice/visiting ranks mixed into it.
            "directory_url": "https://www.law.uchicago.edu/directory?profile_type=103",
            "scrape": {
                "url": "https://www.law.uchicago.edu/directory?profile_type=103",
                "selectors": {"card": "li.profile-list__item",
                              "name": ".profile-list--item__name a span",
                              "link": ".profile-list--item__name a",
                              "title": ".profile-list--item__job-title",
                              "email": ".profile-list--item__contact a[href^='mailto:' i]"},
                "ladder_filter": {"require": r"professor",
                                  "drop": r"emerit|visiting|lecturer|clinical|from practice|of practice|fellow|director"},
                "paginate": {"param": "page", "start": 1, "max": 5},
            },
        },
        {
            "short": "CROWN",
            "name": "Crown Family School of Social Work, Policy, and Practice",
            "majors": ["Public Policy Studies"],
            # /research-faculty/faculty-directory, NOT /directory (which mixes
            # staff, doctoral students, and centers). Emails use a capital-T
            # "mailTo:" scheme the engine's _clean_email regex still recovers.
            "directory_url": "https://crownschool.uchicago.edu/research-faculty/faculty-directory",
            "scrape": {
                "url": "https://crownschool.uchicago.edu/research-faculty/faculty-directory",
                "selectors": {"card": "article.node--type-person.node--view-mode-card",
                              "name": "h3.person-name a",
                              "link": "h3.person-name a",
                              "title": "span.person-title",
                              "email": ".card-details a[href^='mailto:' i]"},
                "ladder_filter": {"require": r"professor", "drop": r"emerit|lecturer|instructional"},
                "paginate": {"param": "page", "start": 1, "max": 3},
            },
        },
        {
            "short": "DIV",
            "name": "University of Chicago Divinity School",
            "majors": ["Religious Studies"],
            # Faceted PATH URL selects the "faculty" role (emeritus/visiting/
            # associated/teaching-fellows live under sibling path segments). The
            # listing carries no email; the per-profile pass (gated) backfills it.
            "directory_url": "https://divinity.uchicago.edu/directory/all/faculty/all/all",
            "scrape": {
                "url": "https://divinity.uchicago.edu/directory/all/faculty/all/all",
                "selectors": {"card": "div.faculty-detail-section",
                              "name": "h5.name-faculty",
                              "link": "a[href^='/directory/']",
                              "title": "h5.name-faculty + span"},
                "ladder_filter": {"require": r"professor", "drop": r"emerit|visiting|lecturer|instructional|fellow"},
                "paginate": {"param": "page", "start": 1, "max": 5},
                "profile_enrich": {"email_selector": "a[href^='mailto:' i]", "throttle": 0.75},
            },
        },
        {
            "short": "PME",
            "name": "Pritzker School of Molecular Engineering",
            "majors": ["Molecular Engineering"],
            "directory_url": "https://pme.uchicago.edu/faculty-research/faculty-directory",
            "scrape": {
                "url": "https://pme.uchicago.edu/faculty-research/faculty-directory",
                "selectors": {
                    "card": "div.card-spotlight.node--type-faculty",
                    "name": "a.card-spotlight__title",
                    "link": "a.card-spotlight__title",
                    "title": "div.card-spotlight__position",
                    "email": "div.card-spotlight__email a[href^='mailto:']",
                    # scholarly-interest taxonomy spans; the .eyebrow child is
                    # the "Research & Scholarly Interests" label, not a topic.
                    "research_items": "div.card-spotlight__research-scholar-intrest span:not(.eyebrow)",
                },
                "ladder_filter": {"drop": r"emerit"},
            },
        },
        {
            "short": "CHEM",
            "name": "Department of Chemistry",
            "majors": ["Chemistry", "Biological Chemistry"],
            "directory_url": "https://chemistry.uchicago.edu/faculty",
            "faculty": [
            faculty("Paul Alivisatos", title="President of the University of Chicago; John D. MacArthur Distinguished Service Professor",
                    url="https://chemistry.uchicago.edu/paul-alivisatos",
                    keywords=["Materials Chemistry", "Physical Chemistry"]),
            faculty("Chuan He", title="John T. Wilson Distinguished Service Professor",
                    url="https://chemistry.uchicago.edu/chuan-he",
                    keywords=["Chemical Biology", "Inorganic Chemistry"]),
            faculty("Hening Lin", title="Professor",
                    url="https://chemistry.uchicago.edu/hening-lin",
                    keywords=["Chemical Biology", "Organic Chemistry"]),
            faculty("Michael Hopkins", title="Professor",
                    url="https://chemistry.uchicago.edu/michael-hopkins",
                    keywords=["Materials Chemistry", "Inorganic Chemistry"]),
            faculty("John Anderson", title="Professor and Associate Chair",
                    url="https://chemistry.uchicago.edu/john-anderson",
                    keywords=["Inorganic Chemistry", "Catalysis", "Materials Chemistry"]),
            faculty("Sarah King", title="Assistant Professor of Chemistry",
                    url="https://chemistry.uchicago.edu/sarah-king",
                    keywords=["Physical Chemistry", "Materials Chemistry"]),
            faculty("Bryan Dickinson", title="Professor",
                    url="https://chemistry.uchicago.edu/bryan-dickinson",
                    keywords=["Chemical Biology"]),
            faculty("Aaron Dinner", title="Professor",
                    url="https://chemistry.uchicago.edu/aaron-dinner",
                    keywords=["Biophysics", "Theoretical Chemistry", "Physical Chemistry"]),
            faculty("Greg Engel", title="Professor",
                    url="https://chemistry.uchicago.edu/greg-engel",
                    keywords=["Biophysics", "Physical Chemistry", "Materials Chemistry"]),
            faculty("Andrew Ferguson", title="Professor of Chemistry, Professor of Molecular Engineering, Vice Dean for Education and Outreach in the Pritzker School of Molecular Engineering",
                    url="https://chemistry.uchicago.edu/andrew-ferguson",
                    keywords=["Physical Chemistry", "Biophysics", "Theoretical Chemistry"]),
            faculty("Giulia Galli", title="Liew Family Professor",
                    url="https://chemistry.uchicago.edu/giulia-galli",
                    keywords=["Theoretical Chemistry", "Physical Chemistry"]),
            faculty("Philippe Guyot-Sionnest", title="Professor",
                    url="https://chemistry.uchicago.edu/philippe-guyot-sionnest",
                    keywords=["Materials Chemistry", "Physical Chemistry"]),
            faculty("Guangbin Dong", title="Weldon G. Brown Professor",
                    url="https://chemistry.uchicago.edu/guangbin-dong",
                    keywords=["Organic Chemistry", "Catalysis"]),
            faculty("David Mazziotti", title="Professor",
                    url="https://chemistry.uchicago.edu/david-mazziotti",
                    keywords=["Theoretical Chemistry", "Physical Chemistry", "Biophysics"]),
            faculty("Raymond Moellering", title="Professor",
                    url="https://chemistry.uchicago.edu/raymond-moellering",
                    keywords=["Chemical Biology", "Organic Chemistry"]),
            faculty("Jiwoong Park", title="Professor and Chair",
                    url="https://chemistry.uchicago.edu/jiwoong-park",
                    keywords=["Materials Chemistry", "Physical Chemistry"]),
            faculty("Joseph Piccirilli", title="Professor",
                    url="https://chemistry.uchicago.edu/joseph-piccirilli",
                    keywords=["Chemical Biology", "Catalysis"]),
            faculty("Viresh Rawal", title="Professor",
                    url="https://chemistry.uchicago.edu/viresh-rawal",
                    keywords=["Catalysis", "Organic Chemistry"]),
            faculty("Benoît Roux", title="Professor",
                    url="https://chemistry.uchicago.edu/benoit-roux",
                    keywords=["Theoretical Chemistry", "Biophysics", "Physical Chemistry"]),
            faculty("Dmitri Talapin", title="Ernest DeWitt Burton Distinguished Service Professor",
                    url="https://chemistry.uchicago.edu/dmitri-talapin",
                    keywords=["Materials Chemistry", "Inorganic Chemistry"]),
            faculty("Yamuna Krishnan", title="Louis Block Professor of Chemistry and the College",
                    url="https://chemistry.uchicago.edu/yamuna-krishnan",
                    keywords=["Chemical Biology", "Biophysics", "Organic Chemistry"]),
            faculty("Mark Levin", title="Professor",
                    url="https://chemistry.uchicago.edu/mark-levin",
                    keywords=["Organic Chemistry", "Catalysis", "Inorganic Chemistry"]),
            faculty("Wenbin Lin", title="James Franck Professor of Chemistry",
                    url="https://chemistry.uchicago.edu/wenbin-lin",
                    keywords=["Materials Chemistry", "Catalysis", "Inorganic Chemistry", "Chemical Biology"]),
            faculty("Weixin Tang", title="Associate Professor",
                    url="https://chemistry.uchicago.edu/weixin-tang",
                    keywords=["Chemical Biology", "Biophysics", "Organic Chemistry"]),
            faculty("Bozhi Tian", title="Professor",
                    url="https://chemistry.uchicago.edu/bozhi-tian",
                    keywords=["Biophysics", "Materials Chemistry", "Inorganic Chemistry", "Physical Chemistry"]),
            faculty("Andrei Tokmakoff", title="Henry G. Gale Distinguished Service Professor",
                    url="https://chemistry.uchicago.edu/andrei-tokmakoff",
                    keywords=["Biophysics", "Physical Chemistry"]),
            faculty("Stuart Rowan", title="Barry L. MacLean Professor for Molecular Engineering Innovation and Enterprise",
                    url="https://chemistry.uchicago.edu/stuart-rowan",
                    keywords=["Materials Chemistry", "Organic Chemistry"]),
            faculty("Norbert Scherer", title="Professor",
                    url="https://chemistry.uchicago.edu/norbert-scherer",
                    keywords=["Biophysics", "Materials Chemistry", "Physical Chemistry"]),
            faculty("Elena Shevchenko", title="Professor (Part-time)",
                    url="https://chemistry.uchicago.edu/elena-shevchenko",
                    keywords=["Catalysis", "Inorganic Chemistry", "Materials Chemistry", "Physical Chemistry"]),
            faculty("Suri Vaikuntanathan", title="Professor",
                    url="https://chemistry.uchicago.edu/suri-vaikuntanathan",
                    keywords=["Biophysics", "Theoretical Chemistry", "Physical Chemistry"]),
            faculty("Steven Sibener", title="Carl William Eisendrath Distinguished Service Professor",
                    url="https://chemistry.uchicago.edu/steven-j-sibener",
                    keywords=["Biophysics", "Materials Chemistry", "Physical Chemistry"]),
            faculty("Scott Snyder", title="Professor",
                    url="https://chemistry.uchicago.edu/scott-snyder",
                    keywords=["Chemical Biology", "Organic Chemistry"]),
            faculty("Jack W. Szostak", title="University Professor",
                    url="https://chemistry.uchicago.edu/jack-w-szostak",
                    keywords=["Chemical Biology", "Biophysics", "Organic Chemistry", "Physical Chemistry"]),
            faculty("Gregory A. Voth", title="Haig P. Papazian Distinguished Service Professor",
                    url="https://chemistry.uchicago.edu/gregory-a-voth",
                    keywords=["Biophysics", "Materials Chemistry", "Theoretical Chemistry", "Physical Chemistry"]),
            faculty("Anna Wuttig", title="Neubauer Family Assistant Professor",
                    url="https://chemistry.uchicago.edu/anna-wuttig",
                    keywords=["Catalysis", "Organic Chemistry", "Inorganic Chemistry", "Materials Chemistry"]),
            faculty("Jie Zhou", title="Assistant Professor",
                    url="https://chemistry.uchicago.edu/jie-zhou",
                    keywords=["Chemical Biology"]),
            faculty("Hannah Lant", title="Assistant Instructional Professor",
                    url="https://chemistry.uchicago.edu/hannah-lant-phd",
                    keywords=["Inorganic Chemistry", "Chemical Education"]),
            faculty("Shaunna McLeod", title="Assistant Instructional Professor",
                    url="https://chemistry.uchicago.edu/shaunna-mcleod",
                    keywords=["Chemical Education"]),
            faculty("Dipti Jasrasaria", title="Assistant Professor",
                    url="https://chemistry.uchicago.edu/dipti-jasrasaria",
                    keywords=["Theoretical Chemistry", "Physical Chemistry", "Materials Chemistry"]),
            faculty("Alex Cusumano", title="Assistant Professor",
                    url="https://chemistry.uchicago.edu/alex-cusumano",
                    keywords=["Organic Chemistry", "Catalysis", "Computational Chemistry"]),
            ],
        },
        {
            "short": "ECEV",
            "name": "Department of Ecology and Evolution",
            "majors": ["Biological Sciences", "Environmental Science"],
            "directory_url": "https://ecologyandevolution.uchicago.edu/people/faculty",
            "faculty": [
            faculty("John Timothy Wootton", title="Professor",
                    url="https://ecologyandevolution.uchicago.edu/john-timothy-wootton-phd",
                    keywords=["Avian Ecology", "Community Ecology", "Conservation", "Ecological Networks", "Ecosystems", "Environmental Imact", "Experimental Community Ecology", "Food Web"]),
            faculty("Joseph Thornton", title="Professor",
                    url="https://ecologyandevolution.uchicago.edu/joseph-thornton-phd",
                    keywords=["Biochemistry", "Evolution", "Evolution, Genetic", "Evolutionary biochemistry", "Molecular Evolution", "Phylogenetics"]),
            faculty("Sarah E. Cobey", title="Professor",
                    url="https://ecologyandevolution.uchicago.edu/sarah-e-cobey-phd",
                    keywords=["B cells", "coevolution", "infectious disease dynamics", "influenza", "mathematical modeling", "vaccination"]),
            faculty("Trevor D. Price", title="Professor",
                    url="https://ecologyandevolution.uchicago.edu/trevor-d-price-phd",
                    keywords=["color vision in birds", "India's biodiversity", "Macroecology", "speciation"]),
            faculty("Luis Bettencourt", title="Professor",
                    url="https://ecologyandevolution.uchicago.edu/luis-bettencourt-phd",
                    keywords=["Cities", "Complex Systems", "Epidemiology", "Evolutionary Dynamics", "Learning", "Networks", "Social Processes and Institutions", "Statistical Theory"]),
            faculty("Manyuan Long", title="Edna K. Papazian Distinguished Service Professor",
                    url="https://ecologyandevolution.uchicago.edu/manyuan-long-phd"),
            faculty("Gregory Dwyer", title="Professor",
                    url="https://ecologyandevolution.uchicago.edu/gregory-dwyer-phd",
                    keywords=["Climate Change", "Eco-evolutionary dynamics", "Host-Pathogen Interactions", "Mathematical ecoloty", "Quantitative Ecology", "Statistical Computing"]),
            faculty("Catherine Pfister", title="Professor",
                    url="https://ecologyandevolution.uchicago.edu/catherine-pfister-phd"),
            faculty("Marcus R. Kronforst", title="Professor",
                    url="https://ecologyandevolution.uchicago.edu/marcus-r-kronforst-phd",
                    keywords=["adaptation", "evolutionary genomics", "population genetics", "speciation"]),
            faculty("Stefano Allesina", title="Chair",
                    url="https://ecologyandevolution.uchicago.edu/stefano-allesina-phd",
                    keywords=["Community Ecology", "Dynamical Systems", "Food Webs", "Networks, Ecological", "Theoretical Ecology"]),
            faculty("Seppe Kuehn", title="Associate Professor",
                    url="https://ecologyandevolution.uchicago.edu/seppe-kuehn-phd"),
            faculty("Matthias Steinruecken", title="Associate Professor",
                    url="https://ecologyandevolution.uchicago.edu/matthias-steinruecken-phd",
                    keywords=["Mathematical Biology", "Population Genetics", "Statistical Genetics"]),
            faculty("Pavitra Muralidhar", title="Assistant Professor",
                    url="https://ecologyandevolution.uchicago.edu/pavitra-muralidhar-phd"),
            faculty("Carl Veller", title="Assistant Professor",
                    url="https://ecologyandevolution.uchicago.edu/carl-veller-phd"),
            faculty("Julia Kreiner", title="Assistant Professor",
                    url="https://ecologyandevolution.uchicago.edu/julia-kreiner-phd"),
            faculty("Dakota McCoy", title="Assistant Professor",
                    url="https://ecologyandevolution.uchicago.edu/dakota-mccoy-phd"),
            faculty("Lauren Carley", title="Assistant Professor",
                    url="https://ecologyandevolution.uchicago.edu/lauren-carley",
                    keywords=["Adaptation", "Chemical ecology", "Evolutionary Ecology", "Species interactions"]),
            faculty("Rachel Moran", title="Assistant Professor",
                    url="https://ecologyandevolution.uchicago.edu/rachel-moran"),
            ],
        },
        {
            "short": "NEURO",
            "name": "Department of Neurobiology",
            "majors": ["Neuroscience", "Biological Sciences"],
            "directory_url": "https://neurobiology.uchicago.edu/our-faculty",
            "faculty": [
            faculty("John H.R. Maunsell", title="Albert D. Lasker Distinguished Service Professor",
                    url="https://neurobiology.uchicago.edu/john-hr-maunsell-phd"),
            faculty("David Freedman", title="Chair",
                    url="https://neurobiology.uchicago.edu/david-freedman-phd"),
            faculty("Peggy Mason", title="Professor",
                    url="https://neurobiology.uchicago.edu/peggy-mason-phd"),
            faculty("Clifton Warren Ragsdale", title="Professor",
                    url="https://neurobiology.uchicago.edu/clifton-warren-ragsdale-phd",
                    keywords=["Developmental Biology", "Evolutionary biology", "Neocortex", "Octopuses", "Regeneration", "Systems Neuroscience"]),
            faculty("Sangram S. Sisodia", title="Thomas A. Reynolds Sr. Family Professor",
                    url="https://neurobiology.uchicago.edu/sangram-s-sisodia-phd"),
            faculty("Paschalis Kratsios", title="Associate Professor",
                    url="https://neurobiology.uchicago.edu/paschalis-kratsios-phd",
                    keywords=["C.elegans genetics", "chromatin factors", "gene regulation", "Gene Regulatory Networks", "mouse genetics", "neuronal development", "Transcription Factors"]),
            faculty("Wei Wei", title="Professor",
                    url="https://neurobiology.uchicago.edu/wei-wei-phd"),
            faculty("Christian R. Hansel", title="Professor",
                    url="https://neurobiology.uchicago.edu/christian-r-hansel-phd",
                    keywords=["Cerebellum", "Intrinsic Plasticity", "Neocortex", "Purkinje cell", "Synaptic Plasticity"]),
            faculty("Jason Maclean", title="Professor",
                    url="https://neurobiology.uchicago.edu/jason-maclean-phd",
                    keywords=["Graph Theory", "Local Circuitry", "Machine Learning", "Motor Cortex", "Neocortex", "Somatosensory Cortex", "Visual Cortex"]),
            faculty("Ruth Anne Eatock", title="Professor",
                    url="https://neurobiology.uchicago.edu/ruth-anne-eatock-phd",
                    keywords=["Action Potentials", "Hair Cell, Vestibular", "Inner Ear", "Sensory Function", "Sensory Neurons", "Synaptic Transmission", "Voltage-Gated Calcium Channels", "Voltage-Gated Potassium Channels"]),
            faculty("S. Murray Sherman", title="Maurice Goldblatt Professor",
                    url="https://neurobiology.uchicago.edu/s-murray-sherman-phd",
                    keywords=["Cortex, Cerebral", "Lateral Geniculate Body", "Pulvinar", "Somatosensory Cortex", "Thalamus", "Ventral Posteromedial Thalamic Nucleus", "Vision", "Visual Cortex"]),
            faculty("William Green", title="Professor",
                    url="https://neurobiology.uchicago.edu/william-green-phd",
                    keywords=["Acetylcholine", "Acetylcholine Receptors, Nicotinic", "Cell Biology of Neurons", "Glutamate", "Glutamate Receptors, Ionotropic", "Nicotine", "Nicotine Addiction", "Synapses"]),
            faculty("Xiaoxi Zhuang", title="Professor",
                    url="https://neurobiology.uchicago.edu/xiaoxi-zhuang"),
            faculty("Brent Doiron", title="Heinrich Kluver Professor",
                    url="https://neurobiology.uchicago.edu/brent-doiron-phd"),
            faculty("Mark Sheffield", title="Associate Professor",
                    url="https://neurobiology.uchicago.edu/mark-sheffield-phd",
                    keywords=["2-photon", "contextual fear conditioning", "dendrites", "hippocampus", "learning", "memory", "neuromodulation", "optogenetics"]),
            faculty("Marlene Cohen", title="Professor",
                    url="https://neurobiology.uchicago.edu/marlene-cohen-phd"),
            faculty("Narayanan Kasthuri", title="Associate Professor",
                    url="https://neurobiology.uchicago.edu/narayanan-kasthuri-md"),
            faculty("Ramon Nogueira Manas", title="Assistant Professor",
                    url="https://neurobiology.uchicago.edu/ramon-nogueira-manas-phd"),
            faculty("Jorge Jaramillo", title="Assistant Professor",
                    url="https://neurobiology.uchicago.edu/jorge-jaramillo-phd"),
            faculty("Marcella Noorman", title="Assistant Professor",
                    url="https://neurobiology.uchicago.edu/marcella-noorman"),
            faculty("Anne-Marie Oswald", title="Associate Professor",
                    url="https://neurobiology.uchicago.edu/anne-marie-oswald"),
            faculty("Samuel Muscinelli", title="Assistant Professor",
                    url="https://neurobiology.uchicago.edu/samuel-muscinelli"),
            faculty("Lucas Pinto", title="Assistant Professor",
                    url="https://neurobiology.uchicago.edu/lucas-pinto"),
            faculty("Sumin Jang", title="Assistant Professor",
                    url="https://neurobiology.uchicago.edu/sumin-jang",
                    keywords=["Human Development", "Motor Neuron Disease", "Motor Neurons", "Neural Progenitors", "Neurodevelopment"]),
            faculty("Julia Cox", title="Assistant Professor",
                    url="https://neurobiology.uchicago.edu/julia-cox"),
            ],
        },
        {
            "short": "HG",
            "name": "Department of Human Genetics",
            "majors": ["Biological Sciences"],
            "directory_url": "https://genes.uchicago.edu/people/our-faculty",
            "faculty": [
            faculty("Xin He", title="Professor",
                    url="https://genes.uchicago.edu/xin-he-phd",
                    keywords=["Cancer genomics", "Computational biology", "Gene regulation", "Psychiatric genetics", "Statistical genetics"]),
            faculty("John Novembre", title="Professor",
                    url="https://genes.uchicago.edu/john-novembre-phd",
                    keywords=["Computational Biology", "Computational Statistics", "Data Science", "Genomics", "Human Genetics", "Molecular Evolution", "Population Genetics"]),
            faculty("Carole Ober", title="Chair",
                    url="https://genes.uchicago.edu/carole-ober-phd"),
            faculty("T. Conrad Gilliam", title="Marjorie I. and Bernard A. Mitchell Distinguished Service Professor",
                    url="https://genes.uchicago.edu/t-conrad-gilliam-phd"),
            faculty("Francois Spitz", title="Professor",
                    url="https://genes.uchicago.edu/francois-spitz-phd",
                    keywords=["Developmental Disorders", "Epigenomics", "Evolution, Genetic", "Gene Expression Regulation", "Gene Regulatory Networks", "Genomics"]),
            faculty("Jeremy Berg", title="Assistant Professor",
                    url="https://genes.uchicago.edu/jeremy-berg-phd",
                    keywords=["Complex Traits and Diseases", "Population Genetics", "Quantitative Genetics"]),
            faculty("Marcelo A. Nobrega", title="A.N. Pritzker Professor",
                    url="https://genes.uchicago.edu/marcelo-nobrega-md-phd"),
            faculty("Maanasa Raghavan", title="Neubauer Family Assistant Professor",
                    url="https://genes.uchicago.edu/maanasa-raghavan-phd",
                    keywords=["Ancient DNA", "Genomics", "Human Evolution", "Population and Evolutionary Genetics"]),
            faculty("Matthew Stephens", title="Professor",
                    url="https://genes.uchicago.edu/matthew-stephens"),
            faculty("Xiaochang Zhang", title="Associate Professor",
                    url="https://genes.uchicago.edu/xiaochang-zhang-phd",
                    keywords=["Alternative RNA Splicing", "Brain development and disorders", "Cell type specification", "Gene regulation"]),
            faculty("Zhuzhu Zhang", title="Assistant Professor",
                    url="https://genes.uchicago.edu/zhuzhu-zhang-phd",
                    keywords=["Brain development and disorders", "Epigenomics", "Gene Regulatory Networks", "Genetics", "Neuroscience", "Psychiatric disorders", "Single-cell genomics"]),
            faculty("Ronan O'Malley", title="Assistant Professor",
                    url="https://genes.uchicago.edu/ronan-omalley-phd"),
            faculty("Francesca Luca", title="Professor",
                    url="https://genes.uchicago.edu/francesca-luca-phd"),
            faculty("Daniela Del Gaudio", title="Professor",
                    url="https://genes.uchicago.edu/daniela-del-gaudio-phd"),
            faculty("Soma Das", title="Professor",
                    url="https://genes.uchicago.edu/soma-das-phd",
                    keywords=["Ataxia", "Exome sequencing", "Molecular Diagnostics", "Mutation detection", "Neurogenetic disorders"]),
            faculty("Siwei Chen", title="Assistant Professor",
                    url="https://genes.uchicago.edu/siwei-chen",
                    keywords=["AI (Artificial Intelligence)", "Computational Biology", "Functional Genomics", "Statistical Genetics", "Systems Biology"]),
            ],
        },
        {
            "short": "MGCB",
            "name": "Department of Molecular Genetics and Cell Biology",
            "majors": ["Biological Sciences"],
            "directory_url": "https://mgcb.uchicago.edu/people/faculty",
            "faculty": [
            faculty("Richard G. Fehon", title="Professor",
                    url="https://mgcb.uchicago.edu/richard-g-fehon-phd",
                    keywords=["Cell signaling", "Development", "Epithelial polarity", "Genetics", "Hippo pathway", "Microscopy"]),
            faculty("Alexander J. Ruthenburg", title="Associate Professor",
                    url="https://mgcb.uchicago.edu/alexander-j-ruthenburg-phd",
                    keywords=["Biochemistry", "Chromatin", "Chromatin Associated RNA", "Chromatin Immunoprecipitation", "Epigenetic Process", "Epigenetics", "Epigenomics", "Genomics"]),
            faculty("David R. Kovar", title="Professor",
                    url="https://mgcb.uchicago.edu/david-r-kovar-phd",
                    keywords=["Cell Division", "Cell Polarity", "Cytoskeleton", "Self-organization", "Single Molecule Imaging", "TIRF Microscopy"]),
            faculty("Jean Greenberg", title="Professor",
                    url="https://mgcb.uchicago.edu/jean-greenberg-phd",
                    keywords=["induced systemic resistance", "plant immunity", "Posttranslational Modifications", "Pseudomonas syringae", "systemic acquired resistance", "type III pathogen effector"]),
            faculty("Michael J. Rust", title="Professor",
                    url="https://mgcb.uchicago.edu/michael-j-rust-phd",
                    keywords=["Bacteria", "Biochemistry", "Cell Division", "Circadian Rhythms", "Mathematical Model", "Microscopy, Fluorescence"]),
            faculty("Sally Horne-Badovinac", title="Professor",
                    url="https://mgcb.uchicago.edu/sally-horne-badovinac-phd",
                    keywords=["Basement Membrane", "Collective Cell Migration", "Drosophila", "Epithelial Morphogenesis", "Intercellular Signaling", "Membrane Trafficking"]),
            faculty("Edwin M. Munro", title="Professor",
                    url="https://mgcb.uchicago.edu/edwin-m-munro-phd",
                    keywords=["actomyosin contractility", "cell polarity", "computational biology", "morphogenesis"]),
            faculty("Jocelyn Malamy", title="Associate Professor",
                    url="https://mgcb.uchicago.edu/jocelyn-malamy-phd",
                    keywords=["Arabidopsis thaliana", "jellyfish", "Phloem", "regeneration", "wound healing"]),
            faculty("Jonathan Prescott Staley", title="Chair",
                    url="https://mgcb.uchicago.edu/jonathan-prescott-staley-phd",
                    keywords=["ATPase", "Baker's Yeast", "Brewer's Yeast", "cotranscriptional processes", "DEAD-box RNA Helicases", "DEAH-box RNA helicase", "Exon", "Gene Expression Regulation"]),
            faculty("Elizabeth S. Heckscher", title="Associate Professor",
                    url="https://mgcb.uchicago.edu/elizabeth-s-heckscher-phd",
                    keywords=["Drosophila", "Evolution, Biological", "Lineage, Cell", "Motor Activity", "Neuron", "Sensory Function", "Stem Cell", "Transcription Factor"]),
            faculty("David Pincus", title="Associate Professor",
                    url="https://mgcb.uchicago.edu/david-pincus-phd",
                    keywords=["chaperone", "Hsf1", "Hsp40", "Hsp70", "Hsp90", "kinase", "Phosphorylation", "proteostasis"]),
            faculty("Michael A. Glotzer", title="Professor",
                    url="https://mgcb.uchicago.edu/michael-glotzer-phd",
                    keywords=["Cell Polarity", "Centralspindlin", "Cytokinesis", "Optogenetics", "Rho GTPases"]),
            faculty("Edwin L. Ferguson", title="Professor",
                    url="https://mgcb.uchicago.edu/edwin-l-ferguson-phd",
                    keywords=["Development and Evolution", "Drosophila", "Embryogenesis", "Intercellular Signaling", "Pattern Formation", "Stem Cell Biology"]),
            faculty("Douglas K. Bishop", title="Professor",
                    url="https://mgcb.uchicago.edu/douglas-k-bishop-phd"),
            faculty("Benjamin Glick", title="Professor",
                    url="https://mgcb.uchicago.edu/benjamin-glick-phd",
                    keywords=["Membranes, Cell", "Microscopy, Electron", "Microscopy, Fluorescence", "Organelles"]),
            faculty("Stephen J. Kron", title="Professor",
                    url="https://mgcb.uchicago.edu/stephen-j-kron-md-phd",
                    keywords=["Checkpoints, Cell Cycle", "DNA Repair", "Immunotherapy", "Radiotherapy", "Senescence, Cell", "Systems Biology"]),
            faculty("Heng-Chi Lee", title="Associate Professor",
                    url="https://mgcb.uchicago.edu/heng-chi-lee-phd",
                    keywords=["C. elegans", "Chromatin", "Epigenetics", "Genome Instability", "Infertility", "RNA Processing, Post Transcriptional", "Small Non-Coding RNA"]),
            faculty("Sampriti Mukherjee", title="Assistant Professor",
                    url="https://mgcb.uchicago.edu/sampriti-mukherjee-phd",
                    keywords=["Bacterial genetics", "Bacterial sensory signal transduction", "Biofilms", "Genomics", "Microscopy", "Molecular biology"]),
            faculty("Robert Carrillo", title="Associate Professor",
                    url="https://mgcb.uchicago.edu/robert-carrillo-phd",
                    keywords=["Cell Surface Proteins", "Cell-cell interactions", "Drosophila melanogaster", "Neural circuit function", "Neural circuits", "Neural development", "Neurobiology, Cellular", "Neurobiology, Molecular"]),
            faculty("Margaret L. Gardel", title="Professor",
                    url="https://mgcb.uchicago.edu/margaret-l-gardel-phd",
                    keywords=["Adhesion, Cell", "Cell Mechanics", "Cytoskeleton, Actin", "Migration, Cell", "Myosin"]),
            faculty("Noah Mitchell", title="Assistant Professor",
                    url="https://mgcb.uchicago.edu/noah-mitchell-phd",
                    keywords=["Biophysics", "Cell Biology", "Developmental Biology", "Mathematical Models", "Morphogenesis", "Physics of Living Systems", "Soft Matter Physics", "Tissue Mechanics"]),
            faculty("Jarrett SMITH", title="Assistant Professor",
                    url="https://mgcb.uchicago.edu/jarrett-smith"),
            ],
        },
        {
            "short": "BMB",
            "name": "Department of Biochemistry and Molecular Biology",
            "majors": ["Biological Chemistry", "Biological Sciences", "Chemistry"],
            "directory_url": "https://biochem.uchicago.edu/people/our-faculty",
            "faculty": [
            faculty("Robert J. Keenan", title="Professor",
                    url="https://biochem.uchicago.edu/robert-j-keenan-phd",
                    keywords=["Biochemical reconstitution", "Cell biology", "Endoplasmic Reticulum", "Membrane protein biogenesis and quality control", "Structural biology, cryo-EM"]),
            faculty("Anthony Kossiakoff", title="Otho S.A. Sprague Distinguished Service Professor",
                    url="https://biochem.uchicago.edu/anthony-kossiakoff-phd",
                    keywords=["Antibody Engineering", "Membrane Proteins", "Phage Display Mutagenesis", "Protein Engineering", "Structural Biology", "T-cell Engineering"]),
            faculty("Tao Pan", title="Professor",
                    url="https://biochem.uchicago.edu/tao-pan-phd",
                    keywords=["epitranscriptomics", "Functional genomics", "Microbiome", "RNA modification", "tRNA"]),
            faculty("Benoit Roux", title="Amgen Professor",
                    url="https://biochem.uchicago.edu/benoit-roux-msc-phd"),
            faculty("Rama Ranganathan", title="Joseph Regenstein Professor",
                    url="https://biochem.uchicago.edu/rama-ranganathan-md-phd",
                    keywords=["adaptation", "cellular", "computational and statistical models", "Evolution", "protein", "protein folding", "statistical analysis"]),
            faculty("Ronald S. Rock", title="Associate Professor",
                    url="https://biochem.uchicago.edu/ronald-s-rock-phd",
                    keywords=["Actin Cytoskeleton", "Myosins", "Optical Tweezers", "Single Molecule", "Structural Biology", "TIRF Microscopy"]),
            faculty("Erin June Adams", title="Chair",
                    url="https://biochem.uchicago.edu/erin-june-adams-phd",
                    keywords=["biochemistry", "MHC (nonclassical and MHC-like)", "Molecular Immunology", "structural biology", "T Cells"]),
            faculty("Marvin W. Makinen", title="Professor",
                    url="https://biochem.uchicago.edu/marvin-w-makinen-md-phd"),
            faculty("Eduardo Perozo", title="Lillian Eichelberger Cannon Professor",
                    url="https://biochem.uchicago.edu/eduardo-perozo-phd"),
            faculty("Joseph A. Piccirilli", title="Professor",
                    url="https://biochem.uchicago.edu/joseph-piccirilli-phd"),
            faculty("Tobin R. Sosnick", title="William B. Graham Professor",
                    url="https://biochem.uchicago.edu/tobin-r-sosnick-phd",
                    keywords=["disordered proteins", "Hydrogen exchange", "Membrane Proteins", "NMR Spectroscopy", "optogenetics", "Protein Folding", "Simulations, Molecular Dynamics", "small-angle scattering"]),
            faculty("D. Allan Drummond", title="Associate Professor",
                    url="https://biochem.uchicago.edu/d-allan-drummond-phd",
                    keywords=["Cell Biology", "Heat Shock Response", "Molecular Evolution", "Phase Separation", "Stress Response, Physiological"]),
            faculty("Phoebe A. Rice", title="Professor",
                    url="https://biochem.uchicago.edu/phoebe-rice-phd",
                    keywords=["Biochemistry", "Cryo electron Microscopy", "DNA recombination", "Mobile Genetic Elements", "MRSA", "Staphylococcus aureus", "Xray Crystallography"]),
            faculty("Jingyi Fei", title="Associate Professor",
                    url="https://biochem.uchicago.edu/jingyi-fei-phd"),
            faculty("Demet Arac-Ozkan", title="Associate Professor",
                    url="https://biochem.uchicago.edu/demet-arac-ozkan-phd",
                    keywords=["Brain", "Cell Surface Proteins", "cortex development", "Crystallography, X Ray", "Electron Microscopy", "G Protein Coupled Receptors", "Membrane Proteins", "multicellularity"]),
            faculty("Minglei Zhao", title="Associate Professor",
                    url="https://biochem.uchicago.edu/minglei-zhao-phd",
                    keywords=["AAA+ ATPase", "p97", "Ubiquitination", "Vault RNP Particle"]),
            faculty("Engin Ozkan", title="Associate Professor",
                    url="https://biochem.uchicago.edu/engin-ozkan-phd",
                    keywords=["Axon guidance", "Cell surface receptors", "Cryo-electron microscopy", "Development", "Protein structure", "Protein-protein interactions", "Synapse formation", "X-ray crystallography"]),
            faculty("Cassandra Hayne", title="Assistant Professor",
                    url="https://biochem.uchicago.edu/cassandra-hayne-phd",
                    keywords=["Biochemistry", "Cell and Molecular Biology", "Cryo-Electron Microscopy", "Neurodegenerative Diseases", "Neurodevelopmental Diseases", "RNA", "RNA Processing, Post-Transcriptional", "tRNA"]),
            faculty("Marcos Sotomayor", title="Professor",
                    url="https://biochem.uchicago.edu/marcos-sotomayor-phd"),
            ],
        },
        {
            "short": "OBA",
            "name": "Department of Organismal Biology and Anatomy",
            "majors": ["Biological Sciences", "Neuroscience"],
            "directory_url": "https://biologicalsciences.uchicago.edu/our-faculty",
            "faculty": [
            faculty("Melina E Hale", title="William Rainey Harper Professor",
                    url="https://profiles.uchicago.edu/profiles/profile/37051"),
            faculty("Urs C. Schmidt-Ott", title="Professor",
                    url="https://profiles.uchicago.edu/profiles/profile/38358",
                    keywords=["Axis Specification", "Development and Evolution", "Drosophila", "Embryogenesis", "Gene Network", "Genomics", "Mosquito", "Pattern Formation"]),
            faculty("Victoria E. Prince", title="Professor",
                    url="https://profiles.uchicago.edu/profiles/profile/37123"),
            faculty("Zeray Alemseged", title="Donald N. Pritzker Professor",
                    url="https://profiles.uchicago.edu/profiles/profile/8725711"),
            faculty("Zhe-Xi Luo", title="Mila Pierce-Rhoads Professor",
                    url="https://profiles.uchicago.edu/profiles/profile/37171",
                    keywords=["Evolutionary Biology", "Paleontology", "Mammalian Evolution", "Vertebrate Evolutionary Development"]),
            faculty("Neil H. Shubin", title="Robert R. Bensley Distinguished Service Professor",
                    url="https://profiles.uchicago.edu/profiles/profile/38183"),
            faculty("Michael I. Coates", title="Chair",
                    url="https://profiles.uchicago.edu/profiles/profile/37831"),
            faculty("Callum F. Ross", title="Professor",
                    url="https://profiles.uchicago.edu/profiles/profile/38637"),
            faculty("Mark Westneat", title="Professor",
                    url="https://profiles.uchicago.edu/profiles/profile/38515"),
            faculty("Nipam Patel", title="Professor",
                    url="https://profiles.uchicago.edu/profiles/profile/2119198"),
            faculty("Paul Sereno", title="Professor",
                    url="https://profiles.uchicago.edu/profiles/profile/36802",
                    keywords=["dinosaurs", "Sahara", "ancient humans", "exploration", "discovery", "engagement"]),
            faculty("Daniel Margoliash", title="Professor",
                    url="https://profiles.uchicago.edu/profiles/profile/37294",
                    keywords=["Behavior", "Development", "Systems", "Circuits", "Cellular"]),
            faculty("Heather Marlow", title="Assistant Professor",
                    url="https://profiles.uchicago.edu/profiles/profile/15493674",
                    keywords=["Genomics", "Evolution", "Regulatory Networks"]),
            faculty("Nicholas G. Hatsopoulos", title="A.J. Carlson Professor",
                    url="https://profiles.uchicago.edu/profiles/profile/39039"),
            faculty("Stephanie Palmer", title="Associate Professor",
                    url="https://profiles.uchicago.edu/profiles/profile/38337"),
            faculty("Zewdi Tsegai", title="Assistant Professor",
                    url="https://profiles.uchicago.edu/profiles/profile/31923676"),
            faculty("Jasmine Nirody", title="Assistant Professor",
                    url="https://profiles.uchicago.edu/profiles/profile/31923674"),
            faculty("Matthew Kaufman", title="Assistant Professor",
                    url="https://profiles.uchicago.edu/profiles/profile/13441987",
                    keywords=["Calcium Imaging", "Computational Modeling", "Decision Making", "Dimensionality Reduction", "Dynamical Systems", "Motor Control", "Mouse", "Population Activity"]),
            faculty("Amy Herbert", title="Assistant Professor",
                    url="https://profiles.uchicago.edu/profiles/profile/56816020"),
            ],
        },
        {
            "short": "PBHS",
            "name": "Department of Public Health Sciences",
            "majors": ["Public Policy Studies", "Data Science", "Statistics"],
            "directory_url": "https://publichealth.bsd.uchicago.edu/",
            "faculty": [
            faculty("Lin Chen", title="Professor",
                    url="https://profiles.uchicago.edu/profiles/profile/38501",
                    keywords=["big data", "integrative genomics", "statistical methods", "software development"]),
            faculty("R. Tamara Konetzka", title="Louis Block Professor",
                    url="https://profiles.uchicago.edu/profiles/profile/37087",
                    keywords=["Health Economics", "Long-Term Care", "Medicaid", "Medicare", "Post-Acute Care"]),
            faculty("Habibul Ahsan", title="Louis Block Distinguished Service Professor",
                    url="https://profiles.uchicago.edu/profiles/profile/37251",
                    keywords=["Disease Prevention", "Early Diagnosis of Cancer", "Global Health", "Precision Medicine", "Risk Assessment"]),
            faculty("Dezheng Huo", title="Professor",
                    url="https://profiles.uchicago.edu/profiles/profile/37017",
                    keywords=["Breast Cancer", "Genetic Epidemiology", "Genetics", "Population", "Health Disparity", "Outcomes Research", "Risk Prediction"]),
            faculty("Diane Sperling Lauderdale", title="Louis Block Distinguished Service Professor",
                    url="https://profiles.uchicago.edu/profiles/profile/38924",
                    keywords=["Aging", "Demographic", "Disparities", "Health Status", "Epidemiology", "Sleep"]),
            faculty("Donald Hedeker", title="Professor",
                    url="https://profiles.uchicago.edu/profiles/profile/2927290",
                    keywords=["ecological momentary assessment", "longitudinal data analysis", "mixed-effects models", "ordinal data"]),
            faculty("Loren Saulsberry", title="Assistant Professor",
                    url="https://profiles.uchicago.edu/profiles/profile/14781317",
                    keywords=["Cancer Prevention and Control", "Health Disparities", "Health Policy", "Health Services Research", "Pharmacogenomics", "Precision Medicine"]),
            faculty("Brandon L. Pierce", title="Chair",
                    url="https://profiles.uchicago.edu/profiles/profile/39150",
                    keywords=["Aging", "Arsenic", "Cancer", "Epigenetics", "gene regulation", "Gene-Environment Interaction", "Genetic Epidemiology", "Telomeres"]),
            faculty("James J. Dignam", title="Professor",
                    url="https://profiles.uchicago.edu/profiles/profile/37229",
                    keywords=["clinical trials", "competing risks", "health disparities in cancer", "modeling", "survival analysis"]),
            faculty("Brian Chih-Hung Chiu", title="Professor",
                    url="https://profiles.uchicago.edu/profiles/profile/37126",
                    keywords=["Epigenetics", "Health disparities", "Liquid biopsy", "Molecular epidemiology", "Multiple Myeloma", "Non-Hodgkin Lymphoma", "Translational population research"]),
            faculty("Yuan Ji", title="Professor",
                    url="https://profiles.uchicago.edu/profiles/profile/2927292"),
            faculty("Marcia Tan", title="Assistant Professor",
                    url="https://profiles.uchicago.edu/profiles/profile/14781316",
                    keywords=["Behavioral Sciences", "Health Disparities", "Minority Health", "Tobacco Cessation", "Weight Management"]),
            faculty("Aresha Martinez-Cardoso", title="Assistant Professor",
                    url="https://profiles.uchicago.edu/profiles/profile/14630620",
                    keywords=["Aging", "Demographic", "Demographic and Health Surveys", "Health Status", "Immigration and Emigration", "Latinos", "Migration", "Race"]),
            faculty("Harold Pollack", title="Helen Ross Professor",
                    url="https://profiles.uchicago.edu/profiles/profile/12760229"),
            faculty("Mei-Yin Chen Polley", title="Professor",
                    url="https://profiles.uchicago.edu/profiles/profile/18786504",
                    keywords=["biomarker reproducibility", "brain cancer", "breast cancer", "cancer biomarker", "clinical trials", "prognostic modeling"]),
            faculty("Prachi Sanghavi", title="Associate Professor",
                    url="https://profiles.uchicago.edu/profiles/profile/5478620",
                    keywords=["Burn injuries", "Fracking", "Healthcare quality measurement", "Long term care", "Low-value services", "Medicaid", "Medicare", "Pre-hospital care"]),
            faculty("Kavi Bhalla", title="Associate Professor",
                    url="https://profiles.uchicago.edu/profiles/profile/9913633",
                    keywords=["Burden of disease", "Global Health", "Injury prevention", "Road safety", "Traffic Accident"]),
            faculty("Eric Polley", title="Associate Professor",
                    url="https://profiles.uchicago.edu/profiles/profile/22565320",
                    keywords=["Assay Development", "Cancer Genomics", "Causal Inference", "Data Science", "Precision Medicine", "Prognostic Risk Models", "Risk Assessment"]),
            faculty("Jasmin Tiro", title="Professor",
                    url="https://profiles.uchicago.edu/profiles/profile/28934556",
                    keywords=["Behavioral Sciences", "Cancer Prevention and Control", "Disparities", "Healthcare", "Health Behavior Interventions"]),
            faculty("Joseph Dov Bruch", title="Assistant Professor",
                    url="https://profiles.uchicago.edu/profiles/profile/28934559",
                    keywords=["Financial Sector", "Health Policy", "Social Epidemiology"]),
            faculty("Betsy Q Cliff", title="Assistant Professor",
                    url="https://profiles.uchicago.edu/profiles/profile/28934554",
                    keywords=["Health economics", "Health policy", "Health insurance", "Consumer behavior"]),
            faculty("Kate Burrows", title="Assistant Professor",
                    url="https://profiles.uchicago.edu/profiles/profile/36891715",
                    keywords=["Climate change and health", "Environmental Health", "Environmental Justice", "Health Disparities", "Mental Health", "Natural Disasters"]),
            faculty("Rebekah Israel Cross", title="Assistant Professor",
                    url="https://profiles.uchicago.edu/profiles/profile/36891719",
                    keywords=["Child Health", "Critical Theory", "Housing", "Maternal Health", "Racism", "Urban Development"]),
            faculty("Wanwen Zeng", title="Assistant Professor",
                    url="https://profiles.uchicago.edu/profiles/profile/96508467"),
            ],
        },
        {
            "short": "MICRO",
            "name": "Department of Microbiology",
            "majors": ["Biological Sciences"],
            "directory_url": "https://microbiology.uchicago.edu/",
            "faculty": [
            faculty("Tatyana Golovkina", title="Professor",
                    url="https://profiles.uchicago.edu/profiles/profile/37082",
                    keywords=["viruses", "bacteria", "commensal microbes"]),
            faculty("Dominique Missiakas", title="Professor",
                    url="https://profiles.uchicago.edu/profiles/profile/37807",
                    keywords=["Animal Disease Models", "Antibodies", "Bacterial", "Bacterial pathogenesis", "Envelope assembly", "Gram Positive Bacteria", "Protein secretion"]),
            faculty("Glenn C. Randall", title="Professor",
                    url="https://profiles.uchicago.edu/profiles/profile/37535",
                    keywords=["dengue virus", "hepatitis C virus", "noroviruses", "virus-host interactions"]),
            faculty("Jueqi Chen", title="Assistant Professor",
                    url="https://profiles.uchicago.edu/profiles/profile/17338331",
                    keywords=["Biochemistry", "Fluorescence Microscopy", "Inflammation", "Innate Immunity", "Microbiology"]),
            faculty("Mark Mimee", title="Assistant Professor",
                    url="https://profiles.uchicago.edu/profiles/profile/17589333",
                    keywords=["Bacteriophage", "Bioengineering", "Host-Pathogen Interactions", "Microbiota", "Synthetic Biology"]),
            faculty("Sam Light", title="Neubauer Family Assistant Professor",
                    url="https://profiles.uchicago.edu/profiles/profile/18601347",
                    keywords=["Bacterial Pathogenesis", "Human Microbiome", "Microbial Genetics", "Protein Biochemistry"]),
            faculty("Laurie Comstock", title="Professor",
                    url="https://profiles.uchicago.edu/profiles/profile/23820259",
                    keywords=["Antimicrobial proteins", "Bacterial antagonism", "Bacterial interactions", "Bacteroidales", "Gut symbionts", "Microbiome", "Microbiota"]),
            faculty("Shabaana Khader", title="Chair",
                    url="https://profiles.uchicago.edu/profiles/profile/28934558"),
            faculty("Mohammed Kaplan", title="Assistant Professor",
                    url="https://profiles.uchicago.edu/profiles/profile/36292832"),
            faculty("Erin Green", title="Assistant Professor",
                    url="https://profiles.uchicago.edu/profiles/profile/37151120",
                    keywords=["Bacteria", "bacterial pathogenesis", "bacterial signal transduction", "gene regulation", "Proteostasis"]),
            faculty("Elias Gerrick", title="Assistant Professor",
                    url="https://profiles.uchicago.edu/profiles/profile/49423489",
                    keywords=["Diet", "Gut microbiota", "Host-microbe interactions", "Microbe-microbe interactions", "Protists"]),
            ],
        },
    ],
}


def fetch_and_normalize(deep: bool = True) -> list[dict]:
    """Wrapper bound to SCHOOL so refresh_all can call it like a collector."""
    return faculty_graph.fetch_and_normalize(SCHOOL, deep=deep)


def merge_into_processed(opps: list[dict]):
    return faculty_graph.merge_into_processed(opps)
