"""University of Chicago faculty config (via the faculty_graph engine).

Mechanism mix, verified Jul 2026 (per-department directory probes; raw HTML/JSON
snapshots reviewed by hand before selectors were pinned):

  * **Live scrape (8 departments).** CS (WordPress+FacetWP card grid, single
    page, per-profile "Focus Areas" enrich), the four PSD MixItUp directories
    (Statistics, Mathematics, Physics, Astronomy & Astrophysics -- same CMS,
    shared selector set, no emails on the listing), the two Drupal Views
    directories (Economics, Psychology -- paginated, emailed + interest-tagged
    cards), and PME (server-rendered card-spotlight grid, emailed + research
    topics via per-card taxonomy spans).
  * **Curated seeds from the sites' own JSON APIs (6 departments).** Chemistry's
    directory page and the five BSD department sites (Ecology & Evolution,
    Neurobiology, Human Genetics, Molecular Genetics & Cell Biology,
    Biochemistry & Molecular Biology) are JS-only shells; the shared BSD data
    endpoint (bsd-data.prod.uchicago.edu/api/faculty_index) additionally
    requires a uchicago Referer header the engine doesn't send. Their rosters
    were pulled from the APIs (chemistry: live-ucchem.pantheonsite.io/api/
    faculty_index) in Jul 2026 and frozen as curated ``faculty(...)`` seeds --
    the Michigan model. Migrate to live ``json_dir`` blocks if the engine grows
    per-source headers + relative-link joins.

BSD department chairs carry the literal title "Chair" (Carole Ober, David
Freedman, ...), not "...Professor", so the BSD dumps used a drop-only rank
filter -- requiring "professor" would have dropped every chair. Emails are
absent from all six API rosters and from the PSD MixItUp listings; records
there ship as linked, keyworded cold-email targets (confidence 0.5), like the
UW Arts & Sciences departments.

Single source ("uchicago_faculty") across all departments (the UIUC model); the
department rides on each record's ``department`` field, and ids are namespaced
by department short-code so they never collide. Audience "unknown" (per-prof
openness).
"""

from __future__ import annotations

from .. import faculty_graph
from ..faculty_graph import faculty


# The four PSD departments (Statistics, Mathematics, Physics, Astronomy) share
# one custom-CMS "MixItUp" directory: a single server-rendered <li class="mix
# <role>"> list per site, filtered client-side. The role classes differ per
# site (math isolates ladder faculty as "professors"; the others mix ranks
# inside "faculty"), so the card selector and title filter are parameters.
def _psd(short: str, name: str, majors: list[str], url: str, *,
         card: str = "li.mix.faculty", ladder_filter: dict | None = None) -> dict:
    return {"short": short, "name": name, "majors": majors, "directory_url": url,
            "scrape": {"url": url,
                       "selectors": {"card": card,
                                     "name": ".people_content h3 span",
                                     "link": "a",
                                     "title": ".people_content h3 b"},
                       **({"ladder_filter": ladder_filter} if ladder_filter else {})}}


# Economics and Psychology share the university's Drupal Views directory theme:
# paginated ?page=N views with emailed, interest-tagged cards. Emeriti mix into
# the Economics view (Psychology keeps them on a separate URL); one drop rule
# covers both.
def _views(short: str, name: str, majors: list[str], url: str, *,
           max_pages: int) -> dict:
    return {"short": short, "name": name, "majors": majors, "directory_url": url,
            "scrape": {"url": url,
                       "selectors": {"card": "div.views-row",
                                     "name": "h2.no-tags > a",
                                     "link": "h2.no-tags > a",
                                     "title": "div.bio-subtitle",
                                     "email": "div.bio-email a",
                                     "research": "div.bio-interest"},
                       "paginate": {"param": "page", "start": 1, "max": max_pages},
                       "ladder_filter": {"drop": r"emerit"}}}


SCHOOL: dict = {
    "school_slug": "uchicago",
    "source": "uchicago_faculty",
    "organization": "University of Chicago",
    "location": "Chicago, IL",
    "id_prefix": "uchicago",
    "audience": "unknown",
    "work_auth_notes": (
        "External campus (University of Chicago) -- work authorization depends "
        "on the arrangement; ask the professor."
    ),
    "departments": [
        {
            "short": "CS",
            "name": "Department of Computer Science",
            "majors": ["Computer Science", "Data Science"],
            "directory_url": "https://cs.uchicago.edu/people/uchicago-faculty/full-time-faculty/",
            "scrape": {
                "url": "https://cs.uchicago.edu/people/uchicago-faculty/full-time-faculty/",
                "selectors": {
                    "card": "div.card.card--person",
                    "name": "h3.card__title",
                    "link": "a.card__url",
                    "title": "div.card__position",
                },
                "ladder_filter": {
                    "require": r"professor",
                    "drop": r"emerit|clinical|instructional|research (assistant|associate) professor|masters",
                },
                # The listing carries name/title only; each profile keeps a
                # "<strong>Focus Areas:</strong> <em>A, B</em>" block (gated
                # per-profile enrich, OFE_ENRICH_PROFILES=1).
                "profile_enrich": {
                    "research_html_re": r"Focus Areas?:\s*</strong>\s*<em>(.*?)</em>",
                    "throttle": 1.0,
                },
            },
        },
        _psd("STAT", "Department of Statistics",
             ["Statistics", "Data Science", "Computational and Applied Mathematics"],
             "https://stat.uchicago.edu/people/",
             ladder_filter={"require": r"professor",
                            "drop": r"emerit|instructional|part-time|visiting|lecturer"}),
        _psd("MATH", "Department of Mathematics",
             ["Mathematics", "Computational and Applied Mathematics"],
             "https://mathematics.uchicago.edu/people/",
             # ladder faculty already isolated by the "professors" role class;
             # instructional/visiting/Dickson instructors carry other classes.
             card="li.mix.professors",
             ladder_filter={"drop": r"emerit"}),
        _psd("PHYS", "Department of Physics",
             ["Physics", "Astrophysics"],
             "https://physics.uchicago.edu/people/",
             ladder_filter={"require": r"professor",
                            "drop": r"emerit|lecturer|instructional|research professor|part-time|scientist|visiting"}),
        _psd("ASTRO", "Department of Astronomy and Astrophysics",
             ["Astrophysics", "Physics"],
             "https://astrophysics.uchicago.edu/people/",
             # the site splits research-faculty/emeriti into their own role
             # classes; within "faculty" the chair/deputy-chair titles carry no
             # "Professor" word, so drop-only.
             ladder_filter={"drop": r"emerit|research professor|lecturer|instructional|part-time|scientist|visiting|postdoc"}),
        _views("ECON", "Kenneth C. Griffin Department of Economics",
               ["Economics"],
               "https://economics.uchicago.edu/people/faculty", max_pages=6),
        _views("PSYCH", "Department of Psychology",
               ["Psychology"],
               "https://psychology.uchicago.edu/people/faculty", max_pages=5),
        {
            "short": "PME",
            "name": "Pritzker School of Molecular Engineering",
            "majors": ["Molecular Engineering"],
            "directory_url": "https://pme.uchicago.edu/faculty-research/faculty-directory",
            "scrape": {
                "url": "https://pme.uchicago.edu/faculty-research/faculty-directory",
                "selectors": {
                    "card": "div.card-spotlight.node--type-faculty",
                    "name": "a.card-spotlight__title",
                    "link": "a.card-spotlight__title",
                    "title": "div.card-spotlight__position",
                    "email": "div.card-spotlight__email a[href^='mailto:']",
                    # scholarly-interest taxonomy spans; the .eyebrow child is
                    # the "Research & Scholarly Interests" label, not a topic.
                    "research_items": "div.card-spotlight__research-scholar-intrest span:not(.eyebrow)",
                },
                "ladder_filter": {"drop": r"emerit"},
            },
        },
        {
            "short": "CHEM",
            "name": "Department of Chemistry",
            "majors": ["Chemistry", "Biological Chemistry"],
            "directory_url": "https://chemistry.uchicago.edu/faculty",
            "faculty": [
            faculty("Paul Alivisatos", title="President of the University of Chicago; John D. MacArthur Distinguished Service Professor",
                    url="https://chemistry.uchicago.edu/paul-alivisatos",
                    keywords=["Materials Chemistry", "Physical Chemistry"]),
            faculty("Chuan He", title="John T. Wilson Distinguished Service Professor",
                    url="https://chemistry.uchicago.edu/chuan-he",
                    keywords=["Chemical Biology", "Inorganic Chemistry"]),
            faculty("Hening Lin", title="Professor",
                    url="https://chemistry.uchicago.edu/hening-lin",
                    keywords=["Chemical Biology", "Organic Chemistry"]),
            faculty("Michael Hopkins", title="Professor",
                    url="https://chemistry.uchicago.edu/michael-hopkins",
                    keywords=["Materials Chemistry", "Inorganic Chemistry"]),
            faculty("John Anderson", title="Professor and Associate Chair",
                    url="https://chemistry.uchicago.edu/john-anderson",
                    keywords=["Inorganic Chemistry", "Catalysis", "Materials Chemistry"]),
            faculty("Sarah King", title="Assistant Professor of Chemistry",
                    url="https://chemistry.uchicago.edu/sarah-king",
                    keywords=["Physical Chemistry", "Materials Chemistry"]),
            faculty("Bryan Dickinson", title="Professor",
                    url="https://chemistry.uchicago.edu/bryan-dickinson",
                    keywords=["Chemical Biology"]),
            faculty("Aaron Dinner", title="Professor",
                    url="https://chemistry.uchicago.edu/aaron-dinner",
                    keywords=["Biophysics", "Theoretical Chemistry", "Physical Chemistry"]),
            faculty("Greg Engel", title="Professor",
                    url="https://chemistry.uchicago.edu/greg-engel",
                    keywords=["Biophysics", "Physical Chemistry", "Materials Chemistry"]),
            faculty("Andrew Ferguson", title="Professor of Chemistry, Professor of Molecular Engineering, Vice Dean for Education and Outreach in the Pritzker School of Molecular Engineering",
                    url="https://chemistry.uchicago.edu/andrew-ferguson",
                    keywords=["Physical Chemistry", "Biophysics", "Theoretical Chemistry"]),
            faculty("Giulia Galli", title="Liew Family Professor",
                    url="https://chemistry.uchicago.edu/giulia-galli",
                    keywords=["Theoretical Chemistry", "Physical Chemistry"]),
            faculty("Philippe Guyot-Sionnest", title="Professor",
                    url="https://chemistry.uchicago.edu/philippe-guyot-sionnest",
                    keywords=["Materials Chemistry", "Physical Chemistry"]),
            faculty("Guangbin Dong", title="Weldon G. Brown Professor",
                    url="https://chemistry.uchicago.edu/guangbin-dong",
                    keywords=["Organic Chemistry", "Catalysis"]),
            faculty("David Mazziotti", title="Professor",
                    url="https://chemistry.uchicago.edu/david-mazziotti",
                    keywords=["Theoretical Chemistry", "Physical Chemistry", "Biophysics"]),
            faculty("Raymond Moellering", title="Professor",
                    url="https://chemistry.uchicago.edu/raymond-moellering",
                    keywords=["Chemical Biology", "Organic Chemistry"]),
            faculty("Jiwoong Park", title="Professor and Chair",
                    url="https://chemistry.uchicago.edu/jiwoong-park",
                    keywords=["Materials Chemistry", "Physical Chemistry"]),
            faculty("Joseph Piccirilli", title="Professor",
                    url="https://chemistry.uchicago.edu/joseph-piccirilli",
                    keywords=["Chemical Biology", "Catalysis"]),
            faculty("Viresh Rawal", title="Professor",
                    url="https://chemistry.uchicago.edu/viresh-rawal",
                    keywords=["Catalysis", "Organic Chemistry"]),
            faculty("Benoît Roux", title="Professor",
                    url="https://chemistry.uchicago.edu/benoit-roux",
                    keywords=["Theoretical Chemistry", "Biophysics", "Physical Chemistry"]),
            faculty("Dmitri Talapin", title="Ernest DeWitt Burton Distinguished Service Professor",
                    url="https://chemistry.uchicago.edu/dmitri-talapin",
                    keywords=["Materials Chemistry", "Inorganic Chemistry"]),
            faculty("Yamuna Krishnan", title="Louis Block Professor of Chemistry and the College",
                    url="https://chemistry.uchicago.edu/yamuna-krishnan",
                    keywords=["Chemical Biology", "Biophysics", "Organic Chemistry"]),
            faculty("Mark Levin", title="Professor",
                    url="https://chemistry.uchicago.edu/mark-levin",
                    keywords=["Organic Chemistry", "Catalysis", "Inorganic Chemistry"]),
            faculty("Wenbin Lin", title="James Franck Professor of Chemistry",
                    url="https://chemistry.uchicago.edu/wenbin-lin",
                    keywords=["Materials Chemistry", "Catalysis", "Inorganic Chemistry", "Chemical Biology"]),
            faculty("Weixin Tang", title="Associate Professor",
                    url="https://chemistry.uchicago.edu/weixin-tang",
                    keywords=["Chemical Biology", "Biophysics", "Organic Chemistry"]),
            faculty("Bozhi Tian", title="Professor",
                    url="https://chemistry.uchicago.edu/bozhi-tian",
                    keywords=["Biophysics", "Materials Chemistry", "Inorganic Chemistry", "Physical Chemistry"]),
            faculty("Andrei Tokmakoff", title="Henry G. Gale Distinguished Service Professor",
                    url="https://chemistry.uchicago.edu/andrei-tokmakoff",
                    keywords=["Biophysics", "Physical Chemistry"]),
            faculty("Stuart Rowan", title="Barry L. MacLean Professor for Molecular Engineering Innovation and Enterprise",
                    url="https://chemistry.uchicago.edu/stuart-rowan",
                    keywords=["Materials Chemistry", "Organic Chemistry"]),
            faculty("Norbert Scherer", title="Professor",
                    url="https://chemistry.uchicago.edu/norbert-scherer",
                    keywords=["Biophysics", "Materials Chemistry", "Physical Chemistry"]),
            faculty("Elena Shevchenko", title="Professor (Part-time)",
                    url="https://chemistry.uchicago.edu/elena-shevchenko",
                    keywords=["Catalysis", "Inorganic Chemistry", "Materials Chemistry", "Physical Chemistry"]),
            faculty("Suri Vaikuntanathan", title="Professor",
                    url="https://chemistry.uchicago.edu/suri-vaikuntanathan",
                    keywords=["Biophysics", "Theoretical Chemistry", "Physical Chemistry"]),
            faculty("Steven Sibener", title="Carl William Eisendrath Distinguished Service Professor",
                    url="https://chemistry.uchicago.edu/steven-j-sibener",
                    keywords=["Biophysics", "Materials Chemistry", "Physical Chemistry"]),
            faculty("Scott Snyder", title="Professor",
                    url="https://chemistry.uchicago.edu/scott-snyder",
                    keywords=["Chemical Biology", "Organic Chemistry"]),
            faculty("Jack W. Szostak", title="University Professor",
                    url="https://chemistry.uchicago.edu/jack-w-szostak",
                    keywords=["Chemical Biology", "Biophysics", "Organic Chemistry", "Physical Chemistry"]),
            faculty("Gregory A. Voth", title="Haig P. Papazian Distinguished Service Professor",
                    url="https://chemistry.uchicago.edu/gregory-a-voth",
                    keywords=["Biophysics", "Materials Chemistry", "Theoretical Chemistry", "Physical Chemistry"]),
            faculty("Anna Wuttig", title="Neubauer Family Assistant Professor",
                    url="https://chemistry.uchicago.edu/anna-wuttig",
                    keywords=["Catalysis", "Organic Chemistry", "Inorganic Chemistry", "Materials Chemistry"]),
            faculty("Jie Zhou", title="Assistant Professor",
                    url="https://chemistry.uchicago.edu/jie-zhou",
                    keywords=["Chemical Biology"]),
            faculty("Hannah Lant", title="Assistant Instructional Professor",
                    url="https://chemistry.uchicago.edu/hannah-lant-phd",
                    keywords=["Inorganic Chemistry", "Chemical Education"]),
            faculty("Shaunna McLeod", title="Assistant Instructional Professor",
                    url="https://chemistry.uchicago.edu/shaunna-mcleod",
                    keywords=["Chemical Education"]),
            faculty("Dipti Jasrasaria", title="Assistant Professor",
                    url="https://chemistry.uchicago.edu/dipti-jasrasaria",
                    keywords=["Theoretical Chemistry", "Physical Chemistry", "Materials Chemistry"]),
            faculty("Alex Cusumano", title="Assistant Professor",
                    url="https://chemistry.uchicago.edu/alex-cusumano",
                    keywords=["Organic Chemistry", "Catalysis", "Computational Chemistry"]),
            ],
        },
        {
            "short": "ECEV",
            "name": "Department of Ecology and Evolution",
            "majors": ["Biological Sciences", "Environmental Science"],
            "directory_url": "https://ecologyandevolution.uchicago.edu/people/faculty",
            "faculty": [
            faculty("John Timothy Wootton", title="Professor",
                    url="https://ecologyandevolution.uchicago.edu/john-timothy-wootton-phd",
                    keywords=["Avian Ecology", "Community Ecology", "Conservation", "Ecological Networks", "Ecosystems", "Environmental Imact", "Experimental Community Ecology", "Food Web"]),
            faculty("Joseph Thornton", title="Professor",
                    url="https://ecologyandevolution.uchicago.edu/joseph-thornton-phd",
                    keywords=["Biochemistry", "Evolution", "Evolution, Genetic", "Evolutionary biochemistry", "Molecular Evolution", "Phylogenetics"]),
            faculty("Sarah E. Cobey", title="Professor",
                    url="https://ecologyandevolution.uchicago.edu/sarah-e-cobey-phd",
                    keywords=["B cells", "coevolution", "infectious disease dynamics", "influenza", "mathematical modeling", "vaccination"]),
            faculty("Trevor D. Price", title="Professor",
                    url="https://ecologyandevolution.uchicago.edu/trevor-d-price-phd",
                    keywords=["color vision in birds", "India's biodiversity", "Macroecology", "speciation"]),
            faculty("Luis Bettencourt", title="Professor",
                    url="https://ecologyandevolution.uchicago.edu/luis-bettencourt-phd",
                    keywords=["Cities", "Complex Systems", "Epidemiology", "Evolutionary Dynamics", "Learning", "Networks", "Social Processes and Institutions", "Statistical Theory"]),
            faculty("Manyuan Long", title="Edna K. Papazian Distinguished Service Professor",
                    url="https://ecologyandevolution.uchicago.edu/manyuan-long-phd"),
            faculty("Gregory Dwyer", title="Professor",
                    url="https://ecologyandevolution.uchicago.edu/gregory-dwyer-phd",
                    keywords=["Climate Change", "Eco-evolutionary dynamics", "Host-Pathogen Interactions", "Mathematical ecoloty", "Quantitative Ecology", "Statistical Computing"]),
            faculty("Catherine Pfister", title="Professor",
                    url="https://ecologyandevolution.uchicago.edu/catherine-pfister-phd"),
            faculty("Marcus R. Kronforst", title="Professor",
                    url="https://ecologyandevolution.uchicago.edu/marcus-r-kronforst-phd",
                    keywords=["adaptation", "evolutionary genomics", "population genetics", "speciation"]),
            faculty("Stefano Allesina", title="Chair",
                    url="https://ecologyandevolution.uchicago.edu/stefano-allesina-phd",
                    keywords=["Community Ecology", "Dynamical Systems", "Food Webs", "Networks, Ecological", "Theoretical Ecology"]),
            faculty("Seppe Kuehn", title="Associate Professor",
                    url="https://ecologyandevolution.uchicago.edu/seppe-kuehn-phd"),
            faculty("Matthias Steinruecken", title="Associate Professor",
                    url="https://ecologyandevolution.uchicago.edu/matthias-steinruecken-phd",
                    keywords=["Mathematical Biology", "Population Genetics", "Statistical Genetics"]),
            faculty("Pavitra Muralidhar", title="Assistant Professor",
                    url="https://ecologyandevolution.uchicago.edu/pavitra-muralidhar-phd"),
            faculty("Carl Veller", title="Assistant Professor",
                    url="https://ecologyandevolution.uchicago.edu/carl-veller-phd"),
            faculty("Julia Kreiner", title="Assistant Professor",
                    url="https://ecologyandevolution.uchicago.edu/julia-kreiner-phd"),
            faculty("Dakota McCoy", title="Assistant Professor",
                    url="https://ecologyandevolution.uchicago.edu/dakota-mccoy-phd"),
            faculty("Lauren Carley", title="Assistant Professor",
                    url="https://ecologyandevolution.uchicago.edu/lauren-carley",
                    keywords=["Adaptation", "Chemical ecology", "Evolutionary Ecology", "Species interactions"]),
            faculty("Rachel Moran", title="Assistant Professor",
                    url="https://ecologyandevolution.uchicago.edu/rachel-moran"),
            ],
        },
        {
            "short": "NEURO",
            "name": "Department of Neurobiology",
            "majors": ["Neuroscience", "Biological Sciences"],
            "directory_url": "https://neurobiology.uchicago.edu/our-faculty",
            "faculty": [
            faculty("John H.R. Maunsell", title="Albert D. Lasker Distinguished Service Professor",
                    url="https://neurobiology.uchicago.edu/john-hr-maunsell-phd"),
            faculty("David Freedman", title="Chair",
                    url="https://neurobiology.uchicago.edu/david-freedman-phd"),
            faculty("Peggy Mason", title="Professor",
                    url="https://neurobiology.uchicago.edu/peggy-mason-phd"),
            faculty("Clifton Warren Ragsdale", title="Professor",
                    url="https://neurobiology.uchicago.edu/clifton-warren-ragsdale-phd",
                    keywords=["Developmental Biology", "Evolutionary biology", "Neocortex", "Octopuses", "Regeneration", "Systems Neuroscience"]),
            faculty("Sangram S. Sisodia", title="Thomas A. Reynolds Sr. Family Professor",
                    url="https://neurobiology.uchicago.edu/sangram-s-sisodia-phd"),
            faculty("Paschalis Kratsios", title="Associate Professor",
                    url="https://neurobiology.uchicago.edu/paschalis-kratsios-phd",
                    keywords=["C.elegans genetics", "chromatin factors", "gene regulation", "Gene Regulatory Networks", "mouse genetics", "neuronal development", "Transcription Factors"]),
            faculty("Wei Wei", title="Professor",
                    url="https://neurobiology.uchicago.edu/wei-wei-phd"),
            faculty("Christian R. Hansel", title="Professor",
                    url="https://neurobiology.uchicago.edu/christian-r-hansel-phd",
                    keywords=["Cerebellum", "Intrinsic Plasticity", "Neocortex", "Purkinje cell", "Synaptic Plasticity"]),
            faculty("Jason Maclean", title="Professor",
                    url="https://neurobiology.uchicago.edu/jason-maclean-phd",
                    keywords=["Graph Theory", "Local Circuitry", "Machine Learning", "Motor Cortex", "Neocortex", "Somatosensory Cortex", "Visual Cortex"]),
            faculty("Ruth Anne Eatock", title="Professor",
                    url="https://neurobiology.uchicago.edu/ruth-anne-eatock-phd",
                    keywords=["Action Potentials", "Hair Cell, Vestibular", "Inner Ear", "Sensory Function", "Sensory Neurons", "Synaptic Transmission", "Voltage-Gated Calcium Channels", "Voltage-Gated Potassium Channels"]),
            faculty("S. Murray Sherman", title="Maurice Goldblatt Professor",
                    url="https://neurobiology.uchicago.edu/s-murray-sherman-phd",
                    keywords=["Cortex, Cerebral", "Lateral Geniculate Body", "Pulvinar", "Somatosensory Cortex", "Thalamus", "Ventral Posteromedial Thalamic Nucleus", "Vision", "Visual Cortex"]),
            faculty("William Green", title="Professor",
                    url="https://neurobiology.uchicago.edu/william-green-phd",
                    keywords=["Acetylcholine", "Acetylcholine Receptors, Nicotinic", "Cell Biology of Neurons", "Glutamate", "Glutamate Receptors, Ionotropic", "Nicotine", "Nicotine Addiction", "Synapses"]),
            faculty("Xiaoxi Zhuang", title="Professor",
                    url="https://neurobiology.uchicago.edu/xiaoxi-zhuang"),
            faculty("Brent Doiron", title="Heinrich Kluver Professor",
                    url="https://neurobiology.uchicago.edu/brent-doiron-phd"),
            faculty("Mark Sheffield", title="Associate Professor",
                    url="https://neurobiology.uchicago.edu/mark-sheffield-phd",
                    keywords=["2-photon", "contextual fear conditioning", "dendrites", "hippocampus", "learning", "memory", "neuromodulation", "optogenetics"]),
            faculty("Marlene Cohen", title="Professor",
                    url="https://neurobiology.uchicago.edu/marlene-cohen-phd"),
            faculty("Narayanan Kasthuri", title="Associate Professor",
                    url="https://neurobiology.uchicago.edu/narayanan-kasthuri-md"),
            faculty("Ramon Nogueira Manas", title="Assistant Professor",
                    url="https://neurobiology.uchicago.edu/ramon-nogueira-manas-phd"),
            faculty("Jorge Jaramillo", title="Assistant Professor",
                    url="https://neurobiology.uchicago.edu/jorge-jaramillo-phd"),
            faculty("Marcella Noorman", title="Assistant Professor",
                    url="https://neurobiology.uchicago.edu/marcella-noorman"),
            faculty("Anne-Marie Oswald", title="Associate Professor",
                    url="https://neurobiology.uchicago.edu/anne-marie-oswald"),
            faculty("Samuel Muscinelli", title="Assistant Professor",
                    url="https://neurobiology.uchicago.edu/samuel-muscinelli"),
            faculty("Lucas Pinto", title="Assistant Professor",
                    url="https://neurobiology.uchicago.edu/lucas-pinto"),
            faculty("Sumin Jang", title="Assistant Professor",
                    url="https://neurobiology.uchicago.edu/sumin-jang",
                    keywords=["Human Development", "Motor Neuron Disease", "Motor Neurons", "Neural Progenitors", "Neurodevelopment"]),
            faculty("Julia Cox", title="Assistant Professor",
                    url="https://neurobiology.uchicago.edu/julia-cox"),
            ],
        },
        {
            "short": "HG",
            "name": "Department of Human Genetics",
            "majors": ["Biological Sciences"],
            "directory_url": "https://genes.uchicago.edu/people/our-faculty",
            "faculty": [
            faculty("Xin He", title="Professor",
                    url="https://genes.uchicago.edu/xin-he-phd",
                    keywords=["Cancer genomics", "Computational biology", "Gene regulation", "Psychiatric genetics", "Statistical genetics"]),
            faculty("John Novembre", title="Professor",
                    url="https://genes.uchicago.edu/john-novembre-phd",
                    keywords=["Computational Biology", "Computational Statistics", "Data Science", "Genomics", "Human Genetics", "Molecular Evolution", "Population Genetics"]),
            faculty("Carole Ober", title="Chair",
                    url="https://genes.uchicago.edu/carole-ober-phd"),
            faculty("T. Conrad Gilliam", title="Marjorie I. and Bernard A. Mitchell Distinguished Service Professor",
                    url="https://genes.uchicago.edu/t-conrad-gilliam-phd"),
            faculty("Francois Spitz", title="Professor",
                    url="https://genes.uchicago.edu/francois-spitz-phd",
                    keywords=["Developmental Disorders", "Epigenomics", "Evolution, Genetic", "Gene Expression Regulation", "Gene Regulatory Networks", "Genomics"]),
            faculty("Jeremy Berg", title="Assistant Professor",
                    url="https://genes.uchicago.edu/jeremy-berg-phd",
                    keywords=["Complex Traits and Diseases", "Population Genetics", "Quantitative Genetics"]),
            faculty("Marcelo A. Nobrega", title="A.N. Pritzker Professor",
                    url="https://genes.uchicago.edu/marcelo-nobrega-md-phd"),
            faculty("Maanasa Raghavan", title="Neubauer Family Assistant Professor",
                    url="https://genes.uchicago.edu/maanasa-raghavan-phd",
                    keywords=["Ancient DNA", "Genomics", "Human Evolution", "Population and Evolutionary Genetics"]),
            faculty("Matthew Stephens", title="Professor",
                    url="https://genes.uchicago.edu/matthew-stephens"),
            faculty("Xiaochang Zhang", title="Associate Professor",
                    url="https://genes.uchicago.edu/xiaochang-zhang-phd",
                    keywords=["Alternative RNA Splicing", "Brain development and disorders", "Cell type specification", "Gene regulation"]),
            faculty("Zhuzhu Zhang", title="Assistant Professor",
                    url="https://genes.uchicago.edu/zhuzhu-zhang-phd",
                    keywords=["Brain development and disorders", "Epigenomics", "Gene Regulatory Networks", "Genetics", "Neuroscience", "Psychiatric disorders", "Single-cell genomics"]),
            faculty("Ronan O'Malley", title="Assistant Professor",
                    url="https://genes.uchicago.edu/ronan-omalley-phd"),
            faculty("Francesca Luca", title="Professor",
                    url="https://genes.uchicago.edu/francesca-luca-phd"),
            faculty("Daniela Del Gaudio", title="Professor",
                    url="https://genes.uchicago.edu/daniela-del-gaudio-phd"),
            faculty("Soma Das", title="Professor",
                    url="https://genes.uchicago.edu/soma-das-phd",
                    keywords=["Ataxia", "Exome sequencing", "Molecular Diagnostics", "Mutation detection", "Neurogenetic disorders"]),
            faculty("Siwei Chen", title="Assistant Professor",
                    url="https://genes.uchicago.edu/siwei-chen",
                    keywords=["AI (Artificial Intelligence)", "Computational Biology", "Functional Genomics", "Statistical Genetics", "Systems Biology"]),
            ],
        },
        {
            "short": "MGCB",
            "name": "Department of Molecular Genetics and Cell Biology",
            "majors": ["Biological Sciences"],
            "directory_url": "https://mgcb.uchicago.edu/people/faculty",
            "faculty": [
            faculty("Richard G. Fehon", title="Professor",
                    url="https://mgcb.uchicago.edu/richard-g-fehon-phd",
                    keywords=["Cell signaling", "Development", "Epithelial polarity", "Genetics", "Hippo pathway", "Microscopy"]),
            faculty("Alexander J. Ruthenburg", title="Associate Professor",
                    url="https://mgcb.uchicago.edu/alexander-j-ruthenburg-phd",
                    keywords=["Biochemistry", "Chromatin", "Chromatin Associated RNA", "Chromatin Immunoprecipitation", "Epigenetic Process", "Epigenetics", "Epigenomics", "Genomics"]),
            faculty("David R. Kovar", title="Professor",
                    url="https://mgcb.uchicago.edu/david-r-kovar-phd",
                    keywords=["Cell Division", "Cell Polarity", "Cytoskeleton", "Self-organization", "Single Molecule Imaging", "TIRF Microscopy"]),
            faculty("Jean Greenberg", title="Professor",
                    url="https://mgcb.uchicago.edu/jean-greenberg-phd",
                    keywords=["induced systemic resistance", "plant immunity", "Posttranslational Modifications", "Pseudomonas syringae", "systemic acquired resistance", "type III pathogen effector"]),
            faculty("Michael J. Rust", title="Professor",
                    url="https://mgcb.uchicago.edu/michael-j-rust-phd",
                    keywords=["Bacteria", "Biochemistry", "Cell Division", "Circadian Rhythms", "Mathematical Model", "Microscopy, Fluorescence"]),
            faculty("Sally Horne-Badovinac", title="Professor",
                    url="https://mgcb.uchicago.edu/sally-horne-badovinac-phd",
                    keywords=["Basement Membrane", "Collective Cell Migration", "Drosophila", "Epithelial Morphogenesis", "Intercellular Signaling", "Membrane Trafficking"]),
            faculty("Edwin M. Munro", title="Professor",
                    url="https://mgcb.uchicago.edu/edwin-m-munro-phd",
                    keywords=["actomyosin contractility", "cell polarity", "computational biology", "morphogenesis"]),
            faculty("Jocelyn Malamy", title="Associate Professor",
                    url="https://mgcb.uchicago.edu/jocelyn-malamy-phd",
                    keywords=["Arabidopsis thaliana", "jellyfish", "Phloem", "regeneration", "wound healing"]),
            faculty("Jonathan Prescott Staley", title="Chair",
                    url="https://mgcb.uchicago.edu/jonathan-prescott-staley-phd",
                    keywords=["ATPase", "Baker's Yeast", "Brewer's Yeast", "cotranscriptional processes", "DEAD-box RNA Helicases", "DEAH-box RNA helicase", "Exon", "Gene Expression Regulation"]),
            faculty("Elizabeth S. Heckscher", title="Associate Professor",
                    url="https://mgcb.uchicago.edu/elizabeth-s-heckscher-phd",
                    keywords=["Drosophila", "Evolution, Biological", "Lineage, Cell", "Motor Activity", "Neuron", "Sensory Function", "Stem Cell", "Transcription Factor"]),
            faculty("David Pincus", title="Associate Professor",
                    url="https://mgcb.uchicago.edu/david-pincus-phd",
                    keywords=["chaperone", "Hsf1", "Hsp40", "Hsp70", "Hsp90", "kinase", "Phosphorylation", "proteostasis"]),
            faculty("Michael A. Glotzer", title="Professor",
                    url="https://mgcb.uchicago.edu/michael-glotzer-phd",
                    keywords=["Cell Polarity", "Centralspindlin", "Cytokinesis", "Optogenetics", "Rho GTPases"]),
            faculty("Edwin L. Ferguson", title="Professor",
                    url="https://mgcb.uchicago.edu/edwin-l-ferguson-phd",
                    keywords=["Development and Evolution", "Drosophila", "Embryogenesis", "Intercellular Signaling", "Pattern Formation", "Stem Cell Biology"]),
            faculty("Douglas K. Bishop", title="Professor",
                    url="https://mgcb.uchicago.edu/douglas-k-bishop-phd"),
            faculty("Benjamin Glick", title="Professor",
                    url="https://mgcb.uchicago.edu/benjamin-glick-phd",
                    keywords=["Membranes, Cell", "Microscopy, Electron", "Microscopy, Fluorescence", "Organelles"]),
            faculty("Stephen J. Kron", title="Professor",
                    url="https://mgcb.uchicago.edu/stephen-j-kron-md-phd",
                    keywords=["Checkpoints, Cell Cycle", "DNA Repair", "Immunotherapy", "Radiotherapy", "Senescence, Cell", "Systems Biology"]),
            faculty("Heng-Chi Lee", title="Associate Professor",
                    url="https://mgcb.uchicago.edu/heng-chi-lee-phd",
                    keywords=["C. elegans", "Chromatin", "Epigenetics", "Genome Instability", "Infertility", "RNA Processing, Post Transcriptional", "Small Non-Coding RNA"]),
            faculty("Sampriti Mukherjee", title="Assistant Professor",
                    url="https://mgcb.uchicago.edu/sampriti-mukherjee-phd",
                    keywords=["Bacterial genetics", "Bacterial sensory signal transduction", "Biofilms", "Genomics", "Microscopy", "Molecular biology"]),
            faculty("Robert Carrillo", title="Associate Professor",
                    url="https://mgcb.uchicago.edu/robert-carrillo-phd",
                    keywords=["Cell Surface Proteins", "Cell-cell interactions", "Drosophila melanogaster", "Neural circuit function", "Neural circuits", "Neural development", "Neurobiology, Cellular", "Neurobiology, Molecular"]),
            faculty("Margaret L. Gardel", title="Professor",
                    url="https://mgcb.uchicago.edu/margaret-l-gardel-phd",
                    keywords=["Adhesion, Cell", "Cell Mechanics", "Cytoskeleton, Actin", "Migration, Cell", "Myosin"]),
            faculty("Noah Mitchell", title="Assistant Professor",
                    url="https://mgcb.uchicago.edu/noah-mitchell-phd",
                    keywords=["Biophysics", "Cell Biology", "Developmental Biology", "Mathematical Models", "Morphogenesis", "Physics of Living Systems", "Soft Matter Physics", "Tissue Mechanics"]),
            faculty("Jarrett SMITH", title="Assistant Professor",
                    url="https://mgcb.uchicago.edu/jarrett-smith"),
            ],
        },
        {
            "short": "BMB",
            "name": "Department of Biochemistry and Molecular Biology",
            "majors": ["Biological Chemistry", "Biological Sciences", "Chemistry"],
            "directory_url": "https://biochem.uchicago.edu/people/our-faculty",
            "faculty": [
            faculty("Robert J. Keenan", title="Professor",
                    url="https://biochem.uchicago.edu/robert-j-keenan-phd",
                    keywords=["Biochemical reconstitution", "Cell biology", "Endoplasmic Reticulum", "Membrane protein biogenesis and quality control", "Structural biology, cryo-EM"]),
            faculty("Anthony Kossiakoff", title="Otho S.A. Sprague Distinguished Service Professor",
                    url="https://biochem.uchicago.edu/anthony-kossiakoff-phd",
                    keywords=["Antibody Engineering", "Membrane Proteins", "Phage Display Mutagenesis", "Protein Engineering", "Structural Biology", "T-cell Engineering"]),
            faculty("Tao Pan", title="Professor",
                    url="https://biochem.uchicago.edu/tao-pan-phd",
                    keywords=["epitranscriptomics", "Functional genomics", "Microbiome", "RNA modification", "tRNA"]),
            faculty("Benoit Roux", title="Amgen Professor",
                    url="https://biochem.uchicago.edu/benoit-roux-msc-phd"),
            faculty("Rama Ranganathan", title="Joseph Regenstein Professor",
                    url="https://biochem.uchicago.edu/rama-ranganathan-md-phd",
                    keywords=["adaptation", "cellular", "computational and statistical models", "Evolution", "protein", "protein folding", "statistical analysis"]),
            faculty("Ronald S. Rock", title="Associate Professor",
                    url="https://biochem.uchicago.edu/ronald-s-rock-phd",
                    keywords=["Actin Cytoskeleton", "Myosins", "Optical Tweezers", "Single Molecule", "Structural Biology", "TIRF Microscopy"]),
            faculty("Erin June Adams", title="Chair",
                    url="https://biochem.uchicago.edu/erin-june-adams-phd",
                    keywords=["biochemistry", "MHC (nonclassical and MHC-like)", "Molecular Immunology", "structural biology", "T Cells"]),
            faculty("Marvin W. Makinen", title="Professor",
                    url="https://biochem.uchicago.edu/marvin-w-makinen-md-phd"),
            faculty("Eduardo Perozo", title="Lillian Eichelberger Cannon Professor",
                    url="https://biochem.uchicago.edu/eduardo-perozo-phd"),
            faculty("Joseph A. Piccirilli", title="Professor",
                    url="https://biochem.uchicago.edu/joseph-piccirilli-phd"),
            faculty("Tobin R. Sosnick", title="William B. Graham Professor",
                    url="https://biochem.uchicago.edu/tobin-r-sosnick-phd",
                    keywords=["disordered proteins", "Hydrogen exchange", "Membrane Proteins", "NMR Spectroscopy", "optogenetics", "Protein Folding", "Simulations, Molecular Dynamics", "small-angle scattering"]),
            faculty("D. Allan Drummond", title="Associate Professor",
                    url="https://biochem.uchicago.edu/d-allan-drummond-phd",
                    keywords=["Cell Biology", "Heat Shock Response", "Molecular Evolution", "Phase Separation", "Stress Response, Physiological"]),
            faculty("Phoebe A. Rice", title="Professor",
                    url="https://biochem.uchicago.edu/phoebe-rice-phd",
                    keywords=["Biochemistry", "Cryo electron Microscopy", "DNA recombination", "Mobile Genetic Elements", "MRSA", "Staphylococcus aureus", "Xray Crystallography"]),
            faculty("Jingyi Fei", title="Associate Professor",
                    url="https://biochem.uchicago.edu/jingyi-fei-phd"),
            faculty("Demet Arac-Ozkan", title="Associate Professor",
                    url="https://biochem.uchicago.edu/demet-arac-ozkan-phd",
                    keywords=["Brain", "Cell Surface Proteins", "cortex development", "Crystallography, X Ray", "Electron Microscopy", "G Protein Coupled Receptors", "Membrane Proteins", "multicellularity"]),
            faculty("Minglei Zhao", title="Associate Professor",
                    url="https://biochem.uchicago.edu/minglei-zhao-phd",
                    keywords=["AAA+ ATPase", "p97", "Ubiquitination", "Vault RNP Particle"]),
            faculty("Engin Ozkan", title="Associate Professor",
                    url="https://biochem.uchicago.edu/engin-ozkan-phd",
                    keywords=["Axon guidance", "Cell surface receptors", "Cryo-electron microscopy", "Development", "Protein structure", "Protein-protein interactions", "Synapse formation", "X-ray crystallography"]),
            faculty("Cassandra Hayne", title="Assistant Professor",
                    url="https://biochem.uchicago.edu/cassandra-hayne-phd",
                    keywords=["Biochemistry", "Cell and Molecular Biology", "Cryo-Electron Microscopy", "Neurodegenerative Diseases", "Neurodevelopmental Diseases", "RNA", "RNA Processing, Post-Transcriptional", "tRNA"]),
            faculty("Marcos Sotomayor", title="Professor",
                    url="https://biochem.uchicago.edu/marcos-sotomayor-phd"),
            ],
        },
    ],
}


def fetch_and_normalize(deep: bool = True) -> list[dict]:
    """Wrapper bound to SCHOOL so refresh_all can call it like a collector."""
    return faculty_graph.fetch_and_normalize(SCHOOL, deep=deep)


def merge_into_processed(opps: list[dict]):
    return faculty_graph.merge_into_processed(opps)
