"""UCLA faculty config (via the faculty_graph engine, WordPress-REST source).

UCLA department sites run WordPress and expose faculty as custom post types over
``/wp-json/wp/v2/``. That structured JSON is far more reliable than CSS-scraping a
JS-rendered grid (the earlier ``.info-box`` / ``.tb-fields`` attempts over-listed
non-faculty), so these departments opt into the engine's ``api`` block:

  * **Chemistry & Biochemistry** (``directory`` post type) — filtered to the
    ``directory-category`` "Faculty" term (id 88), which excludes the Emeriti,
    Staff, Lecturer, Postdoc and Graduate-student categories. Keywords come from
    the clean ``specialties`` research taxonomy (Biochemistry, Biophysics,
    Chemical Biology, Catalysis, …), dropping the two teaching-track terms.
  * **MCDB** (Molecular, Cell & Developmental Biology, ``facultyinfo`` post type)
    — keywords from the ``model`` (organism) and ``research-area`` taxonomies.
  * **Psychology** (``faculty-page`` post type) — no research taxonomy, so a
    bounded per-profile enrich reads the rank ("…Professor" vs "Lecturer", which
    drops teaching-track and emeriti) and the "Primary Area" research line.

The seven **Samueli engineering** departments (BE, CBE, CEE, CS, ECE, MAE, MSE)
share one ``admin-ajax.php`` directory backend whose results come pre-grouped by
role — the engine keeps only the ladder-faculty containers (core / chair /
vice-chair / ieo / in-residence) and reads each profile's "RESEARCH AND
INTERESTS" toggle for clean keywords, so CS/ECE/MAE land at UIUC parity.

Math, Economics, and EEB are static-HTML ladder directories scraped directly.
**Physics & Astronomy** and **Statistics** sit behind an InCommon cert with an
incomplete chain (the server omits its intermediate); the shared fetcher now
supplies that intermediate (``ucb_common._ca_bundle`` — verification stays on),
so both scrape over the normal path: Physics from its ``/faculty.html`` table
(``h5`` name + a rank/research ``<p>`` trimmed of office/phone, emeriti dropped),
Statistics from its dedicated ladder page (lecturers dropped by title).

Single source ("ucla_faculty"); department rides each record's ``department``,
ids namespaced by department short-code. Audience "unknown".
"""

from __future__ import annotations

from .. import faculty_graph

SCHOOL: dict = {
    "school_slug": "ucla",
    "source": "ucla_faculty",
    "organization": "University of California, Los Angeles",
    "location": "Los Angeles, CA",
    "id_prefix": "ucla",
    "audience": "unknown",
    "work_auth_notes": (
        "External campus (UCLA) — work authorization depends on the arrangement; "
        "ask the professor."
    ),
    "departments": [
        {
            "short": "CHEM",
            "name": "Department of Chemistry and Biochemistry",
            "majors": ["Chemistry", "Biochemistry"],
            "directory_url": "https://www.chemistry.ucla.edu/faculty/",
            "api": {
                "type": "wp",
                "base": "https://www.chemistry.ucla.edu",
                "post_type": "directory",
                "category_include": {"directory-category": [88]},
                "keyword_tax": ["specialties"],
                "keyword_drop": ["instructional", "instructional support"],
                "name_flip": True,
            },
        },
        {
            "short": "MCDB",
            "name": "Department of Molecular, Cell and Developmental Biology",
            "majors": [
                "Molecular, Cell and Developmental Biology",
                "Biology",
                "Biochemistry",
            ],
            "directory_url": "https://www.mcdb.ucla.edu/faculty/",
            "api": {
                "type": "wp",
                "base": "https://www.mcdb.ucla.edu",
                "post_type": "facultyinfo",
                "keyword_tax": ["model", "research-area"],
            },
        },
        {
            "short": "PSYCH",
            "name": "Department of Psychology",
            "majors": ["Psychology", "Cognitive Science"],
            "directory_url": "https://www.psych.ucla.edu/faculty/",
            "api": {
                "type": "wp",
                "base": "https://www.psych.ucla.edu",
                "post_type": "faculty-page",
                "profile_enrich": {
                    "position_re": (
                        r"(?:Distinguished |Adjunct |Visiting |Acting |Research )?"
                        r"(?:Assistant |Associate )?Professor(?:\s+Emerit\w+)?"
                        r"|Senior Lecturer|Continuing Lecturer|Lecturer|Emerit\w+"
                    ),
                    "research_re": (
                        r"Primary Area:?\s*([A-Za-z &/-]{4,40}?)\s*"
                        r"(?:Home|Email|Address|Phone|Office|Department|Secondary|$)"
                    ),
                    "require_professor": True,
                },
            },
        },
        {
            "short": "BE",
            "name": "Department of Bioengineering",
            "majors": ["Bioengineering"],
            "directory_url": "https://samueli.ucla.edu/search-faculty/#be",
            "ajax": {"type": "seas", "department": "be", "research_enrich": True},
        },
        {
            "short": "CBE",
            "name": "Department of Chemical and Biomolecular Engineering",
            "majors": ["Chemical Engineering", "Chemical and Biomolecular Engineering"],
            "directory_url": "https://samueli.ucla.edu/search-faculty/#cbe",
            "ajax": {"type": "seas", "department": "cbe", "research_enrich": True},
        },
        {
            "short": "CEE",
            "name": "Department of Civil and Environmental Engineering",
            "majors": ["Civil Engineering", "Environmental Engineering"],
            "directory_url": "https://samueli.ucla.edu/search-faculty/#cee",
            "ajax": {"type": "seas", "department": "cee", "research_enrich": True},
        },
        {
            "short": "CS",
            "name": "Department of Computer Science",
            "majors": ["Computer Science", "Computer Science and Engineering"],
            "directory_url": "https://samueli.ucla.edu/search-faculty/#cs",
            "ajax": {"type": "seas", "department": "cs", "research_enrich": True},
        },
        {
            "short": "ECE",
            "name": "Department of Electrical and Computer Engineering",
            "majors": ["Electrical Engineering", "Computer Engineering"],
            "directory_url": "https://samueli.ucla.edu/search-faculty/#ece",
            "ajax": {"type": "seas", "department": "ece", "research_enrich": True},
        },
        {
            "short": "MAE",
            "name": "Department of Mechanical and Aerospace Engineering",
            "majors": ["Mechanical Engineering", "Aerospace Engineering"],
            "directory_url": "https://samueli.ucla.edu/search-faculty/#mae",
            "ajax": {"type": "seas", "department": "mae", "research_enrich": True},
        },
        {
            "short": "MSE",
            "name": "Department of Materials Science and Engineering",
            "majors": ["Materials Science and Engineering", "Materials Science"],
            "directory_url": "https://samueli.ucla.edu/search-faculty/#mse",
            "ajax": {"type": "seas", "department": "mse", "research_enrich": True},
        },
        # College static directories (ladder-only pages; emeriti live separately).
        {
            "short": "ECON",
            "name": "Department of Economics",
            "majors": ["Economics", "Business Economics"],
            "directory_url": "https://economics.ucla.edu/faculty/ladder/",
            "scrape": {"url": "https://economics.ucla.edu/faculty/ladder/",
                       "selectors": {"card": "a[href*='/person/']",
                                     "name": ":self", "link": ":self"}},
        },
        {
            "short": "EEB",
            "name": "Department of Ecology and Evolutionary Biology",
            "majors": ["Ecology and Evolutionary Biology", "Biology"],
            "directory_url": "https://www.eeb.ucla.edu/faculty/",
            "scrape": {"url": "https://www.eeb.ucla.edu/faculty/",
                       "selectors": {"card": "a[href*='/indivfaculty/?faculty=']",
                                     "name": ":self", "link": ":self"}},
        },
        {
            "short": "MATH",
            "name": "Department of Mathematics",
            "majors": ["Mathematics", "Applied Mathematics"],
            "directory_url": "https://www.math.ucla.edu/people/faculty/",
            "scrape": {"url": "https://www.math.ucla.edu/people/faculty/",
                       "name_flip": True,
                       "selectors": {"card": "tr",
                                     "name": "a[href*='/people/ladder/']",
                                     "link": "a[href*='/people/ladder/']",
                                     "title": "td:nth-child(2)"},
                       "ladder_filter": {"drop": r"emerit"}},
        },
        {
            "short": "PHYS",
            "name": "Department of Physics and Astronomy",
            "majors": ["Physics", "Astrophysics", "Astronomy"],
            "directory_url": "https://pa.ucla.edu/faculty.html",
            "scrape": {"url": "https://pa.ucla.edu/faculty.html",
                       "selectors": {"card": "tbody tr", "name": "h5",
                                     "link": "a", "title": "p",
                                     "title_strip_after": r"\s*(Office|Phone|Email|Fax|Tel)\b"},
                       "ladder_filter": {"require": r"professor", "drop": r"emerit"}},
        },
        {
            "short": "STAT",
            "name": "Department of Statistics and Data Science",
            "majors": ["Statistics", "Data Science"],
            "directory_url": "https://statistics.ucla.edu/index.php/people1/all-faculty/faculty/",
            "scrape": {"url": "https://statistics.ucla.edu/index.php/people1/all-faculty/faculty/",
                       "selectors": {"card": "div.abcfslTxtCntrGridA",
                                     "name": ".MP-F1", "title": ".MP-F3"},
                       "ladder_filter": {"require": r"professor",
                                         "drop": r"lecturer|emerit|adjunct|visiting"}},
        },
        # --- Full-coverage expansion (UIUC-parity): 31 more departments
        # across Letters & Science (humanities, social sciences, physical &
        # life sciences) and the professional schools (Anderson, Law, Luskin,
        # Public Health, Nursing, Arts & Architecture, Music). Each source
        # was verified live through the engine; ranks ladder + teaching.
        {'short': 'ENGL',
         'name': 'English',
         'majors': ['English', 'Literature', 'Creative Writing'],
         'directory_url': 'https://english.ucla.edu/people-faculty-affiliation/faculty/',
         'scrape': {'url': 'https://english.ucla.edu/people-faculty-affiliation/faculty/',
                    'selectors': {'card': '.faculty-item',
                                  'name': '.name',
                                  'link': 'a',
                                  'title': '.position'},
                    'name_flip': True,
                    'ladder_filter': {'drop': 'emerit'}}},
        {'short': 'HIST',
         'name': 'Department of History',
         'majors': ['History'],
         'directory_url': 'https://history.ucla.edu/people/faculty',
         'api': {'type': 'wp',
                 'base': 'https://history.ucla.edu',
                 'post_type': 'person',
                 'category_include': {'people-category': [21, 23]},
                 'category_exclude': {'people-category': [22, 24, 26, 28, 29, 36]}}},
        {'short': 'PHILOS',
         'name': 'Department of Philosophy',
         'majors': ['Philosophy'],
         'directory_url': 'https://philosophy.ucla.edu/people/ladder-faculty/',
         'scrape': {'url': 'https://philosophy.ucla.edu/people/ladder-faculty/',
                    'selectors': {'card': 'div.faculty-container.ladder-faculty, '
                                          'div.faculty-container.lecturers',
                                  'name': 'p.faculty-name',
                                  'title': 'p.faculty-position',
                                  'email': 'p.faculty-email',
                                  'research': 'p.faculty-interest'}}},
        {'short': 'ARTHIST',
         'name': 'Art History',
         'majors': ['Art History'],
         'directory_url': 'https://arthistory.ucla.edu/faculty/',
         'scrape': {'url': 'https://arthistory.ucla.edu/faculty/',
                    'selectors': {'card': 'li.person-item.core-faculty, li.person-item.lecturers',
                                  'name': 'dt.name',
                                  'link': 'a',
                                  'title': 'dd.position'}}},
        {'short': 'COMPLIT',
         'name': 'Comparative Literature',
         'majors': ['Comparative Literature'],
         'directory_url': 'https://complit.ucla.edu/faculty/',
         'scrape': {'url': 'https://complit.ucla.edu/faculty/',
                    'selectors': {'card': 'li.person-item.faculty',
                                  'name': 'dt.name',
                                  'link': 'a',
                                  'title': 'dd.position',
                                  'title_strip_after': ';'}}},
        {'short': 'LING',
         'name': 'Department of Linguistics',
         'majors': ['Linguistics',
                    'Linguistics and Computer Science',
                    'Linguistics and Applied Languages',
                    'Applied Linguistics'],
         'directory_url': 'https://linguistics.ucla.edu/faculty/',
         'scrape': {'url': 'https://linguistics.ucla.edu/faculty/',
                    'selectors': {'card': 'div.people-list h3#ladder-faculty + ul.faculty '
                                          'li.person-item, div.people-list h3#lecturers + ul.faculty '
                                          'li.person-item',
                                  'name': 'dt.name h3',
                                  'link': 'dt.name h3 a',
                                  'title': 'dd.position',
                                  'research': 'dd.interest',
                                  'email': 'dd.email a'},
                    'ladder_filter': {'drop': 'emerit|postdoc|visiting'}}},
        {'short': 'ALC',
         'name': 'Asian Languages & Cultures',
         'majors': ['Asian Languages and Cultures',
                    'Chinese',
                    'Japanese',
                    'Korean',
                    'Asian Studies',
                    'Asian Religions',
                    'East Asian Studies'],
         'directory_url': 'https://www.alc.ucla.edu/faculty/',
         'scrape': {'url': 'https://www.alc.ucla.edu/faculty/',
                    'selectors': {'card': '.person-item',
                                  'name': '.name',
                                  'link': 'a',
                                  'title': '.position',
                                  'research': '.interest'},
                    'ladder_filter': {'drop': 'administrator|emerit'}}},
        {'short': 'SLAVIC',
         'name': 'Slavic, East European & Eurasian Languages & Cultures',
         'majors': ['Russian Language and Literature',
                    'Slavic Languages and Literatures',
                    'Russian Studies',
                    'Central and East European Studies'],
         'directory_url': 'https://slavic.ucla.edu/people/faculty/',
         'scrape': {'url': 'https://slavic.ucla.edu/people/faculty/',
                    'selectors': {'card': 'li.person-item',
                                  'name': 'dt.name a',
                                  'link': 'dt.name a',
                                  'title': 'dd.position',
                                  'email': 'dd.email a'},
                    'ladder_filter': {'drop': 'emerit'}}},
        {'short': 'SPANPORT',
         'name': 'Spanish & Portuguese',
         'majors': ['Spanish',
                    'Portuguese',
                    'Spanish & Community and Culture',
                    'Spanish & Linguistics',
                    'Latin American Studies'],
         'directory_url': 'https://spanport.ucla.edu/faculty/',
         'scrape': {'url': 'https://spanport.ucla.edu/faculty/',
                    'selectors': {'card': 'ul.faculty li.person-item',
                                  'name': 'dt.name',
                                  'link': 'a',
                                  'title': 'dd.position'},
                    'ladder_filter': {'drop': 'emerit'}}},
        {'short': 'CLASSICS',
         'name': 'Classics',
         'majors': ['Classics',
                    'Classical Civilization',
                    'Greek',
                    'Latin',
                    'Ancient Near East and Egyptology'],
         'directory_url': 'https://classics.ucla.edu/people/faculty/',
         'scrape': {'url': 'https://classics.ucla.edu/people/faculty/',
                    'selectors': {'card': 'article.people_cat-faculty',
                                  'name': 'h3.entry-title a',
                                  'link': 'h3.entry-title a'},
                    'paginate': {'param': 'page', 'start': 2, 'max': 6, 'mode': 'path'}}},
        {'short': 'ANTHRO',
         'name': 'Department of Anthropology',
         'majors': ['Anthropology'],
         'directory_url': 'https://anthro.ucla.edu/people/faculty/',
         'api': {'type': 'wp',
                 'base': 'https://anthro.ucla.edu',
                 'post_type': 'person',
                 'category_include': {'people-category': [40, 19]},
                 'keyword_tax': ['people-category'],
                 'keyword_drop': ['Ladder Faculty',
                                  'Lecturers',
                                  'Professors',
                                  'Joint Appointment Faculty',
                                  'Adjunct Professors',
                                  'Graduate Students',
                                  'Previous Graduate Students',
                                  'Professor Emeritus',
                                  'Postdoctoral Scholars',
                                  'Visitors',
                                  'Research Professors']}},
        {'short': 'GEOG',
         'name': 'Department of Geography',
         'majors': ['Geography', 'Geographic Information Science', 'Environmental Science'],
         'directory_url': 'https://geog.ucla.edu/people/ladder-faculty/',
         'scrape': {'url': 'https://geog.ucla.edu/people/ladder-faculty/',
                    'selectors': {'card': 'ul.wpv-loop li',
                                  'name': '.person-name',
                                  'link': 'a',
                                  'title': '.person-position'}}},
        {'short': 'POLISCI',
         'name': 'Department of Political Science',
         'majors': ['Political Science'],
         'directory_url': 'https://polisci.ucla.edu/people/faculty/',
         'scrape': {'url': 'https://polisci.ucla.edu/people/faculty/',
                    'selectors': {'card': '.person-box',
                                  'name': 'h3 a',
                                  'link': 'h3 a',
                                  'title': '.faculty-position'},
                    'ladder_filter': {'drop': 'emerit'}}},
        {'short': 'SOC',
         'name': 'Department of Sociology',
         'majors': ['Sociology'],
         'directory_url': 'https://soc.ucla.edu/people/faculty/core-faculty/',
         'scrape': {'url': 'https://soc.ucla.edu/people/faculty/core-faculty/',
                    'selectors': {'card': 'div.av-special-heading',
                                  'name': 'h2.av-special-heading-tag a',
                                  'link': 'h2.av-special-heading-tag a',
                                  'title': '.av-subheading'},
                    'link_filter': '/person/',
                    'ladder_filter': {'drop': 'emerit'}}},
        {'short': 'COMM',
         'name': 'Department of Communication',
         'majors': ['Communication'],
         'directory_url': 'https://comm.ucla.edu/people/faculty/professors/',
         'scrape': {'url': 'https://comm.ucla.edu/people/faculty/professors/',
                    'selectors': {'card': 'div.right-side',
                                  'name': 'h3.name a',
                                  'link': 'h3.name a',
                                  'title': 'p.position',
                                  'research': 'div.interest',
                                  'email': "a[href^='mailto:']"},
                    'ladder_filter': {'drop': 'emerit|by courtesy'}}},
        {'short': 'GENDER',
         'name': 'Department of Gender Studies',
         'majors': ['Gender Studies', "Women's Studies", 'Feminist Studies'],
         'directory_url': 'https://gender.ucla.edu/people/faculty/',
         'scrape': {'url': 'https://gender.ucla.edu/people/faculty/',
                    'selectors': {'card': 'div.av-special-heading',
                                  'name': 'h2 a',
                                  'link': 'h2 a',
                                  'title': '.av-subheading'},
                    'link_filter': '/person/'}},
        {'short': 'AOS',
         'name': 'Atmospheric & Oceanic Sciences',
         'majors': ['Atmospheric Sciences',
                    'Atmospheric & Oceanic Sciences',
                    'Oceanic Sciences',
                    'Climate Science'],
         'directory_url': 'https://atmos.ucla.edu/directory/faculty/',
         'scrape': {'url': 'https://atmos.ucla.edu/directory/faculty/',
                    'selectors': {'card': '.person-card-grey',
                                  'name': 'h3 a',
                                  'link': 'h3 a',
                                  'title': '.person-card__info-wrapper p',
                                  'title_strip_after': 'Office:|Email:|Phone:'},
                    'ladder_filter': {'drop': 'emerit|adjunct'}}},
        {'short': 'EPSS',
         'name': 'Earth, Planetary & Space Sciences',
         'majors': ['Geology',
                    'Geophysics',
                    'Geochemistry',
                    'Planetary Science',
                    'Atmospheric & Oceanic Sciences',
                    'Earth Science',
                    'Space Physics'],
         'directory_url': 'https://epss.ucla.edu/faculty/',
         'scrape': {'url': 'https://epss.ucla.edu/faculty/',
                    'selectors': {'card': 'article.epss-card',
                                  'name': 'h3.epss-name a',
                                  'link': 'h3.epss-name a',
                                  'title': 'div.epss-job'},
                    'section_filter': {'heading': 'h2', 'exclude': 'affiliated|emerit'},
                    'ladder_filter': {'drop': 'emerit'}}},
        {'short': 'IBP',
         'name': 'Integrative Biology & Physiology',
         'majors': ['Biology',
                    'Physiology',
                    'Neuroscience',
                    'Marine Biology',
                    'Integrative Biology and Physiology'],
         'directory_url': 'https://www.ibp.ucla.edu/faculty/',
         'scrape': {'url': 'https://www.ibp.ucla.edu/faculty/',
                    'selectors': {'card': 'div.col-md-3',
                                  'name': '.faculty-name a',
                                  'link': '.faculty-name a',
                                  'title': '.faculty-title'},
                    'ladder_filter': {'drop': 'emerit|adjunct|adj\\.'}}},
        {'short': 'MIMG',
         'name': 'Microbiology, Immunology & Molecular Genetics',
         'majors': ['Microbiology',
                    'Immunology',
                    'Molecular Genetics',
                    'Molecular, Cell, and Developmental Biology'],
         'directory_url': 'https://mimg.ucla.edu/faculty',
         'scrape': {'url': 'https://mimg.ucla.edu/faculty',
                    'selectors': {'card': '.person-card',
                                  'name': '.person-card__name a',
                                  'link': '.person-card__name a',
                                  'title': '.person-card__title'},
                    'section_filter': {'heading': 'h2', 'include': 'Primary Faculty|Teaching Faculty'},
                    'ladder_filter': {'drop': 'emerit'}}},
        {'short': 'HUMGEN',
         'name': 'Department of Human Genetics',
         'majors': ['Human Genetics',
                    'Genetics',
                    'Genetic Counseling',
                    'Genomics',
                    'Computational Biology',
                    'Bioinformatics',
                    'Statistical Genetics'],
         'directory_url': 'https://medschool.ucla.edu/about/departments/basic-science/human-genetics/faculty-people',
         'scrape': {'url': 'https://medschool.ucla.edu/about/departments/basic-science/human-genetics/faculty-people',
                    'selectors': {'card': 'article.person-card',
                                  'name': '.person-card__name a',
                                  'link': '.person-card__name a',
                                  'title': '.person-card__title',
                                  'name_strip': ',\\s*(?:PhD|MD|DPhil|MS|MPH|EdD|DO|ScD)\\b.*$'},
                    'ladder_filter': {'require': 'profess|lecturer|\\bchair\\b',
                                      'drop': 'emerit|recall faculty|assistant to the '
                                              'chair|administrative|coordinator|\\bofficer\\b|manager|specialist'}}},
        {'short': 'ANDERSON',
         'name': 'Anderson School of Management',
         'majors': ['Business Administration',
                    'Management',
                    'Finance',
                    'Marketing',
                    'Accounting',
                    'Economics',
                    'Operations Management',
                    'Strategy'],
         'directory_url': 'https://www.anderson.ucla.edu/faculty-and-research/faculty-directory',
         'scrape': {'url': 'https://www.anderson.ucla.edu/faculty-and-research/faculty-directory',
                    'selectors': {'card': '.views-row',
                                  'name': '.profile-name',
                                  'link': '.card-links a',
                                  'title': '.person__field-display-title'},
                    'ladder_filter': {'drop': 'emerit|recalled|adjunct'}}},
        {'short': 'LAW',
         'name': 'School of Law',
         'majors': ['Law', 'Legal Studies'],
         'directory_url': 'https://law.ucla.edu/faculty/faculty-profiles',
         'scrape': {'url': 'https://law.ucla.edu/faculty/faculty-profiles',
                    'selectors': {'card': 'div.faculty-result',
                                  'name': 'h3.faculty-result__name',
                                  'link': 'a.faculty-result__link',
                                  'title': 'span.faculty-result__titles'},
                    'ladder_filter': {'require': '\\bprofessor\\b|\\blecturer\\b',
                                      'drop': 'emerit|visiting|adjunct|\\bfellow\\b|scholar|librarian|from '
                                              'practice|professor of practice|professor, '
                                              'ucla|associate professor, '
                                              'ucla|partner,|co-president|special counsel|assistant '
                                              'dean|deputy director|executive '
                                              'director|^director|project director|legal and policy '
                                              'director'},
                    'paginate': {'param': 'page', 'start': 2, 'max': 35}}},
        {'short': 'PUBPOL',
         'name': 'Public Policy',
         'majors': ['Public Policy', 'Public Affairs', 'Policy Analysis'],
         'directory_url': 'https://luskin.ucla.edu/public-policy-faculty',
         'scrape': {'url': 'https://luskin.ucla.edu/public-policy-faculty',
                    'selectors': {'card': 'div.faculty-box',
                                  'name': 'h3 a',
                                  'link': 'h3 a',
                                  'title': 'h4'},
                    'ladder_filter': {'require': 'profess|lecturer', 'drop': 'emerit|adjunct'}}},
        {'short': 'URP',
         'name': 'Urban Planning',
         'majors': ['Urban Planning', 'Urban Studies', 'Urban & Regional Planning'],
         'directory_url': 'https://luskin.ucla.edu/urban-planning-faculty/',
         'scrape': {'url': 'https://luskin.ucla.edu/urban-planning-faculty/',
                    'selectors': {'card': '.faculty-box',
                                  'name': 'h3 a',
                                  'link': 'h3 a',
                                  'title': 'h4'},
                    'ladder_filter': {'require': 'profess|lecturer',
                                      'drop': 'emerit|adjunct|assistant\\s+researcher'}}},
        {'short': 'SOCWEL',
         'name': 'Social Welfare',
         'majors': ['Social Welfare', 'Social Work'],
         'directory_url': 'https://luskin.ucla.edu/social-welfare/social-welfare-faculty',
         'scrape': {'url': 'https://luskin.ucla.edu/social-welfare/social-welfare-faculty',
                    'selectors': {'card': '.faculty-box',
                                  'name': 'h3 a',
                                  'link': 'h3 a',
                                  'title': 'h4'},
                    'ladder_filter': {'require': 'profess|lecturer|faculty', 'drop': 'emerit|adjunct'}}},
        {'short': 'BIOSTAT',
         'name': 'Department of Biostatistics',
         'majors': ['Biostatistics', 'Public Health', 'Statistics', 'Data Science'],
         'directory_url': 'https://ph.ucla.edu/about/faculty-staff-directory?type=faculty&department%5B0%5D=85',
         'scrape': {'url': 'https://ph.ucla.edu/about/faculty-staff-directory?type=faculty&department%5B0%5D=85',
                    'selectors': {'card': '.card--person',
                                  'name': '.card__heading',
                                  'link': 'a.card__link'},
                    'paginate': {'param': 'page', 'start': 2, 'max': 6}}},
        {'short': 'NURS',
         'name': 'School of Nursing',
         'majors': ['Nursing'],
         'directory_url': 'https://nursing.ucla.edu/about/our-people/faculty-directory',
         'scrape': {'url': 'https://nursing.ucla.edu/about/our-people/faculty-directory',
                    'selectors': {'card': '.person-card',
                                  'name': '.person-card__name a',
                                  'link': '.person-card__name a',
                                  'title': '.person-card__title',
                                  'name_strip': ',.*$'},
                    'ladder_filter': {'require': 'profess|lecturer', 'drop': 'adjunct|emerit'}}},
        {'short': 'ARCH',
         'name': 'Architecture & Urban Design',
         'majors': ['Architecture', 'Urban Design', 'Architectural Studies'],
         'directory_url': 'https://www.aud.ucla.edu/faculty',
         'scrape': {'url': 'https://www.aud.ucla.edu/faculty',
                    'selectors': {'card': 'figure.portrait',
                                  'name': 'figcaption',
                                  'name_strip': '\\s*(?:Chair and |Vice Chair and |Associate '
                                                '|Assistant |Adjunct )*(?:Professor|Lecturer|Adjunct '
                                                'Professor).*$',
                                  'link': 'a'},
                    'ladder_filter': {'drop': 'emerit'}}},
        {'short': 'DESMA',
         'name': 'Design Media Arts',
         'majors': ['Design Media Arts', 'Media Arts'],
         'directory_url': 'https://dma.ucla.edu/people/faculty',
         'scrape': {'url': 'https://dma.ucla.edu/people/faculty',
                    'selectors': {'card': 'li.style_item__2yDd9',
                                  'name': 'div.style_itemName__EB7WD',
                                  'link': 'a.style_itemContents__14hs0',
                                  'title': 'div.style_itemMeta__3GHJL'},
                    'ladder_filter': {'require': 'professor|lecturer',
                                      'drop': 'emerit|memoriam|visiting|research professor'}}},
        {'short': 'MUSIC',
         'name': 'Herb Alpert School of Music',
         'majors': ['Music',
                    'Musicology',
                    'Ethnomusicology',
                    'Music Industry',
                    'Music Performance',
                    'Music Education',
                    'Composition',
                    'Global Jazz Studies'],
         'directory_url': 'https://schoolofmusic.ucla.edu/faculty/',
         'api': {'type': 'wp',
                 'base': 'https://schoolofmusic.ucla.edu',
                 'post_type': 'people',
                 'category_include': {'people_category': [36]},
                 'keyword_tax': ['department']}},
    ],
}


def fetch_and_normalize(deep: bool = True) -> list[dict]:
    return faculty_graph.fetch_and_normalize(SCHOOL, deep=deep)


def merge_into_processed(opps: list[dict]):
    return faculty_graph.merge_into_processed(opps)
