"""University of Washington faculty config (via the faculty_graph engine).

Unlike Michigan (whose directories are Cloudflare-walled, so it ships a curated
hand-verified set), UW's department directories are server-rendered and
scrapable, so this config is scrape-first: each department carries a ``scrape``
block (directory URL + CSS selectors) and deep mode lands real, current faculty
live. No curated seed list to hand-maintain.

Two directory shapes on campus:
  * **ECE** uses the College-of-Engineering ``stafftemplate`` card, which exposes
    research interests + a mailto inline — so its faculty land fully keyworded
    in one pass (UIUC-level richness).
  * **The College of Arts & Sciences departments** (Physics, Chemistry,
    Mathematics, Astronomy, Economics, Linguistics, Geography, History,
    Political Science, Sociology, Philosophy, English, Anthropology)
    share a Drupal "Views" directory that lists name + job title + email but not
    research areas, so those faculty land as keyword-light cold-email targets
    (department majors drive matching; per-profile research enrichment is a
    deferred follow-up — the page interest sections are inconsistent across
    departments and risk nav-menu pollution, so accuracy comes first).

The College of Engineering's facultyfinder app and the Allen School's
client-rendered grid still expose their faculty in the raw HTML (a server-
rendered table / profile-link list), so both are covered via the ``_ff`` helper
and the CSE link-list scrape below rather than a headless browser.

Single source ("uw_faculty") across departments (the UIUC model); the
department rides each record's ``department`` field, ids namespaced by
department short-code. Audience "unknown" — cross-school openness is per-prof.
"""

from __future__ import annotations

from .. import faculty_graph

# Shared Drupal "Views" directory selectors (UW College of Arts & Sciences).
# Card is ".views-row" (tag-agnostic): most departments wrap each person in a
# ``div.views-row``, but a few (Applied Math, Classics, Dance, CHID) use a
# ``li.views-row`` grid — matching the class alone covers both with identical
# results on the div-based pages (no extra rows pulled in).
_CAS_SELECTORS = {
    "card": ".views-row",
    "name": ".views-field-title a",
    "link": ".views-field-title a",
    "title": ".views-field-field-job-title .field-content",
    "email": ".views-field-field-email a",
}


def _cas(short: str, name: str, majors: list[str], url: str) -> dict:
    # Drop emeriti by job title (some CAS /people/faculty pages list them inline).
    # Only "emerit" — NOT adjunct/affiliate: those appear as a *secondary* clause
    # on a primary professor's title ("Professor, X; Adjunct Professor, Y"), so
    # dropping on them would cut real home-department faculty.
    return {
        "short": short, "name": name, "majors": majors,
        "directory_url": url,
        "scrape": {"url": url, "selectors": _CAS_SELECTORS,
                   "ladder_filter": {"drop": r"emerit"}},
    }


# College of Engineering "facultyfinder" — a server-rendered table (the JS path
# is just a wrapper). ``?page_size=300`` returns all rows in one request; the
# name is inverted ("Last, First"), research areas are per-area list items, and
# courtesy appointments in other departments mean a whole-cell rank drop would
# over-prune, so we keep any "Professor" row and only drop emeriti.
def _ff(short: str, name: str, majors: list[str], host: str) -> dict:
    url = f"https://{host}/facultyfinder?page_size=300"
    return {"short": short, "name": name, "majors": majors, "directory_url": url,
            "scrape": {"url": url, "name_flip": True,
                       "selectors": {"card": "table#results tbody tr",
                                     "name": "td:nth-child(2) b a",
                                     "link": "td:nth-child(2) b a",
                                     "title": "td:nth-child(3)",
                                     "email": "td:nth-child(2) a[href^='mailto:']",
                                     "research_items": "td:nth-child(4) li"},
                       "ladder_filter": {"require": r"professor", "drop": r"emerit"}}}


SCHOOL: dict = {
    "school_slug": "uw",
    "source": "uw_faculty",
    "organization": "University of Washington",
    "location": "Seattle, WA",
    "id_prefix": "uw",
    "audience": "unknown",
    "work_auth_notes": (
        "External campus (University of Washington) — work authorization depends "
        "on the arrangement; ask the professor."
    ),
    "departments": [
        {
            "short": "ECE",
            "name": "Electrical & Computer Engineering",
            "majors": ["Electrical Engineering", "Computer Engineering", "Electrical & Computer Engineering"],
            "directory_url": "https://www.ece.uw.edu/faculty/",
            "scrape": {
                "url": "https://www.ece.uw.edu/faculty/",
                "selectors": {
                    "card": ".stafftemplate--entry",
                    "name": ".stafftemplate--name a",
                    "link": ".stafftemplate--name a",
                    "title": ".stafftemplate--title",
                    "research": ".stafftemplate--interests",
                    "email": ".stafftemplate--email a",
                },
            },
        },
        _cas("PHYS", "Department of Physics",
             ["Physics", "Applied Physics", "Astrophysics"],
             "https://phys.washington.edu/people/faculty"),
        _cas("CHEM", "Department of Chemistry",
             ["Chemistry", "Biochemistry"],
             "https://chem.washington.edu/people/faculty"),
        _cas("MATH", "Department of Mathematics",
             ["Mathematics", "Applied Mathematics"],
             "https://math.washington.edu/people/faculty"),
        _cas("ASTR", "Department of Astronomy",
             ["Astronomy", "Astrophysics"],
             "https://astro.washington.edu/people/faculty"),
        _cas("ECON", "Department of Economics",
             ["Economics"],
             "https://econ.washington.edu/people/faculty"),
        _cas("LING", "Department of Linguistics",
             ["Linguistics"],
             "https://linguistics.washington.edu/people/faculty"),
        _cas("GEOG", "Department of Geography",
             ["Geography"],
             "https://geography.washington.edu/people/faculty"),
        _cas("HIST", "Department of History",
             ["History"],
             "https://history.washington.edu/people/faculty"),
        _cas("POLS", "Department of Political Science",
             ["Political Science"],
             "https://www.polisci.washington.edu/people/faculty"),
        _cas("SOC", "Department of Sociology",
             ["Sociology"],
             "https://soc.washington.edu/people/faculty"),
        _cas("PHIL", "Department of Philosophy",
             ["Philosophy"],
             "https://phil.washington.edu/people/faculty"),
        _cas("ENGL", "Department of English",
             ["English", "Literature", "Creative Writing"],
             "https://english.washington.edu/people/faculty"),
        _cas("ANTH", "Department of Anthropology",
             ["Anthropology"],
             "https://anthropology.washington.edu/people/faculty"),
        # More College of Arts & Sciences departments on the same Drupal "Views"
        # directory (humanities, arts, and Applied Mathematics).
        _cas("AMATH", "Department of Applied Mathematics",
             ["Applied Mathematics", "Mathematics", "Computational Science"],
             "https://amath.washington.edu/people/faculty"),
        _cas("MUSIC", "School of Music",
             ["Music", "Music Composition", "Ethnomusicology"],
             "https://music.washington.edu/people/faculty"),
        _cas("ASIANLL", "Department of Asian Languages & Literature",
             ["Asian Languages & Literature", "Linguistics"],
             "https://asian.washington.edu/people/faculty"),
        _cas("SPANPORT", "Department of Spanish & Portuguese Studies",
             ["Spanish", "Portuguese", "Romance Languages"],
             "https://spanport.washington.edu/people/faculty"),
        _cas("SCAND", "Department of Scandinavian Studies",
             ["Scandinavian Studies", "Linguistics"],
             "https://scandinavian.washington.edu/people/faculty"),
        _cas("SLAV", "Department of Slavic Languages & Literatures",
             ["Slavic Languages & Literatures", "Russian"],
             "https://slavic.washington.edu/people/faculty"),
        _cas("GERM", "Department of Germanics",
             ["Germanics", "German"],
             "https://germanics.washington.edu/people/faculty"),
        _cas("FRENCHIT", "Department of French & Italian Studies",
             ["French", "Italian", "Romance Languages"],
             "https://frenchitalian.washington.edu/people/faculty"),
        _cas("CLAS", "Department of Classics",
             ["Classics", "Classical Studies"],
             "https://classics.washington.edu/people/faculty"),
        _cas("GWSS", "Department of Gender, Women & Sexuality Studies",
             ["Gender, Women & Sexuality Studies"],
             "https://gwss.washington.edu/people/faculty"),
        _cas("DANCE", "Department of Dance",
             ["Dance"],
             "https://dance.washington.edu/people/faculty"),
        _cas("AIS", "Department of American Indian Studies",
             ["American Indian Studies"],
             "https://ais.washington.edu/people/faculty"),
        _cas("CHID", "Comparative History of Ideas",
             ["Comparative History of Ideas", "Interdisciplinary Studies"],
             "https://chid.washington.edu/people/faculty"),
        # College of Engineering (facultyfinder, keyworded + emailed).
        _ff("ME", "Department of Mechanical Engineering",
            ["Mechanical Engineering"], "www.me.washington.edu"),
        _ff("AA", "Department of Aeronautics & Astronautics",
            ["Aeronautics & Astronautics", "Aerospace Engineering"], "www.aa.washington.edu"),
        _ff("CHEME", "Department of Chemical Engineering",
            ["Chemical Engineering"], "www.cheme.washington.edu"),
        _ff("CEE", "Department of Civil & Environmental Engineering",
            ["Civil Engineering", "Environmental Engineering"], "www.ce.washington.edu"),
        _ff("MSE", "Department of Materials Science & Engineering",
            ["Materials Science & Engineering"], "www.mse.washington.edu"),
        # Paul G. Allen School of CSE — the card grid is JS-rendered, but each
        # faculty's profile link + name is in the raw HTML, so a link-list scrape
        # recovers them (name+profile cold-email targets).
        {
            "short": "CSE",
            "name": "Paul G. Allen School of Computer Science & Engineering",
            "majors": ["Computer Science", "Computer Engineering", "Data Science"],
            "directory_url": "https://www.cs.washington.edu/people/faculty",
            "scrape": {
                "url": "https://www.cs.washington.edu/people/faculty",
                "selectors": {"card": "a[href*='/people/faculty/']",
                              "name": ":self", "link": ":self"},
            },
        },
        # Bioengineering — WordPress (Avada) "Core Faculty" portfolio, keyworded.
        {
            "short": "BIOE",
            "name": "Department of Bioengineering",
            "majors": ["Bioengineering", "Biomedical Engineering"],
            "directory_url": "https://bioe.uw.edu/people/faculty/",
            "api": {"type": "wp", "base": "https://bioe.uw.edu",
                    "post_type": "avada_portfolio",
                    "category_include": {"portfolio_category": [170]},
                    "keyword_tax": ["portfolio_category"],
                    "keyword_drop": ["core faculty", "faculty", "adjunct",
                                     "affiliate", "emeritus", "joint"]},
        },
        # Statistics — Drupal "Views" grid (one .faculty-column per person, 3 per
        # row). Behind an InCommon cert with an incomplete chain; the shared
        # fetcher supplies the missing intermediate (verification stays on).
        # Title-filtered to ladder ranks (lecturers/emeriti/affiliates dropped).
        {
            "short": "STAT",
            "name": "Department of Statistics",
            "majors": ["Statistics", "Data Science"],
            "directory_url": "https://stat.uw.edu/people/faculty",
            "scrape": {
                "url": "https://stat.uw.edu/people/faculty",
                "selectors": {"card": "div.faculty-column",
                              "name": ".views-field-title",
                              "link": "a[href*='/people/']",
                              "title": ".views-field-field-position"},
                "ladder_filter": {"require": r"professor",
                                  "drop": r"emerit|lecturer|adjunct|visiting|affiliate|part-time"},
            },
        },
        # Biology — Drupal directory, title-filtered to ladder ranks.
        {
            "short": "BIOL",
            "name": "Department of Biology",
            "majors": ["Biology", "Molecular Biology", "Ecology"],
            "directory_url": "https://biology.washington.edu/people/faculty",
            "scrape": {
                "url": "https://biology.washington.edu/people/faculty",
                "selectors": {"card": "div.directory-item",
                              "name": "h2.directory-item__name a",
                              "link": "h2.directory-item__name a",
                              "title": "strong.directory-item__title",
                              "email": "a[href^='mailto:']"},
                "ladder_filter": {"require": r"professor",
                                  "drop": r"emerit|adjunct|affiliat|teaching|acting|visiting"},
            },
        },
        # --- Full-coverage expansion (UIUC-parity): 25 more departments
        # across the College of the Environment, Engineering, Education,
        # Foster Business, Nursing, Pharmacy, Public Health, Social Work,
        # Evans, the iSchool, Built Environments, and School of Medicine
        # basic sciences. Each scrape/api/faculty180 source was verified
        # live through the engine; ranks title-filtered to ladder+teaching.
        {'short': 'PSYCH',
         'name': 'Department of Psychology',
         'majors': ['Psychology'],
         'directory_url': 'https://psych.uw.edu/people/faculty',
         'scrape': {'url': 'https://psych.uw.edu/people/faculty',
                    'selectors': {'card': 'table tr',
                                  'name': 'td:nth-of-type(1) a',
                                  'link': 'td:nth-of-type(1) a',
                                  'title': 'td:nth-of-type(2)',
                                  'email': 'td:nth-of-type(3)'},
                    'ladder_filter': {'require': 'profess|lecturer',
                                      'drop': 'emerit|adjunct|affiliate|instructor|postdoc|teaching '
                                              'associate|psychiatr|behavioral '
                                              'scien|dental|radiology|\\bpediatr|harborview|neurology'}}},
        {'short': 'COM',
         'name': 'Department of Communication',
         'majors': ['Communication', 'Journalism', 'Communication Studies'],
         'directory_url': 'https://com.uw.edu/people/faculty/',
         'api': {'type': 'wp',
                 'base': 'https://com.uw.edu',
                 'post_type': 'person',
                 'category_include': {'people-group': [84, 96, 97]},
                 'category_exclude': {'people-group': [99, 100, 98, 85]},
                 'meta_title_field': 'job_title',
                 'meta_email_field': 'email_address'}},
        {'short': 'ESS',
         'name': 'Earth & Space Sciences',
         'majors': ['Earth and Space Sciences', 'Geology', 'Geophysics', 'Earth Science'],
         'directory_url': 'https://ess.uw.edu/people-research/faculty/',
         'scrape': {'url': 'https://ess.uw.edu/people-research/faculty/',
                    'selectors': {'card': 'li.faculty-list-item a',
                                  'name': '.faculty-name',
                                  'link': ':self',
                                  'title': '.faculty-title'},
                    'ladder_filter': {'drop': 'emerit|facilities|engineer/architect'}}},
        {'short': 'ATMOS',
         'name': 'Department of Atmospheric & Climate Science',
         'majors': ['Atmospheric Sciences',
                    'Atmospheric & Climate Science',
                    'Climate Science',
                    'Meteorology',
                    'Earth Sciences'],
         'directory_url': 'https://atmos.uw.edu/faculty-and-research/core-faculty/',
         'scrape': {'url': 'https://atmos.uw.edu/faculty-and-research/core-faculty/',
                    'selectors': {'card': 'div.faculty-list-item',
                                  'name': 'div.faculty-name',
                                  'link': 'a'}}},
        {'short': 'NELC',
         'name': 'Department of Near Eastern Languages & Civilization',
         'majors': ['Near Eastern Languages & Civilization',
                    'Middle Eastern Languages & Cultures',
                    'Middle Eastern Studies',
                    'Arabic',
                    'Hebrew',
                    'Persian',
                    'Turkish'],
         'directory_url': 'https://melc.washington.edu/people/faculty',
         'scrape': {'url': 'https://melc.washington.edu/people/faculty',
                    'selectors': {'card': 'div.views-row',
                                  'name': 'h2.directory-item__name a',
                                  'link': 'h2.directory-item__name a',
                                  'title': 'strong.directory-item__title',
                                  'research_items': '.tags__link',
                                  'email': "a[href^='mailto:']"},
                    'ladder_filter': {'drop': 'emerit'}}},
        {'short': 'ART',
         'name': 'School of Art + Art History + Design',
         'majors': ['Art',
                    'Art History',
                    'Design',
                    'Visual Communication Design',
                    'Industrial Design',
                    'Interaction Design',
                    'Painting + Drawing',
                    'Photo/Media',
                    'Ceramics',
                    'Interdisciplinary Visual Arts'],
         'directory_url': 'https://art.washington.edu/people/faculty',
         'scrape': {'url': 'https://art.washington.edu/people/faculty',
                    'selectors': {'card': '.directory-item',
                                  'name': '.directory-item__name a',
                                  'link': '.directory-item__name a',
                                  'title': '.directory-item__title',
                                  'email': '.directory-item__info a[href^="mailto:"]'},
                    'ladder_filter': {'drop': 'emerit'}}},
        {'short': 'DRAMA',
         'name': 'School of Drama',
         'majors': ['Drama', 'Theatre', 'Theatre Arts', 'Acting', 'Design'],
         'directory_url': 'https://drama.washington.edu/people/faculty',
         'scrape': {'url': 'https://drama.washington.edu/people/faculty',
                    'selectors': {'card': 'div.directory-item',
                                  'name': 'h2.directory-item__name a',
                                  'link': 'h2.directory-item__name a',
                                  'title': 'strong.directory-item__title',
                                  'email': "a[href^='mailto:']"},
                    'ladder_filter': {'require': 'professor|lecturer',
                                      'drop': 'emerit|affiliat|part-time'}}},
        {'short': 'SPHSC',
         'name': 'Department of Speech & Hearing Sciences',
         'majors': ['Speech & Hearing Sciences',
                    'Speech-Language Pathology',
                    'Audiology',
                    'Communication Sciences and Disorders'],
         'directory_url': 'https://sphsc.washington.edu/faculty',
         'scrape': {'url': 'https://sphsc.washington.edu/faculty',
                    'selectors': {'card': '.faculty-box',
                                  'name': 'strong a',
                                  'link': 'strong a',
                                  'title': 'em',
                                  'email': "a[href^='mailto:']"},
                    'ladder_filter': {'drop': 'emerit|adjunct|affiliate'}}},
        {'short': 'SEFS',
         'name': 'School of Environmental & Forest Sciences',
         'majors': ['Environmental Science',
                    'Forestry',
                    'Ecology',
                    'Natural Resources',
                    'Environmental Studies'],
         'directory_url': 'https://sefs.uw.edu/research/faculty/',
         'scrape': {'url': 'https://sefs.uw.edu/research/faculty/',
                    'selectors': {'card': 'a:has(li.faculty-list-item)',
                                  'name': 'h3',
                                  'link': ':self'}}},
        {'short': 'OCEAN',
         'name': 'School of Oceanography',
         'majors': ['Oceanography', 'Marine Biology', 'Marine Science', 'Earth Science'],
         'directory_url': 'https://www.ocean.washington.edu/person/faculty?core=on',
         'scrape': {'url': 'https://www.ocean.washington.edu/person/faculty?core=on',
                    'selectors': {'card': 'div.item',
                                  'name': 'a.overlay2 .description',
                                  'link': 'a.overlay2'}}},
        {'short': 'FISH',
         'name': 'School of Aquatic & Fishery Sciences',
         'majors': ['Aquatic and Fishery Sciences', 'Marine Biology', 'Fisheries', 'Marine Science'],
         'directory_url': 'https://fish.uw.edu/faculty-research/',
         'scrape': {'url': 'https://fish.uw.edu/faculty-research/',
                    'selectors': {'card': 'li.faculty-list-item', 'name': 'h3 a', 'link': 'h3 a'}}},
        {'short': 'ISE',
         'name': 'Industrial & Systems Engineering',
         'majors': ['Industrial Engineering',
                    'Systems Engineering',
                    'Industrial & Systems Engineering'],
         'directory_url': 'https://ise.washington.edu/facultyfinder',
         'scrape': {'url': 'https://ise.washington.edu/facultyfinder',
                    'selectors': {'card': 'table.faculty-finder-list tr',
                                  'name': 'td b',
                                  'link': "td b a, td a[href*='/faculty/'], td "
                                          "a[href*='/facultyfinder/']",
                                  'title': 'td:nth-of-type(3)',
                                  'research_items': 'td:nth-of-type(4) li',
                                  'email': "td a[href^='mailto:']"},
                    'name_flip': True,
                    'ladder_filter': {'require': 'professor', 'drop': 'emerit'}}},
        {'short': 'HCDE',
         'name': 'Human Centered Design & Engineering',
         'majors': ['Human Centered Design & Engineering',
                    'Human-Computer Interaction',
                    'User Experience Design',
                    'Informatics'],
         'directory_url': 'https://www.hcde.washington.edu/faculty',
         'scrape': {'url': 'https://www.hcde.washington.edu/faculty',
                    'selectors': {'card': 'div.columns',
                                  'name': 'h2 a',
                                  'link': 'h2 a',
                                  'title': 'h2 + p',
                                  'research': 'h3 + p'},
                    'ladder_filter': {'require': 'professor', 'drop': 'emerit'}}},
        {'short': 'ISCHOOL',
         'name': 'Information School',
         'majors': ['Informatics',
                    'Information Science',
                    'Library Science',
                    'Information Management',
                    'Data Science',
                    'Human-Computer Interaction'],
         'directory_url': 'https://ischool.uw.edu/people/faculty',
         'scrape': {'url': 'https://ischool.uw.edu/people/faculty',
                    'selectors': {'card': "article.card[data-type*='core']",
                                  'name': '.info h2 a',
                                  'link': '.info h2 a',
                                  'title': '.info p.small em',
                                  'email': "address a[href^='mailto:']"},
                    'ladder_filter': {'require': 'professor', 'drop': 'emerit'}}},
        {'short': 'EDUC',
         'name': 'College of Education',
         'majors': ['Education',
                    'Educational Psychology',
                    'Special Education',
                    'Teacher Education',
                    'Learning Sciences',
                    'Education Policy',
                    'Measurement & Statistics',
                    'School Psychology'],
         'directory_url': 'https://education.uw.edu/about/directory',
         'scrape': {'url': 'https://education.uw.edu/about/directory',
                    'selectors': {'card': 'table tbody tr',
                                  'name': 'td.views-field-title a',
                                  'link': 'td.views-field-title a',
                                  'title': 'td.views-field-field-appointment',
                                  'email': 'td.views-field-field-email a'},
                    'ladder_filter': {'require': 'professor', 'drop': 'emerit'}}},
        {'short': 'Foster',
         'name': 'Foster School of Business',
         'majors': ['Business Administration',
                    'Accounting',
                    'Finance',
                    'Marketing',
                    'Information Systems',
                    'Operations Management',
                    'Management'],
         'directory_url': 'https://foster.uw.edu/faculty-research/directory/',
         'scrape': {'url': 'https://foster.uw.edu/faculty-research/directory/',
                    'selectors': {'card': '.faculty-directory__listing-item',
                                  'name': '.faculty-directory__listing-name',
                                  'link': 'a.faculty-directory__profile-link-image',
                                  'title': '.faculty-directory__listing-job-title'},
                    'ladder_filter': {'require': 'professor|lecturer',
                                      'drop': 'emerit|retired|affiliate|adjunct|visiting'}}},
        {'short': 'NURS',
         'name': 'School of Nursing',
         'majors': ['Nursing', 'Nursing Science', 'Health Informatics', 'Public Health Nursing'],
         'directory_url': 'https://nursing.uw.edu/faculty/',
         'faculty180': {'base': 'https://nursing.uw.edu',
                        'profile_base': 'https://nursing.uw.edu/person/',
                        'per_page': 100,
                        'ladder_filter': {'require': 'professor|lecturer',
                                          'drop': 'emer|affiliate|non.?salaried|postdoc|visiting|teaching '
                                                  'associate|clinical instructor|acting|undesignated'}}},
        {'short': 'PHARM',
         'name': 'School of Pharmacy',
         'majors': ['Pharmacy',
                    'Pharmaceutical Sciences',
                    'Medicinal Chemistry',
                    'Pharmaceutics',
                    'Pharmacology',
                    'Health Economics'],
         'directory_url': 'https://sop.washington.edu/people-directory/school-faculty/',
         'scrape': {'url': 'https://sop.washington.edu/people-directory/school-faculty/',
                    'selectors': {'card': 'div.profile-list.searchable',
                                  'name': 'h3.name',
                                  'link': 'div.info > a',
                                  'title': 'p.title',
                                  'email': "div.contact-block a[href^='mailto:']",
                                  'research_items': 'div.expertise-block a'},
                    'ladder_filter': {'require': 'profess|lecturer',
                                      'drop': 'emerit|^\\s*(?:affiliate|adjunct)\\b|adjunct[\\w '
                                              ']*professor,?\\s*(?:dept\\.?\\s*of\\s*)?pharmacy\\b|pharmacy\\s*\\(adjunct\\)|harvard '
                                              'medical school'}}},
        {'short': 'SOCWORK',
         'name': 'School of Social Work',
         'majors': ['Social Work', 'Social Welfare'],
         'directory_url': 'https://socialwork.uw.edu/directory/?team_roles=professor',
         'scrape': {'url': 'https://socialwork.uw.edu/directory/?team_roles=professor',
                    'selectors': {'card': 'div.item',
                                  'name': 'div.text h3 a',
                                  'link': 'div.text h3 a',
                                  'title': 'div.text p'},
                    'ladder_filter': {'drop': 'emerit'},
                    'paginate': {'mode': 'path', 'param': 'page', 'start': 2, 'max': 6}}},
        {'short': 'Evans',
         'name': 'Evans School of Public Policy & Governance',
         'majors': ['Public Policy',
                    'Public Administration',
                    'Public Affairs',
                    'Public Management',
                    'Nonprofit Management'],
         'directory_url': 'https://evans.uw.edu/directory/',
         'scrape': {'url': 'https://evans.uw.edu/directory/?_sft_profile_type=01-evans-school-faculty',
                    'selectors': {'card': '.profile-card',
                                  'name': '.profile-card__name a',
                                  'link': '.profile-card__name a',
                                  'title': '.profile-card__title',
                                  'email': '.profile-card__email'}}},
        {'short': 'BIOSTAT',
         'name': 'Department of Biostatistics',
         'majors': ['Biostatistics', 'Statistics', 'Public Health', 'Data Science', 'Epidemiology'],
         'directory_url': 'https://www.biostat.washington.edu/people/faculty',
         'scrape': {'url': 'https://www.biostat.washington.edu/people/faculty?faculty_type=1261',
                    'selectors': {'card': '.views-row:has(h2.person-name)',
                                  'name': 'h2.person-name a',
                                  'link': 'h2.person-name a',
                                  'title': '.view-display-id-block_1 .view-content .views-row'},
                    'name_flip': True,
                    'paginate': {'param': 'page', 'start': 1, 'max': 4}}},
        {'short': 'EPI',
         'name': 'Department of Epidemiology',
         'majors': ['Epidemiology', 'Public Health', 'Biostatistics', 'Global Health'],
         'directory_url': 'https://epi.washington.edu/faculty/',
         # The p.fac-ri research field is prose sentences ("Improving engagement
         # in care among people living with HIV."), not clean keyword tags, so it
         # is intentionally NOT scraped — department majors drive matching.
         'scrape': {'url': 'https://epi.washington.edu/faculty/',
                    'selectors': {'card': 'div.faculty-tile',
                                  'name': 'h3 a',
                                  'link': 'h3 a',
                                  'title': 'p.fac-title em',
                                  'email': 'p.fac-email a.email_addr'},
                    'name_flip': True,
                    'ladder_filter': {'require': 'professor', 'drop': 'emerit'}}},
        {'short': 'GENOME',
         'name': 'Department of Genome Sciences',
         'majors': ['Genome Sciences',
                    'Genetics',
                    'Bioinformatics',
                    'Computational Biology',
                    'Molecular Biology',
                    'Biology'],
         'directory_url': 'https://www.gs.washington.edu/about/directory/faculty/',
         'api': {'type': 'wp',
                 'base': 'https://www.gs.washington.edu',
                 'post_type': 'profile',
                 'category_include': {'profile-type': [13, 17, 15]},
                 'category_exclude': {'profile-type': [16, 14]}}},
        {'short': 'MICRO',
         'name': 'Department of Microbiology',
         'majors': ['Microbiology',
                    'Molecular Microbiology',
                    'Immunology',
                    'Microbiology, Immunology & Molecular Pathogenesis'],
         'directory_url': 'https://microbiology.washington.edu/faculty/',
         'scrape': {'url': 'https://microbiology.washington.edu/faculty/',
                    'selectors': {'card': 'div.views-row',
                                  'name': 'a.faculty-link',
                                  'link': 'a.faculty-link',
                                  'title': '.views-field-field-user-title-one .field-content',
                                  'research': '.views-field-field-user-research-topics .field-content'},
                    'link_filter': '/people/faculty/',
                    'ladder_filter': {'drop': 'emerit|adjunct|affiliate'},
                    'field_filter': {'selector': '.views-field-field-user-dept-one .field-content',
                                     'include': 'microbiology'}}},
        {'short': 'ARCH',
         'name': 'Department of Architecture',
         'majors': ['Architecture'],
         'directory_url': 'https://arch.be.uw.edu/people/',
         'scrape': {'url': 'https://arch.be.uw.edu/people/',
                    'selectors': {'card': 'article.people.role-faculty',
                                  'name': 'span a[href*="/people/"]',
                                  'link': 'span a[href*="/people/"]',
                                  'name_strip': ',\\s*(?:Chair|Director|Dean|Head|Coordinator|Interim).*$'}}},
    ],
}


def fetch_and_normalize(deep: bool = True) -> list[dict]:
    """Wrapper bound to SCHOOL so refresh_all can call it like a collector."""
    return faculty_graph.fetch_and_normalize(SCHOOL, deep=deep)


def merge_into_processed(opps: list[dict]):
    return faculty_graph.merge_into_processed(opps)
