"""UW-Madison faculty config (via the faculty_graph engine).

Scrape-first, like the other peer schools. UW-Madison's departments run
different CMSes; this covers each via the cleanest source it exposes:

  * **Computer Science** (``www.cs.wisc.edu/people/faculty-2/``) — a
    ``faculty-member-content`` grid with name + public mailto inline.
  * **ECE / Mechanical / Biomedical Engineering** — the College of Engineering's
    shared ``directory.engr.wisc.edu/<dept>/`` lists faculty and staff together
    in ``div.profileDisplay`` cards; a ``link_filter`` keeps only the ``/Faculty/``
    profile links (the staff carry ``/Staff/``), with public emails inline.
  * **Mathematics** — a WordPress ``uw_staff`` post type filtered to the
    Professor / Associate / Assistant ``uw_staff_type`` terms (name un-inverted
    from "Last, First").
  * **Physics / Statistics** — the same ``faculty-member-content`` theme on a
    single page. Physics' ``/people/faculty/`` is faculty-only (Chair + the
    Department & Affiliated Faculty), so a flat card scrape lands all of it.
    Statistics lists Faculty, Teaching Faculty, Affiliate, and Emeritus on one
    page with no per-card class or rank that separates them (an Affiliate carries
    a real "Professor, <other dept>" title), so a ``section_filter`` keeps only
    the cards under the ``Faculty`` heading; names un-inverted from "Last, First".

The engineering, L&S, CALS, Business, Education, professional, Human Ecology,
Nelson and Veterinary Medicine departments below extend that base to UIUC-parity
coverage across all of UW-Madison's colleges. (The College of Engineering's home
tenure-track rosters live on ``engineering.wisc.edu/.../people/``, not the older
``directory.engr.wisc.edu`` pages, which serve only adjuncts/affiliates to a
stdlib scraper.)

Deferred: Chemistry (an AWS load-balancer bot-challenge returns an empty body) —
needs the headless path.

Single source ("wisc_faculty"); department rides each record's ``department``,
ids namespaced by department short-code. Audience "unknown".
"""

from __future__ import annotations

from .. import faculty_graph


# College of Engineering shared directory: faculty and staff share the page, so
# keep only the /Faculty/ profile links; the profileSubText cell is contact info
# (not research), so these land as emailed name+title cold-email targets.
def _engr(short: str, name: str, majors: list[str], code: str) -> dict:
    url = f"https://directory.engr.wisc.edu/{code}/"
    return {"short": short, "name": name, "majors": majors, "directory_url": url,
            "scrape": {"url": url, "link_filter": r"/Faculty/",
                       "selectors": {"card": "div.profileDisplay",
                                     "name": "h3.display a.display",
                                     "link": "h3.display a.display",
                                     "title": "p.title",
                                     "email": "a[href^='mailto:']"}}}


SCHOOL: dict = {
    "school_slug": "wisc",
    "source": "wisc_faculty",
    "organization": "University of Wisconsin-Madison",
    "location": "Madison, WI",
    "id_prefix": "wisc",
    "audience": "unknown",
    "work_auth_notes": (
        "External campus (UW-Madison) — work authorization depends on the "
        "arrangement; ask the professor."
    ),
    "departments": [
        {
            "short": "CS",
            "name": "Department of Computer Sciences",
            "majors": ["Computer Science", "Data Science"],
            "directory_url": "https://www.cs.wisc.edu/people/faculty-2/",
            "scrape": {
                "url": "https://www.cs.wisc.edu/people/faculty-2/",
                "selectors": {
                    "card": ".faculty-member-content",
                    "name": ".faculty-name a",
                    "link": ".faculty-name a",
                    "email": "a[href^='mailto:']",
                },
            },
        },
        _engr("ECE", "Department of Electrical & Computer Engineering",
              ["Electrical Engineering", "Computer Engineering"], "ece"),
        _engr("ME", "Department of Mechanical Engineering",
              ["Mechanical Engineering"], "me"),
        _engr("BME", "Department of Biomedical Engineering",
              ["Biomedical Engineering"], "bme"),
        {
            "short": "MATH",
            "name": "Department of Mathematics",
            "majors": ["Mathematics", "Applied Mathematics"],
            "directory_url": "https://www.math.wisc.edu/people/",
            "api": {"type": "wp", "base": "https://www.math.wisc.edu",
                    "post_type": "uw_staff",
                    "category_include": {"uw_staff_type": [20, 21, 22]},
                    "name_flip": True},
        },
        {
            "short": "PHYS",
            "name": "Department of Physics",
            "majors": ["Physics", "Applied Physics", "Astrophysics"],
            "directory_url": "https://www.physics.wisc.edu/people/faculty/",
            "scrape": {
                "url": "https://www.physics.wisc.edu/people/faculty/",
                "selectors": {"card": ".faculty-member-content",
                              "name": "h3 a", "link": "h3 a"},
            },
        },
        {
            "short": "STAT",
            "name": "Department of Statistics",
            "majors": ["Statistics", "Data Science"],
            "directory_url": "https://stat.wisc.edu/people/",
            "scrape": {
                "url": "https://stat.wisc.edu/people/",
                "name_flip": True,
                "section_filter": {"include": r"^faculty$"},
                "selectors": {"card": ".faculty-member-content",
                              "name": "h3 a", "link": "h3 a"},
            },
        },
        # --- Full-school coverage (Engineering, L&S, CALS, Business, Education, Professional, SoHE, Nelson, VetMed) ---
        {'short': 'AAE',
         'name': 'Department of Agricultural & Applied Economics',
         'majors': ['Agricultural and Applied Economics', 'Economics'],
         'directory_url': 'https://aae.wisc.edu/faculty/',
         'scrape': {'url': 'https://aae.wisc.edu/faculty/',
                    'ladder_filter': {'require': 'profess', 'drop': 'affiliate|faculty associate|emerit'},
                    'selectors': {'card': '.faculty-member-content',
                                  'name': 'h3 a',
                                  'link': 'h3 a',
                                  'title': 'p',
                                  'email': "a[href^='mailto:']"}}},
        {'short': 'ACCT',
         'name': 'Department of Accounting & Information Systems',
         'majors': ['Accounting', 'Information Systems'],
         'directory_url': 'https://business.wisc.edu/faculty-research/accounting-information-systems/faculty/',
         'scrape': {'url': 'https://business.wisc.edu/faculty-research/accounting-information-systems/faculty/',
                    'link_filter': '/directory/profile/',
                    'selectors': {'card': 'div.card.shadow',
                                  'name': 'h3.card-title',
                                  'link': 'a.card-link',
                                  'title': '.directory-title',
                                  'email': "a[href^='mailto:']"},
                    'ladder_filter': {'require': 'professor|chair|dean',
                                      'drop': 'teaching|lecturer|adjunct|emerit|clinical|of '
                                              'practice|director|assistant dean|associate dean for '
                                              'learning|associate dean for diversity'}}},
        {'short': 'ANTHRO',
         'name': 'Department of Anthropology',
         'majors': ['Anthropology'],
         'directory_url': 'https://www.anthropology.wisc.edu/faculty/',
         'scrape': {'url': 'https://www.anthropology.wisc.edu/faculty/',
                    'ladder_filter': {'require': 'profess', 'drop': 'emerit'},
                    'selectors': {'card': 'div.faculty-member-content',
                                  'name': 'h3.faculty-name a',
                                  'link': 'h3.faculty-name a',
                                  'title': 'p.position-title',
                                  'email': "a[href^='mailto:']"}}},
        {'short': 'AOS',
         'name': 'Department of Atmospheric and Oceanic Sciences',
         'majors': ['Atmospheric and Oceanic Sciences'],
         'directory_url': 'https://www.aos.wisc.edu/faculty/',
         'scrape': {'url': 'https://www.aos.wisc.edu/faculty/',
                    'section_filter': {'heading': 'h2', 'exclude': 'emerit|affiliate|adjunct'},
                    'selectors': {'card': 'td.aos-table-name',
                                  'name': 'b a',
                                  'link': 'b a',
                                  'email': "a[href^='mailto:']"}}},
        {'short': 'ARTHIST',
         'name': 'Department of Art History',
         'majors': ['Art History'],
         'directory_url': 'https://arthistory.wisc.edu/people/faculty/',
         'scrape': {'url': 'https://arthistory.wisc.edu/people/faculty/',
                    'selectors': {'card': '.faculty-member-content',
                                  'name': '.faculty-name a',
                                  'link': '.faculty-name a'}}},
        {'short': 'ASTRON',
         'name': 'Department of Astronomy',
         'majors': ['Astronomy-Physics', 'Astrophysics'],
         'directory_url': 'https://www.astro.wisc.edu/people/faculty/',
         'api': {'type': 'wp',
                 'base': 'https://www.astro.wisc.edu',
                 'post_type': 'uw_staff',
                 'category_include': {'uw_staff_type': [8]},
                 'name_flip': True}},
        {'short': 'BACT',
         'name': 'Department of Bacteriology',
         'majors': ['Microbiology', 'Bacteriology'],
         'directory_url': 'https://bact.wisc.edu/people/',
         'scrape': {'url': 'https://bact.wisc.edu/people/',
                    'selectors': {'card': 'li.research-faculty, li.teaching-faculty',
                                  'name': '.name',
                                  'link': 'a.biocardLink',
                                  'title': 'em.jobtitle',
                                  'email': "a[href^='mailto:']"}}},
        {'short': 'BIOCHEM',
         'name': 'Department of Biochemistry',
         'majors': ['Biochemistry'],
         'directory_url': 'https://biochem.wisc.edu/faculty',
         'scrape': {'url': 'https://biochem.wisc.edu/faculty',
                    'selectors': {'card': '.faculty-member-content',
                                  'name': 'h3.faculty-name a',
                                  'link': 'h3.faculty-name a',
                                  'research': 'p.bio'}}},
        {'short': 'BOTANY',
         'name': 'Department of Botany',
         'majors': ['Botany', 'Plant Biology'],
         'directory_url': 'https://botany.wisc.edu/botany-faculty/',
         'scrape': {'url': 'https://botany.wisc.edu/botany-faculty/',
                    'section_filter': {'heading': 'h2', 'include': 'botany faculty'},
                    'selectors': {'card': '.faculty-member-content',
                                  'name': '.faculty-name a',
                                  'link': '.faculty-name a',
                                  'email': "a[href^='mailto:']"}}},
        {'short': 'BSE',
         'name': 'Department of Biological Systems Engineering',
         'majors': ['Biological Systems Engineering'],
         'directory_url': 'https://bse.wisc.edu/people/',
         'scrape': {'url': 'https://bse.wisc.edu/people/',
                    'section_filter': {'include': '^core faculty$', 'heading': 'h2'},
                    'selectors': {'card': '.faculty-member-content',
                                  'name': 'h3.faculty-name a',
                                  'link': 'h3.faculty-name a'}}},
        {'short': 'CBE',
         'name': 'Department of Chemical & Biological Engineering',
         'majors': ['Chemical Engineering'],
         'directory_url': 'https://engineering.wisc.edu/departments/chemical-biological-engineering/people/',
         'scrape': {'url': 'https://engineering.wisc.edu/departments/chemical-biological-engineering/people/',
                    'ladder_filter': {'drop': 'emerit|adjunct|lecturer|teaching faculty|postdoc|of '
                                              'practice|honorary|visiting|clinical|affiliate'},
                    'selectors': {'card': '.acf-person-card',
                                  'name': '.name a',
                                  'name_strip': ' (?= )',
                                  'link': '.name a',
                                  'title': '.title',
                                  'email': ".email a[href^='mailto:']"}}},
        {'short': 'CEE',
         'name': 'Department of Civil & Environmental Engineering',
         'majors': ['Civil Engineering', 'Environmental Engineering'],
         'directory_url': 'https://engineering.wisc.edu/departments/civil-environmental-engineering/people/',
         'scrape': {'url': 'https://engineering.wisc.edu/departments/civil-environmental-engineering/people/',
                    'ladder_filter': {'drop': 'emerit|adjunct|lecturer|teaching faculty|postdoc|of '
                                              'practice|honorary|visiting|clinical|affiliate'},
                    'selectors': {'card': '.acf-person-card',
                                  'name': '.name a',
                                  'name_strip': ' (?= )',
                                  'link': '.name a',
                                  'title': '.title',
                                  'email': ".email a[href^='mailto:']"}}},
        {'short': 'CI',
         'name': 'Department of Curriculum & Instruction',
         'majors': ['Curriculum & Instruction'],
         'directory_url': 'https://ci.education.wisc.edu/people/',
         'scrape': {'url': 'https://ci.education.wisc.edu/people/',
                    'selectors': {'card': 'div.uw-person-wrapper',
                                  'name': 'a.dm-faculty-name',
                                  'link': 'a.dm-faculty-name',
                                  'title': 'div.uw-person-txt-wrapper p'},
                    'ladder_filter': {'require': 'professor',
                                      'drop': 'emerit|adjunct|affiliate|honorary|clinical|visiting|teaching|lecturer|of '
                                              'practice'}}},
        {'short': 'COMMARTS',
         'name': 'Department of Communication Arts',
         'majors': ['Communication Arts', 'Communication Sciences & Disorders'],
         'directory_url': 'https://commarts.wisc.edu/people/',
         'scrape': {'url': 'https://commarts.wisc.edu/people/',
                    'section_filter': {'include': '^(department leadership|faculty)$',
                                       'exclude': 'affiliate|emeriti|staff|student|instructor',
                                       'heading': 'h2'},
                    'selectors': {'card': 'div.faculty-member-content',
                                  'name': 'h3 a',
                                  'link': 'h3 a',
                                  'email': "a[href^='mailto:']"}}},
        {'short': 'CONSCI',
         'name': 'Department of Consumer Science',
         'majors': ['Consumer Behavior and Marketplace Studies', 'Personal Finance'],
         'directory_url': 'https://humanecology.wisc.edu/academics/departments/consumer-science/',
         'scrape': {'url': 'https://humanecology.wisc.edu/academics/departments/consumer-science/',
                    'ladder_filter': {'require': '\\bprofessor\\b',
                                      'drop': 'teaching|emerit|adjunct|lecturer|instructor|visiting|affiliate'},
                    'selectors': {'card': '.sohe-staff-cards li',
                                  'name': 'a.sohe-fs-search-content',
                                  'link': 'a.sohe-fs-search-content',
                                  'title': 'h3 span'}}},
        {'short': 'CPSYCH',
         'name': 'Department of Counseling Psychology',
         'majors': ['Counseling Psychology'],
         'directory_url': 'https://counselingpsych.education.wisc.edu/people/',
         'scrape': {'url': 'https://counselingpsych.education.wisc.edu/people/',
                    'selectors': {'card': 'div.uw-person-wrapper',
                                  'name': 'a.dm-faculty-name',
                                  'link': 'a.dm-faculty-name',
                                  'title': 'div.uw-person-txt-wrapper p'},
                    'ladder_filter': {'require': 'professor',
                                      'drop': 'emerit|adjunct|affiliate|honorary|clinical|visiting|teaching|lecturer|of '
                                              'practice'}}},
        {'short': 'CSCS',
         'name': 'Department of Civil Society & Community Studies',
         'majors': ['Community and Organizational Development'],
         'directory_url': 'https://humanecology.wisc.edu/academics/departments/civil-society-community-studies/',
         'scrape': {'url': 'https://humanecology.wisc.edu/academics/departments/civil-society-community-studies/',
                    'ladder_filter': {'require': '\\bprofessor\\b',
                                      'drop': 'teaching|emerit|adjunct|lecturer|instructor|visiting|affiliate'},
                    'selectors': {'card': '.sohe-staff-cards li',
                                  'name': 'a.sohe-fs-search-content',
                                  'link': 'a.sohe-fs-search-content',
                                  'title': 'h3 span'}}},
        {'short': 'DS',
         'name': 'Department of Design Studies',
         'majors': ['Textiles and Fashion Design', 'Interior Architecture'],
         'directory_url': 'https://humanecology.wisc.edu/academics/departments/design-studies/',
         'scrape': {'url': 'https://humanecology.wisc.edu/academics/departments/design-studies/',
                    'ladder_filter': {'require': '\\bprofessor\\b',
                                      'drop': 'teaching|emerit|adjunct|lecturer|instructor|visiting|affiliate'},
                    'selectors': {'card': '.sohe-staff-cards li',
                                  'name': 'a.sohe-fs-search-content',
                                  'link': 'a.sohe-fs-search-content',
                                  'title': 'h3 span'}}},
        {'short': 'ECON',
         'name': 'Department of Economics',
         'majors': ['Economics', 'Mathematical Economics'],
         'directory_url': 'https://econ.wisc.edu/faculty/',
         'scrape': {'url': 'https://econ.wisc.edu/faculty/',
                    'ladder_filter': {'require': 'profess', 'drop': 'lecturer|faculty associate|emerit'},
                    'selectors': {'card': 'div.faculty-member-content',
                                  'name': 'h3.faculty-name a',
                                  'link': 'h3.faculty-name a',
                                  'title': 'p.position-title',
                                  'email': "a[href^='mailto:']"}}},
        {'short': 'EDPSYCH',
         'name': 'Department of Educational Psychology',
         'majors': ['Educational Psychology'],
         'directory_url': 'https://edpsych.education.wisc.edu/people/',
         'scrape': {'url': 'https://edpsych.education.wisc.edu/people/',
                    'selectors': {'card': 'div.uw-person-wrapper',
                                  'name': 'a.dm-faculty-name',
                                  'link': 'a.dm-faculty-name',
                                  'title': 'div.uw-person-txt-wrapper p'},
                    'ladder_filter': {'require': 'professor',
                                      'drop': 'emerit|adjunct|affiliate|honorary|clinical|visiting|teaching|lecturer|of '
                                              'practice'}}},
        {'short': 'ELPA',
         'name': 'Department of Educational Leadership & Policy Analysis',
         'majors': ['Educational Leadership & Policy Analysis'],
         'directory_url': 'https://elpa.education.wisc.edu/people/',
         'scrape': {'url': 'https://elpa.education.wisc.edu/people/',
                    'selectors': {'card': 'div.uw-person-wrapper',
                                  'name': 'a.dm-faculty-name',
                                  'link': 'a.dm-faculty-name',
                                  'title': 'div.uw-person-txt-wrapper p'},
                    'ladder_filter': {'require': 'professor',
                                      'drop': 'emerit|adjunct|affiliate|honorary|clinical|visiting|teaching|lecturer|of '
                                              'practice'}}},
        {'short': 'ENGL',
         'name': 'Department of English',
         'majors': ['English', 'Creative Writing'],
         'directory_url': 'https://english.wisc.edu/people/faculty/',
         'scrape': {'url': 'https://english.wisc.edu/people/faculty/',
                    'selectors': {'card': '.faculty-member-content',
                                  'name': '.faculty-name a',
                                  'link': '.faculty-name a',
                                  'email': "a[href^='mailto:']"}}},
        {'short': 'ENTOM',
         'name': 'Department of Entomology',
         'majors': ['Entomology'],
         'directory_url': 'https://entomology.wisc.edu/people/faculty/',
         'scrape': {'url': 'https://entomology.wisc.edu/people/faculty/',
                    'selectors': {'card': 'li.faculty',
                                  'name': 'div.name a',
                                  'link': 'div.name a',
                                  'title': 'em.jobtitle',
                                  'email': "div.email a[href^='mailto:']"}}},
        {'short': 'EP',
         'name': 'Department of Engineering Physics',
         'majors': ['Engineering Physics', 'Nuclear Engineering', 'Engineering Mechanics'],
         'directory_url': 'https://engineering.wisc.edu/departments/nuclear-engineering-engineering-physics/people/',
         'scrape': {'url': 'https://engineering.wisc.edu/departments/nuclear-engineering-engineering-physics/people/',
                    'ladder_filter': {'drop': 'emerit|adjunct|lecturer|teaching faculty|postdoc|of '
                                              'practice|honorary|visiting|clinical|affiliate'},
                    'selectors': {'card': '.acf-person-card',
                                  'name': '.name a',
                                  'name_strip': ' (?= )',
                                  'link': '.name a',
                                  'title': '.title',
                                  'email': ".email a[href^='mailto:']"}}},
        {'short': 'EPS',
         'name': 'Department of Educational Policy Studies',
         'majors': ['Educational Policy Studies'],
         'directory_url': 'https://eps.education.wisc.edu/people/',
         'api': {'type': 'wp',
                 'base': 'https://eps.education.wisc.edu',
                 'post_type': 'uw_staff',
                 'category_include': {'uw_staff_type': [37]},
                 'name_flip': True}},
        {'short': 'FIN',
         'name': 'Department of Finance, Investment Banking & Banking',
         'majors': ['Finance'],
         'directory_url': 'https://business.wisc.edu/faculty-research/finance-investment-banking/faculty/',
         'scrape': {'url': 'https://business.wisc.edu/faculty-research/finance-investment-banking/faculty/',
                    'link_filter': '/directory/profile/',
                    'selectors': {'card': 'div.card.shadow',
                                  'name': 'h3.card-title',
                                  'link': 'a.card-link',
                                  'title': '.directory-title',
                                  'email': "a[href^='mailto:']"},
                    'ladder_filter': {'require': 'professor|chair|dean',
                                      'drop': 'teaching|lecturer|adjunct|emerit|clinical|of '
                                              'practice|director|assistant dean|associate dean for '
                                              'learning|associate dean for diversity'}}},
        {'short': 'FOODSCI',
         'name': 'Department of Food Science',
         'majors': ['Food Science'],
         'directory_url': 'https://foodsci.wisc.edu/faculty/',
         'scrape': {'url': 'https://foodsci.wisc.edu/faculty/',
                    'selectors': {'card': 'div.ds-people-block div.flex.items-center',
                                  'name': 'h3.name a',
                                  'link': 'h3.name a',
                                  'title': 'h4.job'}}},
        {'short': 'FWE',
         'name': 'Department of Forest & Wildlife Ecology',
         'majors': ['Forest Science', 'Wildlife Ecology'],
         'directory_url': 'https://forestandwildlifeecology.wisc.edu/people/faculty-and-staff/',
         'scrape': {'url': 'https://forestandwildlifeecology.wisc.edu/people/faculty-and-staff/',
                    'ladder_filter': {'require': 'profess', 'drop': 'emerit'},
                    'selectors': {'card': 'div.flex-rightCol',
                                  'name': 'h2 strong',
                                  'title': 'p',
                                  'title_strip_after': 'Phone|Email|Expertise',
                                  'email': "a[href^='mailto:']"}}},
        {'short': 'GEN',
         'name': 'Department of Genetics',
         'majors': ['Genetics', 'Biology'],
         'directory_url': 'https://genetics.wisc.edu/genetics-faculty/',
         'scrape': {'url': 'https://genetics.wisc.edu/genetics-faculty/',
                    'section_filter': {'exclude': 'affiliate|emerit', 'heading': 'h2'},
                    'selectors': {'card': '.faculty-member-content',
                                  'name': 'h3.faculty-name a',
                                  'link': 'h3.faculty-name a'}}},
        {'short': 'GEO',
         'name': 'Department of Geoscience',
         'majors': ['Geology and Geophysics', 'Geoscience'],
         'directory_url': 'https://geoscience.wisc.edu/people/',
         'scrape': {'url': 'https://geoscience.wisc.edu/people/',
                    'selectors': {'card': 'li[data-uw_staff_type~="faculty"]',
                                  'name': 'h2 a',
                                  'link': 'h2 a',
                                  'title': 'h2 span'}}},
        {'short': 'GEOG',
         'name': 'Department of Geography',
         'majors': ['Geography', 'Cartography & GIS'],
         'directory_url': 'https://geography.wisc.edu/people/faculty/',
         'scrape': {'url': 'https://geography.wisc.edu/people/faculty/',
                    'ladder_filter': {'require': 'profess',
                                      'drop': 'senior scientist|faculty associate|lecturer|emerit'},
                    'selectors': {'card': 'div.faculty-member-content',
                                  'name': 'h3.faculty-name a',
                                  'link': 'h3.faculty-name a',
                                  'title': 'p.position-title',
                                  'email': "a[href^='mailto:']"}}},
        {'short': 'HDFS',
         'name': 'Department of Human Development & Family Studies',
         'majors': ['Human Development and Family Studies'],
         'directory_url': 'https://humanecology.wisc.edu/academics/departments/human-development-family-studies/',
         'scrape': {'url': 'https://humanecology.wisc.edu/academics/departments/human-development-family-studies/',
                    'ladder_filter': {'require': '\\bprofessor\\b',
                                      'drop': 'teaching|emerit|adjunct|lecturer|instructor|visiting|affiliate'},
                    'selectors': {'card': '.sohe-staff-cards li',
                                  'name': 'a.sohe-fs-search-content',
                                  'link': 'a.sohe-fs-search-content',
                                  'title': 'h3 span'}}},
        {'short': 'HIST',
         'name': 'Department of History',
         'majors': ['History'],
         'directory_url': 'https://history.wisc.edu/faculty/',
         'scrape': {'url': 'https://history.wisc.edu/faculty/',
                    'selectors': {'card': '.faculty-member-content',
                                  'name': '.faculty-name a',
                                  'link': '.faculty-name a'}}},
        {'short': 'IBIO',
         'name': 'Department of Integrative Biology',
         'majors': ['Biology', 'Zoology', 'Botany'],
         'directory_url': 'https://integrativebiology.wisc.edu/faculty/',
         'scrape': {'url': 'https://integrativebiology.wisc.edu/faculty/',
                    'selectors': {'card': '.faculty-member-content',
                                  'name': '.faculty-name a',
                                  'link': '.faculty-name a',
                                  'title': '.faculty-credentials'}}},
        {'short': 'IE',
         'name': 'Department of Industrial & Systems Engineering',
         'majors': ['Industrial Engineering', 'Systems Engineering'],
         'directory_url': 'https://engineering.wisc.edu/departments/industrial-systems-engineering/people/',
         'scrape': {'url': 'https://engineering.wisc.edu/departments/industrial-systems-engineering/people/',
                    'ladder_filter': {'drop': 'emerit|adjunct|lecturer|teaching faculty|postdoc|of '
                                              'practice|honorary|visiting|clinical|affiliate'},
                    'selectors': {'card': '.acf-person-card',
                                  'name': '.name a',
                                  'name_strip': ' (?= )',
                                  'link': '.name a',
                                  'title': '.title',
                                  'email': ".email a[href^='mailto:']"}}},
        {'short': 'KINES',
         'name': 'Department of Kinesiology',
         'majors': ['Kinesiology', 'Athletic Training'],
         'directory_url': 'https://kinesiology.education.wisc.edu/people/',
         'scrape': {'url': 'https://kinesiology.education.wisc.edu/people/',
                    'selectors': {'card': 'div.uw-person-wrapper',
                                  'name': 'a.dm-faculty-name',
                                  'link': 'a.dm-faculty-name',
                                  'title': 'div.uw-person-txt-wrapper p'},
                    'ladder_filter': {'require': 'professor',
                                      'drop': 'emerit|adjunct|affiliate|honorary|clinical|visiting|teaching|lecturer|of '
                                              'practice'}}},
        {'short': 'LAW',
         'name': 'Law School',
         'majors': ['Law'],
         'directory_url': 'https://law.wisc.edu/directory/',
         'scrape': {'url': 'https://law.wisc.edu/directory/',
                    'link_filter': '/profiles/',
                    'ladder_filter': {'require': 'profess', 'drop': 'emerit'},
                    'selectors': {'card': 'div.card.profile-card',
                                  'name': 'h3.card-title',
                                  'link': 'a',
                                  'title': 'p.card-text'}}},
        {'short': 'MHR',
         'name': 'Department of Management & Human Resources',
         'majors': ['Management', 'Human Resources'],
         'directory_url': 'https://business.wisc.edu/faculty-research/management-human-resources/faculty/',
         'scrape': {'url': 'https://business.wisc.edu/faculty-research/management-human-resources/faculty/',
                    'link_filter': '/directory/profile/',
                    'selectors': {'card': 'div.card.shadow',
                                  'name': 'h3.card-title',
                                  'link': 'a.card-link',
                                  'title': '.directory-title',
                                  'email': "a[href^='mailto:']"},
                    'ladder_filter': {'require': 'professor|chair|dean',
                                      'drop': 'teaching|lecturer|adjunct|emerit|clinical|of '
                                              'practice|director|assistant dean|associate dean for '
                                              'learning|associate dean for diversity'}}},
        {'short': 'MKTG',
         'name': 'Department of Marketing',
         'majors': ['Marketing'],
         'directory_url': 'https://business.wisc.edu/faculty-research/marketing/faculty/',
         'scrape': {'url': 'https://business.wisc.edu/faculty-research/marketing/faculty/',
                    'link_filter': '/directory/profile/',
                    'selectors': {'card': 'div.card.shadow',
                                  'name': 'h3.card-title',
                                  'link': 'a.card-link',
                                  'title': '.directory-title',
                                  'email': "a[href^='mailto:']"},
                    'ladder_filter': {'require': 'professor|chair|dean',
                                      'drop': 'teaching|lecturer|adjunct|emerit|clinical|of '
                                              'practice|director|assistant dean|associate dean for '
                                              'learning|associate dean for diversity'}}},
        {'short': 'MSE',
         'name': 'Department of Materials Science & Engineering',
         'majors': ['Materials Science & Engineering'],
         'directory_url': 'https://engineering.wisc.edu/departments/materials-science-engineering/people/',
         'scrape': {'url': 'https://engineering.wisc.edu/departments/materials-science-engineering/people/',
                    'ladder_filter': {'drop': 'emerit|adjunct|lecturer|teaching faculty|postdoc|of '
                                              'practice|honorary|visiting|clinical|affiliate'},
                    'selectors': {'card': '.acf-person-card',
                                  'name': '.name a',
                                  'name_strip': ' (?= )',
                                  'link': '.name a',
                                  'title': '.title',
                                  'email': ".email a[href^='mailto:']"}}},
        {'short': 'NELSON',
         'name': 'Nelson Institute for Environmental Studies',
         'majors': ['Environmental Studies', 'Environmental Sciences', 'Conservation Biology'],
         'directory_url': 'https://nelson.wisc.edu/people/faculty/',
         'scrape': {'url': 'https://nelson.wisc.edu/people/faculty/',
                    'section_filter': {'include': '^faculty$', 'heading': 'h2'},
                    'selectors': {'card': '.faculty-member-content',
                                  'name': 'h3.faculty-name',
                                  'email': "a[href^='mailto:']"}}},
        {'short': 'NURS',
         'name': 'School of Nursing',
         'majors': ['Nursing'],
         'directory_url': 'https://nursing.wisc.edu/directory/faculty/',
         'scrape': {'url': 'https://nursing.wisc.edu/directory/faculty/',
                    'link_filter': '/staff/',
                    'ladder_filter': {'require': 'profess', 'drop': 'emerit'},
                    'selectors': {'card': '.faculty-member-content',
                                  'name': '.faculty-name a',
                                  'link': '.faculty-name a',
                                  'title': 'p.position-title',
                                  'email': "a[href^='mailto:']"}}},
        {'short': 'NUTRSCI',
         'name': 'Department of Nutritional Sciences',
         'majors': ['Nutritional Sciences', 'Dietetics'],
         'directory_url': 'https://nutrisci.wisc.edu/people/faculty-staff/',
         'scrape': {'url': 'https://nutrisci.wisc.edu/people/faculty-staff/',
                    'selectors': {'card': 'li.dept-faculty',
                                  'name': 'div.name',
                                  'link': 'a.biocardLink',
                                  'title': 'em.jobtitle',
                                  'email': "div.email a[href^='mailto:']"}}},
        {'short': 'OTM',
         'name': 'Department of Operations & Information Management',
         'majors': ['Operations Management', 'Information Systems'],
         'directory_url': 'https://business.wisc.edu/faculty-research/operations-information-management/faculty/',
         'scrape': {'url': 'https://business.wisc.edu/faculty-research/operations-information-management/faculty/',
                    'link_filter': '/directory/profile/',
                    'selectors': {'card': 'div.card.shadow',
                                  'name': 'h3.card-title',
                                  'link': 'a.card-link',
                                  'title': '.directory-title',
                                  'email': "a[href^='mailto:']"},
                    'ladder_filter': {'require': 'professor|chair|dean',
                                      'drop': 'teaching|lecturer|adjunct|emerit|clinical|of '
                                              'practice|director|assistant dean|associate dean for '
                                              'learning|associate dean for diversity'}}},
        {'short': 'PAS',
         'name': 'Department of Plant and Agroecosystem Sciences',
         'majors': ['Agronomy', 'Horticulture', 'Plant Sciences'],
         'directory_url': 'https://pasdept.wisc.edu/people/faculty/',
         'scrape': {'url': 'https://pasdept.wisc.edu/people/faculty/',
                    'selectors': {'card': 'li.faculty',
                                  'name': 'div.name',
                                  'link': 'a.biocardLink',
                                  'title': 'em.jobtitle',
                                  'email': "div.email a[href^='mailto:']"}}},
        {'short': 'PHARMSCI',
         'name': 'School of Pharmacy — Pharmaceutical Sciences Division',
         'majors': ['Pharmaceutical Sciences', 'Pharmacology', 'Pharmacy'],
         'directory_url': 'https://pharmacy.wisc.edu/research-and-faculty-labs/pharmaceutical-sciences-research/',
         'scrape': {'url': 'https://pharmacy.wisc.edu/research-and-faculty-labs/pharmaceutical-sciences-research/',
                    'link_filter': 'sopdir/',
                    'section_filter': {'include': 'faculty',
                                       'exclude': 'affiliate|emeritus',
                                       'heading': 'h2'},
                    'selectors': {'card': 'dt', 'name': 'a strong', 'link': 'a'}}},
        {'short': 'PHIL',
         'name': 'Department of Philosophy',
         'majors': ['Philosophy'],
         'directory_url': 'https://philosophy.wisc.edu/people/faculty/',
         'scrape': {'url': 'https://philosophy.wisc.edu/people/faculty/',
                    'section_filter': {'exclude': 'emerit|affiliate|postdoc'},
                    'selectors': {'card': '.faculty-member-content',
                                  'name': '.faculty-name a',
                                  'link': '.faculty-name a',
                                  'email': "a[href^='mailto:']"}}},
        {'short': 'PLPATH',
         'name': 'Department of Plant Pathology',
         'majors': ['Plant Pathology', 'Plant Sciences'],
         'directory_url': 'https://plantpath.wisc.edu/faculty/',
         'scrape': {'url': 'https://plantpath.wisc.edu/faculty/',
                    'selectors': {'card': 'ul.flexbox-container li.page_item',
                                  'name': 'div.heading',
                                  'link': 'a'}}},
        {'short': 'POLISCI',
         'name': 'Department of Political Science',
         'majors': ['Political Science', 'International Studies'],
         'directory_url': 'https://polisci.wisc.edu/faculty/',
         'scrape': {'url': 'https://polisci.wisc.edu/faculty/',
                    'ladder_filter': {'require': 'profess', 'drop': 'emerit'},
                    'selectors': {'card': 'div.faculty-member-content',
                                  'name': 'h3.faculty-name a',
                                  'link': 'h3.faculty-name a',
                                  'email': "a[href^='mailto:']"}}},
        {'short': 'PSYCH',
         'name': 'Department of Psychology',
         'majors': ['Psychology'],
         'directory_url': 'https://psych.wisc.edu/people/',
         'scrape': {'url': 'https://psych.wisc.edu/people/',
                    'ladder_filter': {'require': 'profess', 'drop': 'emerit'},
                    'selectors': {'card': 'div.faculty-member-content',
                                  'name': 'h3.faculty-name a',
                                  'link': 'h3.faculty-name a',
                                  'title': 'p.position-title',
                                  'email': "a[href^='mailto:']"}}},
        {'short': 'PUBAFF',
         'name': 'La Follette School of Public Affairs',
         'majors': ['Public Affairs', 'Public Policy'],
         'directory_url': 'https://lafollette.wisc.edu/about/faculty-and-staff/',
         'scrape': {'url': 'https://lafollette.wisc.edu/about/faculty-and-staff/',
                    'link_filter': '/people/',
                    'ladder_filter': {'require': 'profess', 'drop': 'emerit|adjunct'},
                    'selectors': {'card': '.faculty-member-content',
                                  'name': '.faculty-name a',
                                  'link': '.faculty-name a',
                                  'title': 'p.faculty-credentials',
                                  'email': "a[href^='mailto:']"}}},
        {'short': 'RE',
         'name': 'Department of Real Estate & Urban Land Economics',
         'majors': ['Real Estate'],
         'directory_url': 'https://business.wisc.edu/faculty-research/real-estate/faculty/',
         'scrape': {'url': 'https://business.wisc.edu/faculty-research/real-estate/faculty/',
                    'link_filter': '/directory/profile/',
                    'selectors': {'card': 'div.card.shadow',
                                  'name': 'h3.card-title',
                                  'link': 'a.card-link',
                                  'title': '.directory-title',
                                  'email': "a[href^='mailto:']"},
                    'ladder_filter': {'require': 'professor|chair|dean',
                                      'drop': 'teaching|lecturer|adjunct|emerit|clinical|of '
                                              'practice|director|assistant dean|associate dean for '
                                              'learning|associate dean for diversity'}}},
        {'short': 'RMI',
         'name': 'Department of Risk & Insurance',
         'majors': ['Risk Management & Insurance', 'Actuarial Science'],
         'directory_url': 'https://business.wisc.edu/faculty-research/risk-insurance/faculty/',
         'scrape': {'url': 'https://business.wisc.edu/faculty-research/risk-insurance/faculty/',
                    'link_filter': '/directory/profile/',
                    'selectors': {'card': 'div.card.shadow',
                                  'name': 'h3.card-title',
                                  'link': 'a.card-link',
                                  'title': '.directory-title',
                                  'email': "a[href^='mailto:']"},
                    'ladder_filter': {'require': 'professor|chair|dean',
                                      'drop': 'teaching|lecturer|adjunct|emerit|clinical|of '
                                              'practice|director|assistant dean|associate dean for '
                                              'learning|associate dean for diversity'}}},
        {'short': 'RPSE',
         'name': 'Department of Rehabilitation Psychology & Special Education',
         'majors': ['Special Education', 'Rehabilitation Psychology'],
         'directory_url': 'https://rpse.education.wisc.edu/people/',
         'scrape': {'url': 'https://rpse.education.wisc.edu/people/',
                    'selectors': {'card': 'div.uw-person-wrapper',
                                  'name': 'a.dm-faculty-name',
                                  'link': 'a.dm-faculty-name',
                                  'title': 'div.uw-person-txt-wrapper p'},
                    'ladder_filter': {'require': 'professor',
                                      'drop': 'emerit|adjunct|affiliate|honorary|clinical|visiting|teaching|lecturer|of '
                                              'practice'}}},
        {'short': 'SOC',
         'name': 'Department of Sociology',
         'majors': ['Sociology'],
         'directory_url': 'https://sociology.wisc.edu/faculty/',
         'scrape': {'url': 'https://sociology.wisc.edu/faculty/',
                    'name_flip': True,
                    'ladder_filter': {'require': 'profess', 'drop': 'lecturer|teaching faculty|emerit'},
                    'selectors': {'card': 'div.faculty-member-content',
                                  'name': 'h3.faculty-name a',
                                  'link': 'h3.faculty-name a',
                                  'title': 'p.position-title',
                                  'email': "a[href^='mailto:']"}}},
        {'short': 'SOILS',
         'name': 'Department of Soil & Environmental Sciences',
         'majors': ['Soil Science', 'Environmental Sciences'],
         'directory_url': 'https://soilenvsci.wisc.edu/people/faculty/',
         'scrape': {'url': 'https://soilenvsci.wisc.edu/people/faculty/',
                    'selectors': {'card': 'li.faculty-people',
                                  'name': 'div.name',
                                  'link': 'a.biocardLink',
                                  'title': 'em.jobtitle',
                                  'email': "div.email a[href^='mailto:']"}}},
        {'short': 'SPANPORT',
         'name': 'Department of Spanish & Portuguese',
         'majors': ['Spanish', 'Portuguese'],
         'directory_url': 'https://spanport.wisc.edu/faculty/',
         'api': {'type': 'wp',
                 'base': 'https://spanport.wisc.edu',
                 'post_type': 'uw_staff',
                 'category_include': {'uw_staff_type': [11]},
                 'name_flip': True}},
        {'short': 'SW',
         'name': 'Sandra Rosenbaum School of Social Work',
         'majors': ['Social Work'],
         'directory_url': 'https://socwork.wisc.edu/directory-faculty/',
         'api': {'type': 'wp',
                 'base': 'https://socwork.wisc.edu',
                 'post_type': 'uw_staff',
                 'category_include': {'uw_staff_type': [9, 11]},
                 'name_flip': True,
                 'profile_enrich': {'position_re': '(?:Distinguished |Clinical )?(?:Assistant |Associate '
                                                   ')?Professor(?: of [A-Za-z ]{3,40})?|Faculty '
                                                   'Affiliate',
                                    'require_professor': True}}},
        {'short': 'VMCBS',
         'name': 'Department of Comparative Biosciences',
         'majors': ['Veterinary Medicine', 'Biology', 'Neuroscience'],
         'directory_url': 'https://www.vetmed.wisc.edu/people/',
         'scrape': {'url': 'https://www.vetmed.wisc.edu/people/',
                    'selectors': {'card': '.faculty-member.type-cbs.type-faculty',
                                  'name': 'h3 a',
                                  'link': 'h3 a',
                                  'email': "a[href^='mailto:']"}}},
        {'short': 'VMDMS',
         'name': 'Department of Medical Sciences',
         'majors': ['Veterinary Medicine'],
         'directory_url': 'https://www.vetmed.wisc.edu/people/',
         'scrape': {'url': 'https://www.vetmed.wisc.edu/people/',
                    'selectors': {'card': '.faculty-member.type-dms.type-faculty',
                                  'name': 'h3 a',
                                  'link': 'h3 a',
                                  'email': "a[href^='mailto:']"}}},
        {'short': 'VMDSS',
         'name': 'Department of Surgical Sciences',
         'majors': ['Veterinary Medicine'],
         'directory_url': 'https://www.vetmed.wisc.edu/people/',
         'scrape': {'url': 'https://www.vetmed.wisc.edu/people/',
                    'selectors': {'card': '.faculty-member.type-dss.type-faculty',
                                  'name': 'h3 a',
                                  'link': 'h3 a',
                                  'email': "a[href^='mailto:']"}}},
        {'short': 'VMPBS',
         'name': 'Department of Pathobiological Sciences',
         'majors': ['Veterinary Medicine', 'Microbiology', 'Pathology'],
         'directory_url': 'https://www.vetmed.wisc.edu/people/',
         'scrape': {'url': 'https://www.vetmed.wisc.edu/people/',
                    'selectors': {'card': '.faculty-member.type-pbs.type-faculty',
                                  'name': 'h3 a',
                                  'link': 'h3 a',
                                  'email': "a[href^='mailto:']"}}},
    ],
}


# --- Research-area enrichment -----------------------------------------------
# UW-Madison mostly publishes prose bios with no structured research field, so
# the big shared WordPress directory theme (.faculty-member-content — used by
# ~20 depts incl. CS, Physics, Psych, Poli-Sci, Sociology, History, …) and the
# Education / VetMed / Pharmacy / Business / Plant-Path / Geoscience directories
# all stay broad — better broad than fragments. Each extractor below was found
# by per-template recon and re-verified live through the engine. The shared
# engineering directories yield clean groups: directory.engr.wisc.edu cards keep
# a "Research interests:" line (BME/ECE/ME), and engineering.wisc.edu profiles
# carry a research-interests accordion (CEE/ChemE/MSE/IE/EngrPhysics).
_THROTTLE = 1.2
_BME_RE = (r'Research interests:</b>(.*?)(?:<a [^>]*>\s*Research at UW'
           r'|<b>\s*Courses|<b>\s*Other affiliations|<b>\s*Also|</p>)')
_CEE_SEL = "#collapse-research_interests ul li"
_CARD_RESEARCH_RE = {
    "ECON": r'<p>\s*Fields?:\s*(.*?)\s*</p>',
    "BME": _BME_RE, "ECE": _BME_RE, "ME": _BME_RE,
    "FWE": r'Expertise:\s*(.*?)\s*(?:<br|</p>)',
    "GEN": r'<br\s*/?>\s*([^<>]+?)\s*</br>\s*</p>',
    "NUTRSCI": r'<div class="expertise">(.*?)</div>',
}
_PROFILE_ENRICH = {
    "ENGL": {"research_html_re": r'<dt[^>]*>\s*Interests?\s*</dt>\s*<dd[^>]*class="faculty-extra-value"[^>]*>\s*(.*?)\s*</dd>'},
    "CEE": {"research_items_selector": _CEE_SEL},
    "CBE": {"research_items_selector": _CEE_SEL},
    "MSE": {"research_items_selector": _CEE_SEL},
    "IE": {"research_items_selector": _CEE_SEL},
    "EP": {"research_items_selector": _CEE_SEL},
    "LAW": {"research_items_selector": "#scholarship-tab ul:not(.associated_articles) li"},
    "AOS": {"research_items_selector": "span.uw-button-inverse"},
    "SOILS": {"research_html_re": r'researchTabContent["\']>\s*<p>\s*<(?:strong|b)\b[^>]*>(.*?)\s*:?\s*</(?:strong|b)>'},
}
for _dept in SCHOOL["departments"]:
    _short = _dept["short"]
    if not _dept.get("scrape"):
        continue
    _cre = _CARD_RESEARCH_RE.get(_short)
    if _cre:
        _dept["scrape"]["selectors"] = {
            **_dept["scrape"].get("selectors", {}), "research_re": _cre}
    _enr = _PROFILE_ENRICH.get(_short)
    if _enr:
        _dept["scrape"].setdefault("profile_enrich", {**_enr, "throttle": _THROTTLE})


def fetch_and_normalize(deep: bool = True) -> list[dict]:
    return faculty_graph.fetch_and_normalize(SCHOOL, deep=deep)


def merge_into_processed(opps: list[dict]):
    return faculty_graph.merge_into_processed(opps)
