import {test,expect} from '@playwright/test';
import {STORAGE_KEYS} from '../src/lib/storage-keys';
import {encodeProfile} from '../src/lib/profile-share';
import type {ProfileData,ProfileRequest} from '../src/lib/types';
const STUB=`http://127.0.0.1:${process.env.E2E_SUPABASE_PORT??54321}`,FRONT=`http://127.0.0.1:${process.env.E2E_PORT??3100}`,BACK=`http://127.0.0.1:${process.env.E2E_BACKEND_PORT??8100}`;
// Each audit poll waits for the real backend to finish a ranking. The first is
// cold: about 2.2 s on a laptop, and past the default 5 s on a busy CI runner,
// where the poll gave up with the request still in flight.
const RANKING_MS=30_000;
const normal=():ProfileData=>({name:'Alex 王',institution:'UIUC',college:'Grainger College of Engineering',major:'Computer Science',grade:'Junior',is_international:false,research_interests:'robotics '.repeat(260)+'🧪 LATE_INTEREST',skills:Array.from({length:60},(_,i)=>({name:`Skill ${i+1}`,level:'experienced'})),coursework:Array.from({length:60},(_,i)=>`Course ${i+1}`),seeking_types:['research']});
test('B53 complete imported profile, field rejection and server aggregate recovery',async({page,request},info)=>{
 test.setTimeout(120000);const zh=info.project.name==='mobile-chrome',copy=(en:string,cn:string)=>zh?cn:en;if(zh)await page.setViewportSize({width:390,height:844});
 const signup=await request.post(STUB+'/auth/v1/signup',{data:{}});expect(signup.status()).toBe(200);const session=await signup.json();const headers={Authorization:`Bearer ${session.access_token}`};const original=normal();
 const seeded=await request.post(STUB+'/rest/v1/rpc/commit_profile_patch_cas',{headers,data:{p_expected_device_id:session.user.id,p_expected_revision:0,p_patch:original}});expect(await seeded.json()).toMatchObject({status:'applied'});
 const audit={external:[] as string[],errors:[] as string[],requests:[] as ProfileRequest[],statuses:[] as number[]};
 await page.context().route('**/*',route=>{const url=new URL(route.request().url());if(![STUB,FRONT,BACK].includes(url.origin)){audit.external.push(url.origin);return route.abort();}if(/^\/api\/(cold-email|tailor|chat|send)/.test(url.pathname))return route.abort();return route.continue();});
 page.on('pageerror',e=>audit.errors.push(e.message));
 await page.context().addCookies([{name:STORAGE_KEYS.LOCALE,value:zh?'zh':'en',url:FRONT}]);await page.addInitScript(({session,keys,locale})=>{if(!localStorage.getItem('b53-seeded')){localStorage.setItem('ofe_auth',JSON.stringify(session));localStorage.setItem(keys.LOCALE,locale);localStorage.setItem(keys.ONBOARDING_SEEN,'1');localStorage.setItem('b53-seeded','1');}},{session,keys:STORAGE_KEYS,locale:zh?'zh':'en'});
 // backend/schemas.py PROFILE_MAX_CHARACTERS: the whole normalized profile, not any one field.
 const actualError={code:'PROFILE_INPUT_LIMIT_EXCEEDED',field:'profile',limit:160000};
 let replayAggregate=false;
 await page.route('**/api/matches/view?**',async route=>{const body=route.request().postDataJSON();audit.requests.push(body.profile);if(replayAggregate){const response=await route.fetch();audit.statuses.push(response.status());expect(response.status()).toBe(422);expect((await response.json()).detail).toMatchObject({code:actualError.code,field:actualError.field,limit:actualError.limit});return route.fulfill({response});}const response=await route.fetch();audit.statuses.push(response.status());return route.fulfill({response});});
 await page.goto('/?share='+encodeProfile(original));await expect(page.locator('#research_interests')).toHaveValue(original.research_interests);await expect(page.getByTestId('generate-matches')).toBeEnabled();await page.getByTestId('generate-matches').click();await expect(page).toHaveURL(/\/results/);await expect.poll(()=>audit.statuses.length,{timeout:RANKING_MS}).toBe(1);expect(audit.statuses[0]).toBe(200);expect(audit.requests[0].research_interests_text).toBe(original.research_interests);expect(audit.requests[0].hard_skills.at(-1)?.name).toBe('Skill 60');expect(audit.requests[0].coursework.at(-1)).toBe('Course 60');expect(audit.requests[0].hard_skills).toHaveLength(60);
 await page.goto('/');await expect(page.locator('#research_interests')).toHaveValue(original.research_interests);const oversized='🧪'.repeat(60001);await page.locator('#research_interests').fill(oversized);await page.getByTestId('generate-matches').click();await expect(page).toHaveURL(/\/results/);await expect(page.getByText(copy('Research interests has 60001 characters; the limit is 60000. Edit this input in your profile and try again. Your original content is kept.','研究兴趣共 60001 个字符，上限为 60000。请在个人资料中修改后重试，原文已保留。'),{exact:true})).toBeVisible();expect(audit.requests).toHaveLength(1);await expect(page.locator('.skeleton')).toHaveCount(0);await expect(page.getByText(copy('Loading...','加载中…'),{exact:true})).toHaveCount(0);await page.screenshot({path:info.outputPath('b53-field-error-'+(zh?'zh':'en')+'.png')});await page.getByRole('button',{name:copy('Edit profile','修改个人资料'),exact:true}).click();await expect(page.locator('#research_interests')).toHaveValue(oversized);
 await page.locator('#research_interests').fill(original.research_interests);await page.getByTestId('generate-matches').click();await expect.poll(()=>audit.statuses.length,{timeout:RANKING_MS}).toBe(2);expect(audit.statuses[1]).toBe(200);
 await page.goto('/');await expect(page.locator('#research_interests')).toHaveValue(original.research_interests);
 const aggregate={...original,research_interests:'R'.repeat(40000),skills:Array.from({length:512},(_,i)=>({name:'s'.repeat(100)+i,level:'experienced' as const}))};
 // Next's native history integration imports a long link without sending an oversized HTTP request URL.
 await page.evaluate(encoded=>window.history.pushState(null,'','/?share='+encoded),encodeProfile(aggregate));await expect(page.locator('#research_interests')).toHaveValue(aggregate.research_interests);replayAggregate=true;expect(await page.evaluate(()=>document.body.scrollWidth<=document.documentElement.clientWidth)).toBe(true);await page.getByTestId('generate-matches').scrollIntoViewIfNeeded();await info.attach('aggregate-click-layout',{body:JSON.stringify(await page.getByTestId('generate-matches').evaluate(el=>{const r=el.getBoundingClientRect();return {button:{x:r.x,y:r.y,width:r.width,height:r.height},hit:document.elementFromPoint(r.x+r.width/2,r.y+r.height/2)?.outerHTML.slice(0,1000),viewport:{width:innerWidth,height:innerHeight,scale:visualViewport?.scale},bodyWidth:document.body.scrollWidth};}),null,2),contentType:'application/json'});await page.getByTestId('generate-matches').click({timeout:15000});await expect(page).toHaveURL(/\/results/);const total=copy('The complete profile is too long. Reduce the material used for this request and try again. Your original content is kept.','整份资料过长，请减少本次使用的材料后重试。原内容已保留。');await expect(page.getByText(total,{exact:true})).toBeVisible();expect(audit.requests.at(-1)!.hard_skills).toHaveLength(512);await expect(page.locator('.skeleton')).toHaveCount(0);await expect(page.getByText(copy('Loading...','加载中…'),{exact:true})).toHaveCount(0);await page.screenshot({path:info.outputPath('b53-total-error-'+(zh?'zh':'en')+'.png')});await page.getByRole('button',{name:copy('Edit profile','修改个人资料'),exact:true}).click();await expect(page.locator('#research_interests')).toHaveValue(aggregate.research_interests);await page.locator('#research_interests').fill('Robotics after review 🧪');replayAggregate=false;const count=audit.statuses.length;await page.getByTestId('generate-matches').click();await expect.poll(()=>audit.statuses.length,{timeout:RANKING_MS}).toBe(count+1);expect(audit.statuses.at(-1)).toBe(200);expect(audit.requests.at(-1)!.hard_skills).toHaveLength(512);expect(audit.requests.at(-1)!.research_interests_text).toBe('Robotics after review 🧪');
 expect(audit.external).toEqual([]);expect(audit.errors).toEqual([]);await info.attach('b53-profile-input-recovery',{body:JSON.stringify(audit,null,2),contentType:'application/json'});
});

test('B53 share refuses an oversized encoded link and recovers without losing profile',async({page,request},info)=>{
 const zh=info.project.name==='mobile-chrome',copy=(en:string,cn:string)=>zh?cn:en;if(zh)await page.setViewportSize({width:390,height:844});
 const session=await(await request.post(STUB+'/auth/v1/signup',{data:{}})).json();const p={...normal(),research_interests:'🧪'.repeat(2000)};
 const response=await request.post(STUB+'/rest/v1/rpc/commit_profile_patch_cas',{headers:{Authorization:`Bearer ${session.access_token}`},data:{p_expected_device_id:session.user.id,p_expected_revision:0,p_patch:p}});expect(await response.json()).toMatchObject({status:'applied'});
 const external:string[]=[];await page.context().route('**/*',route=>{const url=new URL(route.request().url());if(![STUB,FRONT,BACK].includes(url.origin)){external.push(url.origin);return route.abort();}if(/^\/api\/(cold-email|tailor|chat|send|matches)/.test(url.pathname))return route.abort();return route.continue();});
 await page.context().addCookies([{name:STORAGE_KEYS.LOCALE,value:zh?'zh':'en',url:FRONT}]);await page.addInitScript(({session,keys,locale})=>{localStorage.setItem('ofe_auth',JSON.stringify(session));localStorage.setItem(keys.LOCALE,locale);localStorage.setItem(keys.ONBOARDING_SEEN,'1');},{session,keys:STORAGE_KEYS,locale:zh?'zh':'en'});
 await page.goto('/');await expect(page.locator('#research_interests')).toHaveValue(p.research_interests);
 await page.evaluate(()=>{const state=window as unknown as {b53Copies:string[]};state.b53Copies=[];Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async(text:string)=>{state.b53Copies.push(text);}}});});
 await page.getByRole('button',{name:copy('Share profile','分享档案'),exact:true}).click();await expect(page.getByRole('main').getByRole('alert')).toHaveText(copy('This profile is too long to put in a share link. Share fewer details and try again. Your profile is unchanged.','资料太长，无法放进分享链接。请减少要分享的内容后重试，原资料未改动。'));await expect(page.locator('#research_interests')).toHaveValue(p.research_interests);expect(await page.evaluate(()=>(window as unknown as {b53Copies:string[]}).b53Copies)).toEqual([]);await page.getByRole('main').getByRole('alert').scrollIntoViewIfNeeded();await page.screenshot({path:info.outputPath('b53-share-limit-'+(zh?'zh':'en')+'.png')});
 await page.locator('#research_interests').fill('Complete shorter shared direction 🧪');await page.getByRole('button',{name:copy('Share profile','分享档案'),exact:true}).click();await expect(page.getByRole('button',{name:copy('Copied!','已复制！'),exact:true})).toBeVisible();const copies=await page.evaluate(()=>(window as unknown as {b53Copies:string[]}).b53Copies);expect(copies).toHaveLength(1);expect(copies[0].length).toBeLessThanOrEqual(8000);expect(external).toEqual([]);await info.attach('b53-share-limit',{body:JSON.stringify({encodedLinkCharacters:copies[0].length,originalKeptBeforeEdit:true,external}),contentType:'application/json'});
});
