import { test, expect, request as apiRequest, type Page } from '@playwright/test';
import { STORAGE_KEYS } from '../src/lib/storage-keys';
import { createEmptyResumeMaster } from '../src/lib/resume-master';
import type { ProfileData, ResumeFact } from '../src/lib/types';
import type { TargetResumeAiRequest, TargetResumeAiResponse } from '../src/lib/target-resume-ai-protocol';
import type { TargetResumeV1 } from '../src/lib/target-resume';
const STUB=`http://127.0.0.1:${Number(process.env.E2E_SUPABASE_PORT??54321)}`,FRONT=`http://127.0.0.1:${Number(process.env.E2E_PORT??3100)}`,BACK=`http://127.0.0.1:${Number(process.env.E2E_BACKEND_PORT??8100)}`;
const TARGET='uiuc-siebel-ugresearch';
const ORIGINAL='Measured robot trials; I did not lead the team.',SUPPORT='I wrote Python scripts to compare the recorded trials. I did not design the experiment.',UNBOUND='I checked the robot trial logs in Spring 2026.';
const PROPOSED='Measured robot trials; wrote Python scripts to compare the recorded trials. I did not lead the team. I did not design the experiment.';
const INTEREST='I want to explore reliable robot perception. 我希望研究鲁棒感知。';
const fact=(id:string,value:string):ResumeFact=>({id,value,revision:1,status:'confirmed',source:{kind:'manual'}});
function profile():ProfileData{const master=createEmptyResumeMaster('browser-master');master.basics.name=fact('name','Alex 王');master.activities=[{id:'robot',kind:'research',title:fact('title','Robot trials'),organization:fact('org','Example Lab'),start:fact('start','Fall 2025'),end:fact('end','Spring 2026'),details:[{id:'original',revision:1},{id:'support',revision:1}]},{id:'other',kind:'project',title:fact('other-title','Other project'),details:[{id:'other-entry',revision:1}]}];return {institution:'UIUC',home_school:'uiuc',college:'Engineering',major:'CS',grade:'Junior',is_international:false,skills:[],research_interests:INTEREST,seeking_types:['research'],coursework:[],resume_text:'',resume_master:master,experience_entries:[['original',ORIGINAL],['support',SUPPORT],['other-entry','Built a website for a club.'],['unbound',UNBOUND]].map(([id,text])=>({id,text,revision:1,status:'confirmed',source:{kind:'manual'}}))};}
const lines=(d:TargetResumeV1)=>d.document.sections.flatMap(section=>section.blocks.flatMap(block=>block.lines.map(line=>({section,block,line}))));
function reply(r:TargetResumeAiRequest):TargetResumeAiResponse{const units=lines(r.draft).filter(x=>x.section.kind!=='basics');const source=Array.from(r.draft.target_snapshot.description);return {version:1,pipeline_version:'full-target-v6',check_version:'target-resume-source-checks-v4',request_id:r.request_id,document_id:r.draft.id,opportunity_id:r.draft.opportunity_id,document_signature:r.document_signature,base:r.draft.base,support_groups:r.support_groups,manifest:{unit_ids:units.map(x=>x.line.id),protected_unit_count:lines(r.draft).length-units.length},method:'ai',logical_calls:2,provider_attempts_upper_bound:4,receipts:units.filter(x=>r.selected_unit_ids.includes(x.line.id)).map(({section,block,line})=>{const group=r.support_groups?.find(g=>g.unit_id===line.id);return {unit_id:line.id,section_id:section.id,block_id:block.id,evidence:line.evidence,before_text:line.text,status:group||line.evidence.kind!=='experience'?'suggested':'unchanged',reason_code:group||line.evidence.kind!=='experience'?null:'no_link',suggestion:{priority:'normal',reason:'Review the exact trial work and confirmed Python contribution.',target_evidence:[],links:[],ops:group?['personal_first']:[],alternative_text:null,proposed_text:group?PROPOSED:null,...(group?{source_evidence:[group.unit_id,...group.support_unit_ids].map(id=>{const l=lines(r.draft).find(x=>x.line.id===id)!.line;return {unit_id:id,start:0,end:Array.from(l.original).length,quote:l.original};})}:{})}};})};}
async function session(){const http=await apiRequest.newContext();const response=await http.post(STUB+'/auth/v1/signup',{data:{}});expect(response.status()).toBe(200);const session=await response.json();session.user={...session.user,is_anonymous:false,email:'b52@fixture.invalid',app_metadata:{provider:'email',providers:['email']}};const token=session.access_token.split('.');token[1]=Buffer.from(JSON.stringify({...JSON.parse(Buffer.from(token[1],'base64url').toString()),is_anonymous:false})).toString('base64url');session.access_token=token.join('.');const p=profile();const saved=await http.post(STUB+'/rest/v1/rpc/commit_profile_patch_cas',{headers:{Authorization:`Bearer ${session.access_token}`},data:{p_expected_device_id:session.user.id,p_expected_revision:0,p_patch:p}});expect(await saved.json()).toMatchObject({status:'applied',revision:1});return {http,session};}

test('B52 assign, review support, invalidate old suggestions and save complete sources',async({page},info)=>{
 test.setTimeout(90_000);const zh=info.project.name==='mobile-chrome',copy=(en:string,cn:string)=>zh?cn:en;if(zh)await page.setViewportSize({width:390,height:844});const owner=await session();const audit={external:[] as string[],errors:[] as string[],requests:[] as TargetResumeAiRequest[],writes:[] as {path:string;body:Record<string,unknown>}[]};
 try{
 await page.context().route('**/*',route=>{const url=new URL(route.request().url());if(![STUB,FRONT,BACK].includes(url.origin)){audit.external.push(url.origin);return route.abort();}if(/^\/api\/(cold-email|tailor)/.test(url.pathname))return route.abort();return route.continue();});
 page.on('pageerror',e=>audit.errors.push(e.message));page.on('request',r=>{const path=new URL(r.url()).pathname;if(r.method()!=='GET'&&path.startsWith('/rest/v1/'))audit.writes.push({path,body:r.postDataJSON()});});
 await page.context().addCookies([{name:STORAGE_KEYS.LOCALE,value:zh?'zh':'en',url:FRONT}]);await page.addInitScript(({session,keys,locale})=>{localStorage.setItem('ofe_auth',JSON.stringify(session));localStorage.setItem(keys.LOCALE,locale);localStorage.setItem(keys.ONBOARDING_SEEN,'1');},{session:owner.session,keys:STORAGE_KEYS,locale:zh?'zh':'en'});await page.route('**/auth/v1/user',route=>route.fulfill({json:owner.session.user}));await page.route('**/auth/v1/token?grant_type=refresh_token',route=>route.fulfill({json:owner.session}));
 await page.route('**/api/tailor/full-target/suggestions',route=>{const r=route.request().postDataJSON();audit.requests.push(r);return route.fulfill({json:reply(r)});});
 await page.goto('/opportunities/'+TARGET);await page.getByRole('button',{name:copy('Renovate Resume','简历翻新'),exact:true}).click();const modal=page.getByRole('dialog',{name:copy('Target résumé','目标简历'),exact:true});await modal.getByRole('button',{name:copy('Create from confirmed master','从已确认母版创建'),exact:true}).click();await expect(modal.getByRole('textbox',{name:copy('Edit Full name','编辑 姓名'),exact:true})).toHaveValue('Alex 王');
 const save=async(revision:number)=>{const pending=page.waitForResponse(r=>new URL(r.url()).pathname==='/rest/v1/rpc/commit_target_resume_with_provenance_cas');await modal.getByRole('button',{name:copy('Save target draft','保存目标文稿'),exact:true}).click();const r=await pending;expect(await r.json()).toMatchObject({status:'saved',revision});await expect(modal.getByText(copy('Saved version','已保存版本')+' '+revision,{exact:true})).toBeVisible();};await save(1);
 await modal.getByRole('button',{name:copy('Add experience details','补充经历'),exact:true}).click();const assign=page.getByTestId('resume-experience-assignment');await expect(assign.getByText(UNBOUND,{exact:true})).toBeVisible();await assign.getByRole('radio').check();await assign.getByRole('combobox').selectOption('robot');await expect(assign.getByText(ORIGINAL,{exact:true})).toBeVisible();await expect(assign.getByRole('button',{name:copy('Save assignment','保存归属'),exact:true})).toBeDisabled();await assign.getByRole('checkbox').check();
 await page.evaluate(prefix=>{const original=Storage.prototype.setItem;(window as unknown as {restoreJournal:()=>void}).restoreJournal=()=>{Storage.prototype.setItem=original;};Storage.prototype.setItem=function(key,value){if(key.includes(prefix+'op_'))throw new DOMException('Fixture quota','QuotaExceededError');return original.call(this,key,value);};},STORAGE_KEYS.PROFILE_JOURNAL_PREFIX);
 await assign.getByRole('button',{name:copy('Save assignment','保存归属'),exact:true}).click();await expect(assign.getByRole('alert')).toContainText(copy('not saved','未能保存'));await expect(assign.getByRole('radio')).toBeChecked();await expect(assign.getByRole('combobox')).toHaveValue('robot');await assign.scrollIntoViewIfNeeded();await page.screenshot({path:info.outputPath('b52-assignment-failure-'+(zh?'zh':'en')+'.png')});await page.evaluate(()=>(window as unknown as {restoreJournal:()=>void}).restoreJournal());
 await assign.getByRole('button',{name:copy('Save assignment','保存归属'),exact:true}).click();await expect(assign.getByText(copy('Assigned to your master résumé. Your existing target draft is kept; create a new draft when ready.','已归入母版。原有目标稿保持不变，需要时再创建新稿。'))).toBeVisible();expect(audit.writes.filter(w=>w.path.endsWith('commit_profile_patch_cas'))).toHaveLength(1);
 await modal.getByRole('button',{name:copy('Rebuild from current confirmed master','从当前已确认母版重新创建'),exact:true}).click();await modal.getByRole('button',{name:copy('Create new draft','创建新稿'),exact:true}).click();await expect(modal.locator('textarea').filter({hasText:UNBOUND})).toHaveCount(1);await modal.getByRole('button',{name:copy('Add experience details','补充经历'),exact:true}).click();
 const direction=page.getByTestId('target-resume-direction');await direction.locator('summary').click();await expect(direction).toContainText(INTEREST);
 const support=page.getByTestId('target-resume-support');await support.locator('summary').click();await support.getByRole('combobox').selectOption({label:ORIGINAL});expect(await support.getByRole('option').allTextContents()).not.toContain('Built a website for a club.');const supportChoice=support.locator('label').filter({hasText:SUPPORT});await supportChoice.getByRole('checkbox').check();const ai=page.getByRole('region',{name:'AI adaptation suggestions',exact:true});
 await ai.getByRole('button',{name:copy('Generate AI suggestions','生成 AI 建议'),exact:true}).click();await expect.poll(()=>audit.requests.length).toBe(1);expect(audit.requests[0].support_groups).toEqual([]);expect(audit.requests[0].draft.base_snapshot.research_interests).toBe(INTEREST);await expect(ai.getByRole('checkbox',{name:/Use rewrite:/})).toHaveCount(0);
 await support.getByRole('button',{name:copy('Reviewed: use these sources for this rewrite','核对后用于这条修改'),exact:true}).click();await ai.getByRole('button',{name:copy('Generate AI suggestions','生成 AI 建议'),exact:true}).click();await expect(ai.getByRole('checkbox',{name:/Use rewrite:/})).toHaveCount(1);const currentRequest=audit.requests.at(-1)!;expect(currentRequest.support_groups).toHaveLength(1);await support.scrollIntoViewIfNeeded();await page.screenshot({path:info.outputPath('b52-support-review-'+(zh?'zh':'en')+'.png')});
 await supportChoice.getByRole('checkbox').uncheck();await expect(ai.getByRole('checkbox',{name:/Use rewrite:/})).toHaveCount(0);await supportChoice.getByRole('checkbox').check();await support.getByRole('button',{name:copy('Reviewed: use these sources for this rewrite','核对后用于这条修改'),exact:true}).click();await ai.getByRole('button',{name:copy('Generate AI suggestions','生成 AI 建议'),exact:true}).click();await ai.getByRole('checkbox',{name:/Use rewrite:/}).check();await ai.getByRole('button',{name:copy('Apply selected suggestions','应用所选建议'),exact:true}).click();await expect(modal.locator('textarea').filter({hasText:PROPOSED})).toHaveCount(1);await save(2);
 const record=audit.writes.filter(w=>w.path.endsWith('commit_target_resume_with_provenance_cas')).at(-1)!.body;const provenance=record.p_provenance as {events:{changes:{source_evidence:{quote:string}[]}[]}[]};expect(provenance.events.at(-1)!.changes[0].source_evidence.map(x=>x.quote)).toEqual([ORIGINAL,SUPPORT]);
 await modal.locator('textarea').filter({hasText:PROPOSED}).scrollIntoViewIfNeeded();await page.screenshot({path:info.outputPath('b52-adapted-'+(zh?'zh':'en')+'.png')});await modal.getByRole('button',{name:copy('Close target résumé','关闭目标简历'),exact:true}).click();await expect(modal).toHaveCount(0);await page.reload();await page.getByRole('button',{name:copy('Renovate Resume','简历翻新'),exact:true}).click();await expect(modal.locator('textarea').filter({hasText:PROPOSED})).toHaveCount(1);const restoredDirection=page.getByTestId('target-resume-direction');await restoredDirection.locator('summary').click();await expect(restoredDirection).toContainText(INTEREST);await modal.locator('textarea').filter({hasText:PROPOSED}).scrollIntoViewIfNeeded();await page.screenshot({path:info.outputPath('b52-restored-'+(zh?'zh':'en')+'.png')});expect(audit.external).toEqual([]);expect(audit.errors).toEqual([]);
 await info.attach('b52-material-flow',{body:JSON.stringify(audit,null,2),contentType:'application/json'});
 }finally{await owner.http.dispose();}
});
