/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/admin/data-quality": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Data Quality */
        get: operations["data_quality_api_admin_data_quality_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/data-quality/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Data Quality History */
        get: operations["data_quality_history_api_admin_data_quality_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cold-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Email
         * @description Generate a cold email for a specific opportunity with mailto: link.
         */
        post: operations["generate_email_api_cold_email_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cold-email/refine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refine Email */
        post: operations["refine_email_api_cold_email_refine_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cold-email/variants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Email Variants */
        post: operations["generate_email_variants_api_cold_email_variants_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cron/reminders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Reminders Cron
         * @description Invoked by an external scheduler (Vercel Cron / GitHub Actions).
         *
         *     Scans push_subscriptions joined with interactions.remind_at where
         *     remind_at <= today and status in ('applied','replied','interviewing'),
         *     sends a Web Push notification to each matching subscription.
         */
        get: operations["reminders_cron_api_cron_reminders_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/email/restore-link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restore Link
         * @description Emails a signed URL that lets a user recover their profile on a
         *     new device. Returns {ok: true} even when Resend is unconfigured so
         *     the frontend doesn't leak configuration state — just logs a warning.
         */
        post: operations["restore_link_api_email_restore_link_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/email/send-favorites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send Favorites */
        post: operations["send_favorites_api_email_send_favorites_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/email/send-matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send Matches */
        post: operations["send_matches_api_email_send_matches_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/email/verify-restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Verify Restore
         * @description Verify the signed restore link. The frontend calls this when
         *     the user clicks the email link; we respond with the validated
         *     device_id so the app can load their profile.
         */
        get: operations["verify_restore_api_email_verify_restore_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get Matches
         * @description Score and rank opportunities for the given profile.
         *
         *     The full bucket counts are always returned so the client knows
         *     the total picture. Only the slice [offset, offset+limit) of visible
         *     (non-low_fit) results is returned in ``results``.
         *
         *     Set ``semantic=true`` to blend LLM/TF-IDF semantic similarity into
         *     the top 50 results (30% weight). Adds ~200-800ms latency when
         *     OpenAI key is configured; free when falling back to TF-IDF.
         */
        post: operations["get_matches_api_matches_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matches/{opportunity_id}/gaps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get Gap Analysis */
        post: operations["get_gap_analysis_api_matches__opportunity_id__gaps_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/opportunities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Opportunities */
        get: operations["list_opportunities_api_opportunities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/opportunities/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get Opportunities Batch
         * @description Return multiple opportunities by ID in a single request.
         *
         *     Body: {"ids": ["id1", "id2", ...]} — capped at 200 to bound work.
         *     Missing IDs are silently skipped so the caller can always iterate
         *     the response alongside its own list.
         */
        post: operations["get_opportunities_batch_api_opportunities_batch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/opportunities/stats/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Stats */
        get: operations["get_stats_api_opportunities_stats_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/opportunities/upcoming": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Upcoming Deadlines
         * @description Opportunities with deadlines within the next ``days`` days, sorted ascending.
         *
         *     Useful for building a calendar / "what's due soon" widget without
         *     re-ranking the full corpus per request.
         */
        get: operations["get_upcoming_deadlines_api_opportunities_upcoming_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/opportunities/{opportunity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Opportunity */
        get: operations["get_opportunity_api_opportunities__opportunity_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/opportunities/{opportunity_id}/similar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Similar Opportunities
         * @description Return opportunities similar to the given one.
         *
         *     Similarity is the weighted sum of:
         *       * shared keyword count  (primary signal)
         *       * same opportunity_type (small bonus)
         *       * shared majors         (small bonus)
         *       * same organization     (small bonus for "more from this lab")
         *     The source opportunity is always excluded.
         */
        get: operations["get_similar_opportunities_api_opportunities__opportunity_id__similar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/push/vapid-public-key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Vapid Public Key */
        get: operations["get_vapid_public_key_api_push_vapid_public_key_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resume/github/{username}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Parse Github Profile */
        get: operations["parse_github_profile_api_resume_github__username__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resume/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Resume
         * @description Upload and parse a PDF resume to extract profile data.
         */
        post: operations["upload_resume_api_resume_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_resume_api_resume_upload_post */
        Body_upload_resume_api_resume_upload_post: {
            /** File */
            file: string;
        };
        /** ColdEmailRequest */
        ColdEmailRequest: {
            /** Opportunity Id */
            opportunity_id: string;
            profile: components["schemas"]["ProfileRequest"];
        };
        /** ColdEmailResponse */
        ColdEmailResponse: {
            /** Body */
            body: string;
            /** Mailto Link */
            mailto_link: string;
            /** Recipient Email */
            recipient_email: string;
            /** Subject */
            subject: string;
        };
        /** EmailRefineRequest */
        EmailRefineRequest: {
            /** Current Body */
            current_body: string;
            /** Instruction */
            instruction: string;
            /**
             * Subject
             * @default
             */
            subject: string;
        };
        /** FavoriteItem */
        FavoriteItem: {
            /** Deadline */
            deadline?: string | null;
            /**
             * Notes
             * @default
             */
            notes: string;
            /** Score */
            score?: number | null;
            /**
             * Source
             * @default
             */
            source: string;
            /**
             * Status
             * @default
             */
            status: string;
            /** Title */
            title: string;
            /**
             * Url
             * @default
             */
            url: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MatchItem */
        MatchItem: {
            /** Deadline */
            deadline?: string | null;
            /**
             * Organization
             * @default
             */
            organization: string;
            /** Score */
            score?: number | null;
            /**
             * Source
             * @default
             */
            source: string;
            /** Title */
            title: string;
            /**
             * Url
             * @default
             */
            url: string;
        };
        /** MatchResultResponse */
        MatchResultResponse: {
            /** Bucket */
            bucket: string;
            /** Eligibility Score */
            eligibility_score: number;
            /** Final Score */
            final_score: number;
            /** Next Steps */
            next_steps: string[];
            /** Opportunity */
            opportunity: {
                [key: string]: unknown;
            };
            /** Opportunity Id */
            opportunity_id: string;
            /** Readiness Score */
            readiness_score: number;
            /** Reasons Fit */
            reasons_fit: string[];
            /** Reasons Gap */
            reasons_gap: string[];
            /** Upside Score */
            upside_score: number;
        };
        /** MatchesResponse */
        MatchesResponse: {
            /** Good Match */
            good_match: number;
            /** High Priority */
            high_priority: number;
            /** Low Fit */
            low_fit: number;
            /** Reach */
            reach: number;
            /** Results */
            results: components["schemas"]["MatchResultResponse"][];
            /** Total */
            total: number;
        };
        /** ProfilePreferences */
        ProfilePreferences: {
            /**
             * Exclude Citizenship Restricted
             * @default true
             */
            exclude_citizenship_restricted: boolean;
            /**
             * Min Match Threshold
             * @default 25
             */
            min_match_threshold: number;
            /**
             * Prioritize Paid
             * @default true
             */
            prioritize_paid: boolean;
            /**
             * Show Reach Opportunities
             * @default true
             */
            show_reach_opportunities: boolean;
        };
        /**
         * ProfileRequest
         * @example {
         *       "college": "Grainger College of Engineering",
         *       "hard_skills": [
         *         {
         *           "level": "experienced",
         *           "name": "Python"
         *         },
         *         {
         *           "level": "beginner",
         *           "name": "Java"
         *         },
         *         {
         *           "level": "expert",
         *           "name": "C++"
         *         }
         *       ],
         *       "international_student": true,
         *       "major": "ECE",
         *       "name": "Eric",
         *       "seeking_type": [
         *         "research",
         *         "summer_program"
         *       ],
         *       "year": "freshman"
         *     }
         */
        ProfileRequest: {
            /**
             * Can Cold Email
             * @default true
             */
            can_cold_email: boolean;
            /**
             * College
             * @default
             */
            college: string;
            /** Coursework */
            coursework?: string[];
            /** Desired Fields */
            desired_fields?: string[];
            /**
             * Experience Level
             * @default beginner
             */
            experience_level: string;
            /**
             * Github Url
             * @default
             */
            github_url: string;
            /** Hard Skills */
            hard_skills?: (components["schemas"]["SkillItem"] | string)[];
            /**
             * International Student
             * @default false
             */
            international_student: boolean;
            /**
             * Linkedin Ready
             * @default false
             */
            linkedin_ready: boolean;
            /**
             * Linkedin Url
             * @default
             */
            linkedin_url: string;
            /**
             * Major
             * @default
             */
            major: string;
            /**
             * Name
             * @default
             */
            name: string;
            preferences?: components["schemas"]["ProfilePreferences"] | null;
            /**
             * Preferred Location
             * @default on-campus
             */
            preferred_location: string;
            /**
             * Research Interests Text
             * @default
             */
            research_interests_text: string;
            /**
             * Resume Ready
             * @default false
             */
            resume_ready: boolean;
            /**
             * School
             * @default
             */
            school: string;
            /**
             * Search Weight
             * @default 50
             */
            search_weight: number;
            /** Secondary Interests */
            secondary_interests?: string[];
            /** Seeking Type */
            seeking_type?: string[];
            /**
             * Time Availability
             * @default summer
             */
            time_availability: string;
            /**
             * Year
             * @default
             */
            year: string;
        };
        /** RestoreLinkRequest */
        RestoreLinkRequest: {
            /** Device Id */
            device_id: string;
            /** Email */
            email: string;
        };
        /** ResumeParseResponse */
        ResumeParseResponse: {
            /** Experience Level */
            experience_level: string;
            /** Extracted Coursework */
            extracted_coursework: string[];
            /** Extracted Skills */
            extracted_skills: string[];
            /**
             * Message
             * @default
             */
            message: string;
            /** Raw Text */
            raw_text: string;
            /** Success */
            success: boolean;
        };
        /** SendFavoritesRequest */
        SendFavoritesRequest: {
            /** Email */
            email: string;
            /** Items */
            items: components["schemas"]["FavoriteItem"][];
        };
        /** SendMatchesRequest */
        SendMatchesRequest: {
            /** Email */
            email: string;
            /** Items */
            items: components["schemas"]["MatchItem"][];
            /**
             * Subject Hint
             * @default
             */
            subject_hint: string;
        };
        /** SkillItem */
        SkillItem: {
            /**
             * Level
             * @default beginner
             */
            level: string;
            /** Name */
            name: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    data_quality_api_admin_data_quality_get: {
        parameters: {
            query?: {
                token?: string | null;
                /** @description Bypass cache */
                force?: boolean;
            };
            header?: {
                "X-Admin-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    data_quality_history_api_admin_data_quality_history_get: {
        parameters: {
            query?: {
                token?: string | null;
                limit?: number;
            };
            header?: {
                "X-Admin-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_email_api_cold_email_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ColdEmailRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ColdEmailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refine_email_api_cold_email_refine_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailRefineRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_email_variants_api_cold_email_variants_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ColdEmailRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reminders_cron_api_cron_reminders_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_link_api_email_restore_link_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RestoreLinkRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_favorites_api_email_send_favorites_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendFavoritesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_matches_api_email_send_matches_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendMatchesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_restore_api_email_verify_restore_get: {
        parameters: {
            query: {
                d: string;
                t: number;
                s: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_matches_api_matches_post: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                semantic?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_gap_analysis_api_matches__opportunity_id__gaps_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                opportunity_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_opportunities_api_opportunities_get: {
        parameters: {
            query?: {
                opportunity_type?: string | null;
                paid?: string | null;
                international_friendly?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_opportunities_batch_api_opportunities_batch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stats_api_opportunities_stats_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_upcoming_deadlines_api_opportunities_upcoming_get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_opportunity_api_opportunities__opportunity_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                opportunity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_similar_opportunities_api_opportunities__opportunity_id__similar_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                opportunity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_vapid_public_key_api_push_vapid_public_key_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    parse_github_profile_api_resume_github__username__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_resume_api_resume_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_resume_api_resume_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeParseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
