export const COLLEGE_MAJORS: Record<string, string[]> = {
  'Division of General Studies (DGS)': [
    'Undeclared / Exploring',
  ],
  'Grainger College of Engineering': [
    'Aerospace Engineering',
    'Bioengineering',
    'Chemical & Biomolecular Engineering',
    'Civil & Environmental Engineering',
    'Computer Engineering',
    'Computer Science',
    'Computer Science + Advertising',
    'Computer Science + Animal Sciences',
    'Computer Science + Anthropology',
    'Computer Science + Astronomy',
    'Computer Science + Bioengineering',
    'Computer Science + Chemistry',
    'Computer Science + Crop Sciences',
    'Computer Science + Economics',
    'Computer Science + Education',
    'Computer Science + Geography & GIS',
    'Computer Science + Linguistics',
    'Computer Science + Music',
    'Computer Science + Philosophy',
    'Computer Science + Physics',
    'Electrical & Computer Engineering (ECE)',
    'Engineering Mechanics',
    'Engineering Physics',
    'Environmental Engineering',
    'Industrial & Enterprise Systems Engineering',
    'Innovation, Leadership & Engineering Entrepreneurship (ILEE)',
    'Materials Science & Engineering',
    'Mechanical Engineering',
    'Neural Engineering',
    'Nuclear, Plasma & Radiological Engineering',
    'Systems Engineering & Design',
  ],
  'Liberal Arts & Sciences (LAS)': [
    'Actuarial Science',
    'African American Studies',
    'Anthropology',
    'Asian American Studies',
    'Astronomy',
    'Astrophysics',
    'Atmospheric Sciences',
    'Biochemistry',
    'Brain & Cognitive Science',
    'Chemistry',
    'Classics',
    'Communication',
    'Comparative & World Literature',
    'Creative Writing',
    'Earth, Society & Environmental Sustainability',
    'East Asian Languages & Cultures',
    'Econometrics & Quantitative Economics',
    'Economics',
    'English',
    'French',
    'Gender & Women\'s Studies',
    'Geography & GIS',
    'Geology',
    'Germanic Studies',
    'Global Studies',
    'History',
    'Integrative Biology',
    'Italian',
    'Latin American Studies',
    'Latina/Latino Studies',
    'Linguistics',
    'Mathematics',
    'Mathematics & Computer Science',
    'Molecular & Cellular Biology',
    'Neuroscience',
    'Philosophy',
    'Physics',
    'Political Science',
    'Portuguese',
    'Psychology',
    'Religion',
    'Russian, East European & Eurasian Studies',
    'Slavic Studies',
    'Sociology',
    'Spanish',
    'Statistics',
    'Statistics & Computer Science',
    'Individual Plans of Study',
    'Interdisciplinary Studies',
    'Liberal Studies',
  ],
  'Gies College of Business': [
    'Accountancy',
    'Accountancy + Data Science',
    'Business + Data Science',
    'Finance',
    'Finance + Data Science',
    'Information Systems',
    'Management',
    'Marketing',
    'Operations Management',
    'Strategy, Innovation & Entrepreneurship',
    'Supply Chain Management',
  ],
  'College of ACES': [
    'Agricultural & Biological Engineering',
    'Agricultural & Consumer Economics',
    'Agricultural Leadership, Education & Communications',
    'Agronomy',
    'Animal Sciences',
    'Crop Sciences',
    'Dietetics & Nutrition',
    'Engineering Technology & Management for Agricultural Systems',
    'Food Science & Human Nutrition',
    'Hospitality Management',
    'Human Development & Family Studies',
    'Natural Resources & Environmental Sciences',
    'Plant Biotechnology',
    'Sustainability in Food & Environmental Systems',
  ],
  'College of Fine & Applied Arts': [
    'Architectural Studies',
    'Art & Art History',
    'Art Education',
    'Dance',
    'Graphic Design',
    'Industrial Design',
    'Landscape Architecture',
    'Music',
    'Music Composition',
    'Music Education',
    'Studio Art',
    'Sustainable Design',
    'Theatre',
    'Urban Studies & Planning',
  ],
  'School of Information Sciences (iSchool)': [
    'Information Sciences',
    'Information Sciences + Data Science',
  ],
  'College of Applied Health Sciences': [
    'Community Health',
    'Interdisciplinary Health Sciences',
    'Kinesiology',
    'Nutrition & Health',
    'Recreation, Sport & Tourism',
    'Speech & Hearing Science',
  ],
  'College of Education': [
    'Early Childhood Education',
    'Elementary Education',
    'Learning & Education Studies',
    'Middle Grades Education',
    'Secondary Education',
    'Special Education',
  ],
  'College of Media': [
    'Advertising',
    'Journalism',
    'Media & Cinema Studies',
    'Sports Media',
  ],
  'School of Social Work': [
    'Social Work',
  ],
  'College of Veterinary Medicine': [
    'Veterinary Medicine',
  ],
};

export const COLLEGES = Object.keys(COLLEGE_MAJORS);

export const GRADES = ['Freshman', 'Sophomore', 'Junior', 'Senior'] as const;
