/**
 * API ↔ frontend contract for M03 detail fields.
 *
 * `detail-fields.contract.json` is generated by
 * scripts/generate_detail_fields_contract.py from the real detail-route
 * projection, and a backend test fails if it goes stale. This file closes the
 * other half: for every case, every facet the server put in `explicit`
 * renders "Source says" (with the page's sentence when the API sent one), every
 * facet it put in `inferred` renders "System inference" with its basis, and
 * every facet it left unknown renders "Not provided" — nothing more, nothing
 * less.
 */
import { describe, expect, it } from 'vitest';
import { render, screen, within } from '@testing-library/react';
import contract from './detail-fields.contract.json';
import { DETAIL_FIELD_NAMES, DETAIL_FIELDS_VERSION, FIELD_FACETS, readDetailFields } from './detail-fields';
import { DetailFactsSection } from '@/app/opportunities/[id]/DetailFactsSection';

const t = (key: string) => key;

interface ContractField {
  state: string;
  explicit: Record<string, unknown>;
  inferred: Record<string, { value: unknown; basis: string }>;
  unknown: string[];
  quotes: Record<string, { text: string; source_url: string | null; observed_at: string | null }>;
}
interface ContractCase {
  name: string;
  detail_fields: { version: string; fields: Record<string, ContractField> };
}

const cases = contract.cases as unknown as ContractCase[];

describe('detail-fields contract', () => {
  it('shares the field and facet vocabulary with the backend', () => {
    expect(contract.version).toBe(DETAIL_FIELDS_VERSION);
    expect(contract.field_names).toEqual([...DETAIL_FIELD_NAMES]);
    for (const name of DETAIL_FIELD_NAMES) {
      expect(contract.field_facets[name]).toEqual([...FIELD_FACETS[name]]);
    }
  });

  it.each(cases.map((c) => [c.name, c] as const))('%s: every facet renders the state the API assigned', (_name, c) => {
    const fields = readDetailFields({ detail_fields: c.detail_fields });
    expect(fields).not.toBeNull();
    render(<DetailFactsSection fields={fields!} isFaculty={false} t={t} />);

    for (const [name, apiField] of Object.entries(c.detail_fields.fields)) {
      const group = screen.getByTestId(`fact-field-${name}`);
      expect(group.getAttribute('data-state')).toBe(apiField.state);
      for (const facet of FIELD_FACETS[name as keyof typeof FIELD_FACETS]) {
        const rows = within(group).queryAllByTestId(`fact-${name}-${facet}`);
        const rendered = rows.map((r) => r.getAttribute('data-state')).sort();
        const expected = [
          ...(facet in apiField.explicit ? ['source'] : []),
          ...(facet in apiField.inferred ? ['inferred'] : []),
          ...(apiField.unknown.includes(facet) ? ['unknown'] : []),
        ].sort();
        expect(rendered, `${c.name} ${name}.${facet}`).toEqual(expected);

        const inferredRow = rows.find((r) => r.getAttribute('data-state') === 'inferred');
        if (facet in apiField.inferred) {
          expect(within(inferredRow!).getByText('detail.facts.state.inferred')).toBeInTheDocument();
          expect(
            within(inferredRow!).getByText(`detail.facts.basis.${apiField.inferred[facet].basis}`),
          ).toBeInTheDocument();
        }
        const sourceRow = rows.find((r) => r.getAttribute('data-state') === 'source');
        if (sourceRow) {
          expect(within(sourceRow).getByText('detail.facts.state.source')).toBeInTheDocument();
        }
        // The page's own words appear exactly where the API sent them.
        const quote = within(group).queryByTestId(`fact-${name}-${facet}-quote`);
        if (facet in apiField.quotes) {
          expect(sourceRow, `${c.name} ${name}.${facet}`).toBeDefined();
          expect(within(sourceRow!).getByTestId(`fact-${name}-${facet}-quote`).textContent)
            .toBe(apiField.quotes[facet].text);
          // …linked to the page that sentence was read on.
          const link = within(sourceRow!).queryByTestId(`fact-${name}-${facet}-quote-source`)?.querySelector('a');
          expect(link?.getAttribute('href') ?? null, `${c.name} ${name}.${facet}`)
            .toBe(apiField.quotes[facet].source_url);
        } else {
          expect(quote, `${c.name} ${name}.${facet}`).toBeNull();
        }
      }
    }
  });

  it('never renders an inferred skill as a required skill', () => {
    for (const c of cases) {
      const skills = c.detail_fields.fields.required_skills;
      if (!('mentioned' in skills.inferred)) continue;
      const fields = readDetailFields({ detail_fields: c.detail_fields })!;
      const { unmount } = render(<DetailFactsSection fields={fields} isFaculty={false} t={t} />);
      const required = screen.getByTestId('fact-required_skills-required');
      expect(required.getAttribute('data-state')).toBe(
        'required' in skills.explicit ? 'source' : 'unknown',
      );
      expect(screen.getByTestId('fact-required_skills-mentioned').getAttribute('data-state')).toBe('inferred');
      unmount();
    }
  });
});
