import { beforeEach, expect, it, vi } from 'vitest';
import type { LoadedProfile, ProfilePatchIntent, ProfilePatchOutcome } from '@/lib/supabase';
import type { ProfileData } from '@/lib/types';
const load = vi.fn<() => Promise<LoadedProfile>>();
const commit = vi.fn<(intent: ProfilePatchIntent) => Promise<ProfilePatchOutcome>>();
vi.mock('@/lib/supabase', () => ({ loadProfile: () => load(), commitProfilePatch: (intent: ProfilePatchIntent) => commit(intent) }));
import { advanceOwnerEpoch, captureOwnerToken, syncLocalIdentityOwner, readUserScopedRaw } from '@/lib/identity-owner';
import { resetJournalLaneForTests } from '@/lib/profile-journal';
import * as sync from '@/lib/profile-sync';
import { STORAGE_KEYS } from '@/lib/storage-keys';
import { DEFAULT_PROFILE } from '@/app/home/types';
const base: ProfileData = { ...DEFAULT_PROFILE, name: 'Synthetic owner', research_interests: 'before' };
const cloud = (p: ProfileData | null, revision = 7): LoadedProfile => ({ source: p ? 'cloud' : 'cloud-absent', profile: p as unknown as Record<string, unknown>, revision: p ? revision : 0, token: captureOwnerToken() });
beforeEach(async () => { localStorage.clear(); load.mockReset(); commit.mockReset(); resetJournalLaneForTests(); sync.resetProfileDirtyLedger(); advanceOwnerEpoch(null); advanceOwnerEpoch('deleted-receipt-owner'); await syncLocalIdentityOwner('deleted-receipt-owner'); load.mockResolvedValue(cloud(base)); });
it.each(['saved', 'already-saved', 'conflict-matching', 'conflict-disjoint', 'conflict-overlap'] as const)('a late %s receipt cannot replace confirmed deletion or trigger another write', async (kind) => {
 const hydrated = await sync.hydrateProfile();
 const view = sync.makeProfileViewSnapshot({ renderedProfile: hydrated.profile!, baseProfile: hydrated.baseProfile!, revision: hydrated.revision, token: hydrated.token, identityGeneration: hydrated.token.epoch, source: 'hydration' });
 let release!: (outcome: ProfilePatchOutcome) => void;
 let sent!: () => void; const dispatched = new Promise<void>(done => { sent = done; });
 commit.mockImplementation(() => { sent(); return new Promise(done => { release = done; }); });
 const desired = { ...base, research_interests: 'synthetic saved before deletion' };
 const pending = sync.commitProfileAction({ view, desiredAfter: desired, keys: ['research_interests'], writer: 'red-review', allowCreate: false });
 await dispatched;
 load.mockResolvedValue(cloud(null));
 const deleted = await sync.hydrateProfile();
 expect(deleted.profile).toBeNull(); expect(deleted.hasPending).toBe(false);
 expect(sync.readProfileSyncEnvelope()?.tombstone?.reason).toBe('deleted');
 expect(readUserScopedRaw(STORAGE_KEYS.PROFILE)).toBeNull();
 const status = kind.startsWith('conflict') ? 'conflict' : kind as 'saved' | 'already-saved';
 const remote = kind === 'conflict-disjoint' ? { ...base, major: 'Physics' }
   : kind === 'conflict-overlap' ? { ...base, research_interests: 'another remote value' } : desired;
 release({ status, revision: 8, profile: remote as unknown as Record<string, unknown> });
 const receipt = await pending;
 expect(receipt.result).toEqual({ status: 'missing', reason: 'absent' });
 expect(sync.readProfileSyncEnvelope()?.tombstone?.reason).toBe('deleted');
 expect(readUserScopedRaw(STORAGE_KEYS.PROFILE)).toBeNull();
 expect(sync.readProfileSyncEnvelope()?.pending?.desiredProfile.research_interests).toBe(desired.research_interests);
 expect(await sync.flushPendingProfileWrite(captureOwnerToken())).toEqual({ status: 'missing', reason: 'absent' });
 expect(commit).toHaveBeenCalledTimes(1);
});
